// MODS_LOADED: tfc

class TerraFirmaCraft {

  // - Raw Igneous Intrusive Rocks Array
  static final List rawIgneousIntrusive = [
    item('tfc:raw/granite'),
    item('tfc:raw/gabbro'),
    item('tfc:raw/rhyolite'),
    item('tfc:raw/diorite'),
    item('tfc:raw/breccia'),
    item('tfc:raw/porphyry')
  ]

  // - Raw Igneous Extrusive Rocks Array
  static final List rawIgneousExtrusive = [
    item('tfc:raw/basalt'),
    item('tfc:raw/dacite'),
    item('tfc:raw/andesite'),
    item('tfc:raw/peridotite')
  ]

  // - Raw Metamorphic Rocks Array
  static final List rawMetamorphic = [
    item('tfc:raw/marble'),
    item('tfc:raw/gneiss'),
    item('tfc:raw/schist'),
    item('tfc:raw/quartzite'),
    item('tfc:raw/phyllite'),
    item('tfc:raw/slate'),
    item('tfc:raw/catlinite'),
    item('tfc:raw/novaculite'),
    item('tfc:raw/soapstone'),
    item('tfc:raw/komatiite')
  ]

  // - Raw Sedimentary Rocks Array
  static final List rawSedimentary = [
    item('tfc:raw/shale'),
    item('tfc:raw/dolomite'),
    item('tfc:raw/conglomerate'),
    item('tfc:raw/limestone'),
    item('tfc:raw/rocksalt'),
    item('tfc:raw/claystone'),
    item('tfc:raw/chert'),
    item('tfc:raw/chalk'),
    item('tfc:raw/mudstone'),
    item('tfc:raw/sandstone'),
    item('tfc:raw/siltstone')
  ]

  static final List tfcFlour = [
    item('tfcflorae:food/fonio_flour'),
    item('tfcflorae:food/buckwheat_flour'),
    item('tfcflorae:food/amaranth_flour'),
    item('tfc:food/wheat_flour'),
    item('tfc:food/rye_flour'),
    item('tfc:food/rice_flour'),
    item('tfc:food/oat_flour'),
    item('tfc:food/cornmeal_flour'),
    item('tfc:food/barley_flour'),
    item('tfcflorae:food/spelt_flour'),
    item('tfcflorae:food/quinoa_flour'),
    item('tfcflorae:food/millet_flour')
  ]

  static final List tfcFlatDoughs = [
    item('tfcflorae:food/fonio_flatbread_dough'),
    item('tfcflorae:food/buckwheat_flatbread_dough'),
    item('tfcflorae:food/amaranth_flatbread_dough'),
    item('firmalife:wheat_flatbread_dough'),
    item('firmalife:rye_flatbread_dough'),
    item('firmalife:rice_flatbread_dough'),
    item('firmalife:oat_flatbread_dough'),
    item('firmalife:corn_flatbread_dough'),
    item('firmalife:barley_flatbread_dough'),
    item('tfcflorae:food/spelt_flatbread_dough'),
    item('tfcflorae:food/quinoa_flatbread_dough'),
    item('tfcflorae:food/millet_flatbread_dough')
  ]

  static final List tfcFlatBreads = [
    item('tfcflorae:food/fonio_flatbread'),
    item('tfcflorae:food/buckwheat_flatbread'),
    item('tfcflorae:food/amaranth_flatbread'),
    item('firmalife:wheat_flatbread'),
    item('firmalife:rye_flatbread'),
    item('firmalife:rice_flatbread'),
    item('firmalife:oat_flatbread'),
    item('firmalife:corn_flatbread'),
    item('firmalife:barley_flatbread'),
    item('tfcflorae:food/spelt_flatbread'),
    item('tfcflorae:food/quinoa_flatbread'),
    item('tfcflorae:food/millet_flatbread')
  ]

  static final List tfcDoughs = [
    item('tfcflorae:food/fonio_dough'),
    item('tfcflorae:food/buckwheat_dough'),
    item('tfcflorae:food/amaranth_dough'),
    item('tfc:food/wheat_dough'),
    item('tfc:food/rye_dough'),
    item('tfc:food/rice_dough'),
    item('tfc:food/oat_dough'),
    item('tfc:food/cornmeal_dough'),
    item('tfc:food/barley_dough'),
    item('tfcflorae:food/spelt_dough'),
    item('tfcflorae:food/quinoa_dough'),
    item('tfcflorae:food/millet_dough')
  ]

  static final List tfcBreads = [
    item('tfcflorae:food/fonio_bread'),
    item('tfcflorae:food/buckwheat_bread'),
    item('tfcflorae:food/amaranth_bread'),
    item('tfc:food/wheat_bread'),
    item('tfc:food/rye_bread'),
    item('tfc:food/rice_bread'),
    item('tfc:food/oat_bread'),
    item('tfc:food/cornbread'),
    item('tfc:food/barley_bread'),
    item('tfcflorae:food/spelt_bread'),
    item('tfcflorae:food/quinoa_bread'),
    item('tfcflorae:food/millet_bread')
  ]

  // - TFC Recipes for Macerator(input) Array
  static final List tfcQuernToMaceratorInput = [
    item('tfc:food/olive'),
    item('tfc:food/rye'),
    item('tfc:food/oat'),
    item('tfc:food/barley'),
    item('tfc:food/wheat'),
    item('tfc:food/maize'),
    item('tfc:food/rye_grain'),
    item('tfc:food/oat_grain'),
    item('tfc:food/barley_grain'),
    item('tfc:food/wheat_grain'),
    item('tfc:food/rice_grain'),
    item('tfc:food/maize_grain'),
    item('firmalife:roasted_chestnuts'),
    item('tfc:plants/sargassum'),
    item('tfc:plants/rough_horsetail'),
    item('tfc:plants/grape_hyacinth'),
    item('tfc:plants/blue_orchid'),
    item('tfc:plants/snapdragon_pink'),
    item('tfc:plants/tulip_pink'),
    item('tfc:plants/sacred_datura'),
    item('tfc:plants/foxglove'),
    item('tfc:plants/moss'),
    item('tfc:plants/sapphire_tower'),
    item('tfc:plants/labrador_tea'),
    item('tfc:plants/black_orchid'),
    item('tfc:plants/perovskia'),
    item('tfc:plants/allium'),
    item('tfc:plants/sagebrush'),
    item('tfc:plants/snapdragon_yellow'),
    item('tfc:plants/dandelion'),
    item('tfc:plants/goldenrod'),
    item('tfc:plants/calendula'),
    item('tfc:plants/meads_milkweed'),
    item('tfc:plants/tropical_milkweed'),
    item('tfc:plants/tulip_red'),
    item('tfc:plants/vriesea'),
    item('tfc:plants/snapdragon_red'),
    item('tfc:plants/rose'),
    item('tfc:plants/poppy'),
    item('tfc:plants/guzmania'),
    item('tfc:plants/strelitzia'),
    item('tfc:plants/canna'),
    item('tfc:plants/water_canna'),
    item('tfc:plants/tulip_orange'),
    item('tfc:plants/butterfly_milkweed'),
    item('tfc:plants/nasturtium'),
    item('tfc:plants/yucca'),
    item('tfc:plants/trillium'),
    item('tfc:plants/snapdragon_white'),
    item('tfc:plants/primrose'),
    item('tfc:plants/reindeer_lichen'),
    item('tfc:plants/oxeye_daisy'),
    item('tfc:plants/houstonia'),
    item('tfc:plants/tulip_white'),
    item('tfc:plants/spanish_moss'),
    item('tfc:plants/athyrium_fern'),
    item('tfc:plants/pulsatilla'),
    item('tfc:plants/blood_lily'),
    item('tfc:plants/morning_glory'),
    item('tfc:plants/ryegrass'),
    item('tfc:plants/orchard_grass'),
    item('tfc:plants/switchgrass'),
    item('tfc:plants/licorice_fern'),
    item('tfc:plants/duckweed'),
    item('tfc:plants/ostrich_fern'),
    item('tfc:plants/field_horsetail'),
    item('tfc:plants/fountain_grass'),
    item('tfc:plants/lady_fern'),
    item('tfc:plants/water_lily'),
    item('tfc:plants/barrel_cactus'),
    item('tfc:plants/scutch_grass'),
    item('tfc:plants/tall_fescue_grass'),
    item('tfc:plants/lotus'),
    item('tfc:plants/pistia'),
    item('tfc:plants/toquilla_palm'),
    item('tfc:plants/timothy_grass'),
    item('tfc:plants/sword_fern'),
    item('tfc:plants/tree_fern'),
    item('tfc:plants/pampas_grass')
  ]

  // - TFC Recipes for Macerator(output) Array
  static final List tfcQuernToMaceratorOutput = [
    item('tfc:food/olive_paste'),
    item('tfc:food/rye_grain'),
    item('tfc:food/oat_grain'),
    item('tfc:food/barley_grain'),
    item('tfc:food/wheat_grain'),
    item('tfc:food/maize_grain'),
    item('tfc:food/rye_flour'),
    item('tfc:food/oat_flour'),
    item('tfc:food/barley_flour'),
    item('tfc:food/wheat_flour'),
    item('tfc:food/rice_flour'),
    item('tfc:food/cornmeal_flour'),
    item('firmalife:chestnut_flour'),
    item('tfc:dye/brown'),
    item('tfc:dye/brown'),
    item('tfc:dye/blue'),
    item('tfc:dye/blue'),
    item('minecraft:dye', 9),
    item('minecraft:dye', 9),
    item('minecraft:dye', 9),
    item('minecraft:dye', 9),
    item('minecraft:dye', 10),
    item('minecraft:dye', 12),
    item('minecraft:dye', 12),
    item('minecraft:dye', 5),
    item('minecraft:dye', 5),
    item('minecraft:dye', 5),
    item('minecraft:dye', 11),
    item('minecraft:dye', 11),
    item('minecraft:dye', 11),
    item('minecraft:dye', 11),
    item('minecraft:dye', 11),
    item('minecraft:dye', 11),
    item('minecraft:dye', 1),
    item('minecraft:dye', 1),
    item('minecraft:dye', 1),
    item('minecraft:dye', 1),
    item('minecraft:dye', 1),
    item('minecraft:dye', 1),
    item('minecraft:dye', 1),
    item('minecraft:dye', 14),
    item('minecraft:dye', 14),
    item('minecraft:dye', 14),
    item('minecraft:dye', 14),
    item('minecraft:dye', 14),
    item('minecraft:dye', 14),
    item('minecraft:dye', 7),
    item('tfc:dye/white'),
    item('tfc:dye/white'),
    item('tfc:dye/white'),
    item('tfc:dye/white'),
    item('tfc:dye/white'),
    item('tfc:dye/white'),
    item('tfc:dye/white'),
    item('tfc:dye/white'),
    item('minecraft:dye', 13),
    item('minecraft:dye', 13),
    item('minecraft:dye', 13),
    item('minecraft:dye', 13),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2),
    item('minecraft:dye', 2)
  ]

  // - TFC Cooked Meat Array
  static final List tfcCookedMeat = [
    item('tfc:food/cooked_beef'),
    item('tfc:food/cooked_pork'),
    item('tfc:food/cooked_chicken'),
    item('tfc:food/cooked_mutton'),
    item('tfc:food/cooked_fish'),
    item('tfc:food/cooked_bear'),
    item('tfc:food/cooked_calamari'),
    item('tfc:food/cooked_horse_meat'),
    item('tfc:food/cooked_pheasant'),
    item('tfc:food/cooked_venison'),
    item('tfc:food/cooked_wolf'),
    item('tfc:food/cooked_rabbit'),
    item('tfc:food/cooked_mongoose'),
    item('tfc:food/cooked_gran_feline'),
    item('tfc:food/cooked_camelidae'),
    item('tfcflorae:food/cooked_eel'),
    item('tfcflorae:food/cooked_crab'),
    item('tfcflorae:food/cooked_clam'),
    item('tfcflorae:food/cooked_scallop'),
    item('tfcflorae:food/cooked_starfish'),
    item('tfcflorae:food/cooked_snail'),
    item('tfcflorae:food/cooked_worm')
  ]

  // - TFC Raw Meat Array
  static final List tfcRawMeat = [
    item('tfc:food/beef'),
    item('tfc:food/pork'),
    item('tfc:food/chicken'),
    item('tfc:food/mutton'),
    item('tfc:food/fish'),
    item('tfc:food/bear'),
    item('tfc:food/calamari'),
    item('tfc:food/horse_meat'),
    item('tfc:food/pheasant'),
    item('tfc:food/venison'),
    item('tfc:food/wolf'),
    item('tfc:food/rabbit'),
    item('tfc:food/mongoose'),
    item('tfc:food/gran_feline'),
    item('tfc:food/camelidae'),
    item('tfcflorae:food/raw_eel'),
    item('tfcflorae:food/raw_crab'),
    item('tfcflorae:food/raw_clam'),
    item('tfcflorae:food/raw_scallop'),
    item('tfcflorae:food/raw_starfish'),
    item('tfcflorae:food/raw_snail'),
    item('tfcflorae:food/raw_worm')
  ]

  // - TFC Fired Ceramics
  static final List tfcFiredCeramics = [
    item('tfc:ceramics/fired/mold/hammer_head'),
    item('tfc:ceramics/fired/mold/knife_blade'),
    item('tfc:ceramics/fired/mold/scythe_blade'),
    item('tfc:ceramics/fired/mold/ingot'),
    item('tfc:ceramics/fired/mold/pick_head'),
    item('tfc:ceramics/fired/mold/shovel_head'),
    item('tfc:ceramics/fired/mold/axe_head'),
    item('tfc:ceramics/fired/mold/hoe_head'),
    item('tfc:ceramics/fired/mold/chisel_head'),
    item('tfc:ceramics/fired/mold/sword_blade'),
    item('tfc:ceramics/fired/mold/mace_head'),
    item('tfc:ceramics/fired/mold/saw_blade'),
    item('tfc:ceramics/fired/mold/javelin_head'),
    item('tfc:ceramics/fired/mold/hammer_head'),
    item('tfc:ceramics/fired/mold/propick_head'),
    item('tfc:ceramics/fired/large_vessel'),
    item('tfc:ceramics/fired/vessel'),
    item('tfc:ceramics/fired/vessel_glazed', 15),
    item('tfc:ceramics/fired/vessel_glazed', 14),
    item('tfc:ceramics/fired/vessel_glazed', 13),
    item('tfc:ceramics/fired/vessel_glazed', 12),
    item('tfc:ceramics/fired/vessel_glazed', 11),
    item('tfc:ceramics/fired/vessel_glazed', 10),
    item('tfc:ceramics/fired/vessel_glazed', 9),
    item('tfc:ceramics/fired/vessel_glazed', 8),
    item('tfc:ceramics/fired/vessel_glazed', 7),
    item('tfc:ceramics/fired/vessel_glazed', 6),
    item('tfc:ceramics/fired/vessel_glazed', 5),
    item('tfc:ceramics/fired/vessel_glazed', 4),
    item('tfc:ceramics/fired/vessel_glazed', 3),
    item('tfc:ceramics/fired/vessel_glazed', 2),
    item('tfc:ceramics/fired/vessel_glazed', 1),
    item('tfc:ceramics/fired/vessel_glazed', 0),
    item('tfc:ceramics/fired/pot'),
    item('tfc:ceramics/fired/bowl'),
    item('tfc:ceramics/fired/spindle'),
    item('tfc:ceramics/fired/fire_brick'),
    item('tfc:ceramics/fired/jug'),
    item('tfg:device/crucible'),
    item('minecraft:brick'),
    item('minecraft:flower_pot')
  ]

  // - TFC Fired Ceramics
  static final List tfcUnfiredCeramics = [
    item('tfc:ceramics/unfired/mold/hammer_head'),
    item('tfc:ceramics/unfired/mold/knife_blade'),
    item('tfc:ceramics/unfired/mold/scythe_blade'),
    item('tfc:ceramics/unfired/mold/ingot'),
    item('tfc:ceramics/unfired/mold/pick_head'),
    item('tfc:ceramics/unfired/mold/shovel_head'),
    item('tfc:ceramics/unfired/mold/axe_head'),
    item('tfc:ceramics/unfired/mold/hoe_head'),
    item('tfc:ceramics/unfired/mold/chisel_head'),
    item('tfc:ceramics/unfired/mold/sword_blade'),
    item('tfc:ceramics/unfired/mold/mace_head'),
    item('tfc:ceramics/unfired/mold/saw_blade'),
    item('tfc:ceramics/unfired/mold/javelin_head'),
    item('tfc:ceramics/unfired/mold/hammer_head'),
    item('tfc:ceramics/unfired/mold/propick_head'),
    item('tfc:ceramics/unfired/large_vessel'),
    item('tfc:ceramics/unfired/vessel'),
    item('tfc:ceramics/unfired/vessel_glazed', 15),
    item('tfc:ceramics/unfired/vessel_glazed', 14),
    item('tfc:ceramics/unfired/vessel_glazed', 13),
    item('tfc:ceramics/unfired/vessel_glazed', 12),
    item('tfc:ceramics/unfired/vessel_glazed', 11),
    item('tfc:ceramics/unfired/vessel_glazed', 10),
    item('tfc:ceramics/unfired/vessel_glazed', 9),
    item('tfc:ceramics/unfired/vessel_glazed', 8),
    item('tfc:ceramics/unfired/vessel_glazed', 7),
    item('tfc:ceramics/unfired/vessel_glazed', 6),
    item('tfc:ceramics/unfired/vessel_glazed', 5),
    item('tfc:ceramics/unfired/vessel_glazed', 4),
    item('tfc:ceramics/unfired/vessel_glazed', 3),
    item('tfc:ceramics/unfired/vessel_glazed', 2),
    item('tfc:ceramics/unfired/vessel_glazed', 1),
    item('tfc:ceramics/unfired/vessel_glazed', 0),
    item('tfc:ceramics/unfired/pot'),
    item('tfc:ceramics/unfired/bowl'),
    item('tfc:ceramics/unfired/spindle'),
    item('tfc:ceramics/unfired/fire_brick'),
    item('tfc:ceramics/unfired/jug'),
    item('tfc:ceramics/unfired/crucible'),
    item('tfc:ceramics/unfired/clay_brick'),
    item('tfc:ceramics/unfired/clay_flower_pot')
  ]

  // - TFC Raws Array
  static final List tfcRaws = [
    item('tfc:raw/granite'),
    item('tfc:raw/diorite'),
    item('tfc:raw/gabbro'),
    item('tfc:raw/shale'),
    item('tfc:raw/claystone'),
    item('tfc:raw/rocksalt'),
    item('tfc:raw/limestone'),
    item('tfc:raw/conglomerate'),
    item('tfc:raw/dolomite'),
    item('tfc:raw/chert'),
    item('tfc:raw/chalk'),
    item('tfc:raw/rhyolite'),
    item('tfc:raw/basalt'),
    item('tfc:raw/andesite'),
    item('tfc:raw/dacite'),
    item('tfc:raw/quartzite'),
    item('tfc:raw/slate'),
    item('tfc:raw/phyllite'),
    item('tfc:raw/schist'),
    item('tfc:raw/gneiss'),
    item('tfc:raw/marble'),
    item('tfc:raw/breccia'),
    item('tfc:raw/porphyry'),
    item('tfc:raw/peridotite'),
    item('tfc:raw/mudstone'),
    item('tfc:raw/sandstone'),
    item('tfc:raw/siltstone'),
    item('tfc:raw/catlinite'),
    item('tfc:raw/novaculite'),
    item('tfc:raw/soapstone'),
    item('tfc:raw/komatiite')
  ]


  // - TFC Smooths Array
  static final List tfcSmooths = [
    item('tfc:smooth/granite'),
    item('tfc:smooth/diorite'),
    item('tfc:smooth/gabbro'),
    item('tfc:smooth/shale'),
    item('tfc:smooth/claystone'),
    item('tfc:smooth/rocksalt'),
    item('tfc:smooth/limestone'),
    item('tfc:smooth/conglomerate'),
    item('tfc:smooth/dolomite'),
    item('tfc:smooth/chert'),
    item('tfc:smooth/chalk'),
    item('tfc:smooth/rhyolite'),
    item('tfc:smooth/basalt'),
    item('tfc:smooth/andesite'),
    item('tfc:smooth/dacite'),
    item('tfc:smooth/quartzite'),
    item('tfc:smooth/slate'),
    item('tfc:smooth/phyllite'),
    item('tfc:smooth/schist'),
    item('tfc:smooth/gneiss'),
    item('tfc:smooth/marble'),
    item('tfc:smooth/breccia'),
    item('tfc:smooth/porphyry'),
    item('tfc:smooth/peridotite'),
    item('tfc:smooth/mudstone'),
    item('tfc:smooth/sandstone'),
    item('tfc:smooth/siltstone'),
    item('tfc:smooth/catlinite'),
    item('tfc:smooth/novaculite'),
    item('tfc:smooth/soapstone'),
    item('tfc:smooth/komatiite')
  ]

  // - TFC Cobbles Array
  static final List tfcCobbles = [
    item('tfc:cobble/granite'),
    item('tfc:cobble/diorite'),
    item('tfc:cobble/gabbro'),
    item('tfc:cobble/shale'),
    item('tfc:cobble/claystone'),
    item('tfc:cobble/rocksalt'),
    item('tfc:cobble/limestone'),
    item('tfc:cobble/conglomerate'),
    item('tfc:cobble/dolomite'),
    item('tfc:cobble/chert'),
    item('tfc:cobble/chalk'),
    item('tfc:cobble/rhyolite'),
    item('tfc:cobble/basalt'),
    item('tfc:cobble/andesite'),
    item('tfc:cobble/dacite'),
    item('tfc:cobble/quartzite'),
    item('tfc:cobble/slate'),
    item('tfc:cobble/phyllite'),
    item('tfc:cobble/schist'),
    item('tfc:cobble/gneiss'),
    item('tfc:cobble/marble'),
    item('tfc:cobble/breccia'),
    item('tfc:cobble/porphyry'),
    item('tfc:cobble/peridotite'),
    item('tfc:cobble/mudstone'),
    item('tfc:cobble/sandstone'),
    item('tfc:cobble/siltstone'),
    item('tfc:cobble/catlinite'),
    item('tfc:cobble/novaculite'),
    item('tfc:cobble/soapstone'),
    item('tfc:cobble/komatiite')
  ]

  // - TFC Gravel Array
  static final List tfcGravel = [
    item('tfc:gravel/granite'),
    item('tfc:gravel/diorite'),
    item('tfc:gravel/gabbro'),
    item('tfc:gravel/shale'),
    item('tfc:gravel/claystone'),
    item('tfc:gravel/rocksalt'),
    item('tfc:gravel/limestone'),
    item('tfc:gravel/conglomerate'),
    item('tfc:gravel/dolomite'),
    item('tfc:gravel/chert'),
    item('tfc:gravel/chalk'),
    item('tfc:gravel/rhyolite'),
    item('tfc:gravel/basalt'),
    item('tfc:gravel/andesite'),
    item('tfc:gravel/dacite'),
    item('tfc:gravel/quartzite'),
    item('tfc:gravel/slate'),
    item('tfc:gravel/phyllite'),
    item('tfc:gravel/schist'),
    item('tfc:gravel/gneiss'),
    item('tfc:gravel/marble'),
    item('tfc:gravel/breccia'),
    item('tfc:gravel/porphyry'),
    item('tfc:gravel/peridotite'),
    item('tfc:gravel/mudstone'),
    item('tfc:gravel/sandstone'),
    item('tfc:gravel/siltstone'),
    item('tfc:gravel/catlinite'),
    item('tfc:gravel/novaculite'),
    item('tfc:gravel/soapstone'),
    item('tfc:gravel/komatiite')
  ]

  // - TFC Sand Array
  static final List tfcSands = [
    item('tfc:sand/granite'),
    item('tfc:sand/diorite'),
    item('tfc:sand/gabbro'),
    item('tfc:sand/shale'),
    item('tfc:sand/claystone'),
    item('tfc:sand/rocksalt'),
    item('tfc:sand/limestone'),
    item('tfc:sand/conglomerate'),
    item('tfc:sand/dolomite'),
    item('tfc:sand/chert'),
    item('tfc:sand/chalk'),
    item('tfc:sand/rhyolite'),
    item('tfc:sand/basalt'),
    item('tfc:sand/andesite'),
    item('tfc:sand/dacite'),
    item('tfc:sand/quartzite'),
    item('tfc:sand/slate'),
    item('tfc:sand/phyllite'),
    item('tfc:sand/schist'),
    item('tfc:sand/gneiss'),
    item('tfc:sand/marble'),
    item('tfc:sand/breccia'),
    item('tfc:sand/porphyry'),
    item('tfc:sand/peridotite'),
    item('tfc:sand/mudstone'),
    item('tfc:sand/sandstone'),
    item('tfc:sand/siltstone'),
    item('tfc:sand/catlinite'),
    item('tfc:sand/novaculite'),
    item('tfc:sand/soapstone'),
    item('tfc:sand/komatiite')
  ]

  // - TFC Slabs Cobble Array
  static final List tfcSlabsCobble = [
    item('tfc:slab/cobble/granite'),
    item('tfc:slab/cobble/diorite'),
    item('tfc:slab/cobble/gabbro'),
    item('tfc:slab/cobble/shale'),
    item('tfc:slab/cobble/claystone'),
    item('tfc:slab/cobble/rocksalt'),
    item('tfc:slab/cobble/limestone'),
    item('tfc:slab/cobble/conglomerate'),
    item('tfc:slab/cobble/dolomite'),
    item('tfc:slab/cobble/chert'),
    item('tfc:slab/cobble/chalk'),
    item('tfc:slab/cobble/rhyolite'),
    item('tfc:slab/cobble/basalt'),
    item('tfc:slab/cobble/andesite'),
    item('tfc:slab/cobble/dacite'),
    item('tfc:slab/cobble/quartzite'),
    item('tfc:slab/cobble/slate'),
    item('tfc:slab/cobble/phyllite'),
    item('tfc:slab/cobble/schist'),
    item('tfc:slab/cobble/gneiss'),
    item('tfc:slab/cobble/marble'),
    item('tfc:slab/cobble/breccia'),
    item('tfc:slab/cobble/porphyry'),
    item('tfc:slab/cobble/peridotite'),
    item('tfc:slab/cobble/mudstone'),
    item('tfc:slab/cobble/sandstone'),
    item('tfc:slab/cobble/siltstone'),
    item('tfc:slab/cobble/catlinite'),
    item('tfc:slab/cobble/novaculite'),
    item('tfc:slab/cobble/soapstone'),
    item('tfc:slab/cobble/komatiite')
  ]

  // - TFC Slabs Smooth Array
  static final List tfcSlabsSmooth = [
    item('tfc:slab/smooth/granite'),
    item('tfc:slab/smooth/diorite'),
    item('tfc:slab/smooth/gabbro'),
    item('tfc:slab/smooth/shale'),
    item('tfc:slab/smooth/claystone'),
    item('tfc:slab/smooth/rocksalt'),
    item('tfc:slab/smooth/limestone'),
    item('tfc:slab/smooth/conglomerate'),
    item('tfc:slab/smooth/dolomite'),
    item('tfc:slab/smooth/chert'),
    item('tfc:slab/smooth/chalk'),
    item('tfc:slab/smooth/rhyolite'),
    item('tfc:slab/smooth/basalt'),
    item('tfc:slab/smooth/andesite'),
    item('tfc:slab/smooth/dacite'),
    item('tfc:slab/smooth/quartzite'),
    item('tfc:slab/smooth/slate'),
    item('tfc:slab/smooth/phyllite'),
    item('tfc:slab/smooth/schist'),
    item('tfc:slab/smooth/gneiss'),
    item('tfc:slab/smooth/marble'),
    item('tfc:slab/smooth/breccia'),
    item('tfc:slab/smooth/porphyry'),
    item('tfc:slab/smooth/peridotite'),
    item('tfc:slab/smooth/mudstone'),
    item('tfc:slab/smooth/sandstone'),
    item('tfc:slab/smooth/siltstone'),
    item('tfc:slab/smooth/catlinite'),
    item('tfc:slab/smooth/novaculite'),
    item('tfc:slab/smooth/soapstone'),
    item('tfc:slab/smooth/komatiite')
  ]

  // - TFC Slabs Bricks Array
  static final List tfcSlabsBricks = [
    item('tfc:slab/bricks/granite'),
    item('tfc:slab/bricks/diorite'),
    item('tfc:slab/bricks/gabbro'),
    item('tfc:slab/bricks/shale'),
    item('tfc:slab/bricks/claystone'),
    item('tfc:slab/bricks/rocksalt'),
    item('tfc:slab/bricks/limestone'),
    item('tfc:slab/bricks/conglomerate'),
    item('tfc:slab/bricks/dolomite'),
    item('tfc:slab/bricks/chert'),
    item('tfc:slab/bricks/chalk'),
    item('tfc:slab/bricks/rhyolite'),
    item('tfc:slab/bricks/basalt'),
    item('tfc:slab/bricks/andesite'),
    item('tfc:slab/bricks/dacite'),
    item('tfc:slab/bricks/quartzite'),
    item('tfc:slab/bricks/slate'),
    item('tfc:slab/bricks/phyllite'),
    item('tfc:slab/bricks/schist'),
    item('tfc:slab/bricks/gneiss'),
    item('tfc:slab/bricks/marble'),
    item('tfc:slab/bricks/breccia'),
    item('tfc:slab/bricks/porphyry'),
    item('tfc:slab/bricks/peridotite'),
    item('tfc:slab/bricks/mudstone'),
    item('tfc:slab/bricks/sandstone'),
    item('tfc:slab/bricks/siltstone'),
    item('tfc:slab/bricks/catlinite'),
    item('tfc:slab/bricks/novaculite'),
    item('tfc:slab/bricks/soapstone'),
    item('tfc:slab/bricks/komatiite')
  ]

  // - TFC Stairs Cobble Array
  static final List tfcStairsCobble = [
    item('tfc:stairs/cobble/granite'),
    item('tfc:stairs/cobble/diorite'),
    item('tfc:stairs/cobble/gabbro'),
    item('tfc:stairs/cobble/shale'),
    item('tfc:stairs/cobble/claystone'),
    item('tfc:stairs/cobble/rocksalt'),
    item('tfc:stairs/cobble/limestone'),
    item('tfc:stairs/cobble/conglomerate'),
    item('tfc:stairs/cobble/dolomite'),
    item('tfc:stairs/cobble/chert'),
    item('tfc:stairs/cobble/chalk'),
    item('tfc:stairs/cobble/rhyolite'),
    item('tfc:stairs/cobble/basalt'),
    item('tfc:stairs/cobble/andesite'),
    item('tfc:stairs/cobble/dacite'),
    item('tfc:stairs/cobble/quartzite'),
    item('tfc:stairs/cobble/slate'),
    item('tfc:stairs/cobble/phyllite'),
    item('tfc:stairs/cobble/schist'),
    item('tfc:stairs/cobble/gneiss'),
    item('tfc:stairs/cobble/marble'),
    item('tfc:stairs/cobble/breccia'),
    item('tfc:stairs/cobble/porphyry'),
    item('tfc:stairs/cobble/peridotite'),
    item('tfc:stairs/cobble/mudstone'),
    item('tfc:stairs/cobble/sandstone'),
    item('tfc:stairs/cobble/siltstone'),
    item('tfc:stairs/cobble/catlinite'),
    item('tfc:stairs/cobble/novaculite'),
    item('tfc:stairs/cobble/soapstone'),
    item('tfc:stairs/cobble/komatiite')
  ]

  // - TFC Stairs Smooth Array
  static final List tfcStairsSmooth = [
    item('tfc:stairs/smooth/granite'),
    item('tfc:stairs/smooth/diorite'),
    item('tfc:stairs/smooth/gabbro'),
    item('tfc:stairs/smooth/shale'),
    item('tfc:stairs/smooth/claystone'),
    item('tfc:stairs/smooth/rocksalt'),
    item('tfc:stairs/smooth/limestone'),
    item('tfc:stairs/smooth/conglomerate'),
    item('tfc:stairs/smooth/dolomite'),
    item('tfc:stairs/smooth/chert'),
    item('tfc:stairs/smooth/chalk'),
    item('tfc:stairs/smooth/rhyolite'),
    item('tfc:stairs/smooth/basalt'),
    item('tfc:stairs/smooth/andesite'),
    item('tfc:stairs/smooth/dacite'),
    item('tfc:stairs/smooth/quartzite'),
    item('tfc:stairs/smooth/slate'),
    item('tfc:stairs/smooth/phyllite'),
    item('tfc:stairs/smooth/schist'),
    item('tfc:stairs/smooth/gneiss'),
    item('tfc:stairs/smooth/marble'),
    item('tfc:stairs/smooth/breccia'),
    item('tfc:stairs/smooth/porphyry'),
    item('tfc:stairs/smooth/peridotite'),
    item('tfc:stairs/smooth/mudstone'),
    item('tfc:stairs/smooth/sandstone'),
    item('tfc:stairs/smooth/siltstone'),
    item('tfc:stairs/smooth/catlinite'),
    item('tfc:stairs/smooth/novaculite'),
    item('tfc:stairs/smooth/soapstone'),
    item('tfc:stairs/smooth/komatiite')
  ]

  // - TFC Stairs Bricks Array
  static final List tfcStairsBricks = [
    item('tfc:stairs/bricks/granite'),
    item('tfc:stairs/bricks/diorite'),
    item('tfc:stairs/bricks/gabbro'),
    item('tfc:stairs/bricks/shale'),
    item('tfc:stairs/bricks/claystone'),
    item('tfc:stairs/bricks/rocksalt'),
    item('tfc:stairs/bricks/limestone'),
    item('tfc:stairs/bricks/conglomerate'),
    item('tfc:stairs/bricks/dolomite'),
    item('tfc:stairs/bricks/chert'),
    item('tfc:stairs/bricks/chalk'),
    item('tfc:stairs/bricks/rhyolite'),
    item('tfc:stairs/bricks/basalt'),
    item('tfc:stairs/bricks/andesite'),
    item('tfc:stairs/bricks/dacite'),
    item('tfc:stairs/bricks/quartzite'),
    item('tfc:stairs/bricks/slate'),
    item('tfc:stairs/bricks/phyllite'),
    item('tfc:stairs/bricks/schist'),
    item('tfc:stairs/bricks/gneiss'),
    item('tfc:stairs/bricks/marble'),
    item('tfc:stairs/bricks/breccia'),
    item('tfc:stairs/bricks/porphyry'),
    item('tfc:stairs/bricks/peridotite'),
    item('tfc:stairs/bricks/mudstone'),
    item('tfc:stairs/bricks/sandstone'),
    item('tfc:stairs/bricks/siltstone'),
    item('tfc:stairs/bricks/catlinite'),
    item('tfc:stairs/bricks/novaculite'),
    item('tfc:stairs/bricks/soapstone'),
    item('tfc:stairs/bricks/komatiite')
  ]

  // - TFC Stone Pressure Plates Array
  static final List tfcStonePressurePlates = [
    item('tfc:stone/pressure_plate/granite'),
    item('tfc:stone/pressure_plate/diorite'),
    item('tfc:stone/pressure_plate/gabbro'),
    item('tfc:stone/pressure_plate/shale'),
    item('tfc:stone/pressure_plate/claystone'),
    item('tfc:stone/pressure_plate/rocksalt'),
    item('tfc:stone/pressure_plate/limestone'),
    item('tfc:stone/pressure_plate/conglomerate'),
    item('tfc:stone/pressure_plate/dolomite'),
    item('tfc:stone/pressure_plate/chert'),
    item('tfc:stone/pressure_plate/chalk'),
    item('tfc:stone/pressure_plate/rhyolite'),
    item('tfc:stone/pressure_plate/basalt'),
    item('tfc:stone/pressure_plate/andesite'),
    item('tfc:stone/pressure_plate/dacite'),
    item('tfc:stone/pressure_plate/quartzite'),
    item('tfc:stone/pressure_plate/slate'),
    item('tfc:stone/pressure_plate/phyllite'),
    item('tfc:stone/pressure_plate/schist'),
    item('tfc:stone/pressure_plate/gneiss'),
    item('tfc:stone/pressure_plate/marble'),
    item('tfc:stone/pressure_plate/breccia'),
    item('tfc:stone/pressure_plate/porphyry'),
    item('tfc:stone/pressure_plate/peridotite'),
    item('tfc:stone/pressure_plate/mudstone'),
    item('tfc:stone/pressure_plate/sandstone'),
    item('tfc:stone/pressure_plate/siltstone'),
    item('tfc:stone/pressure_plate/catlinite'),
    item('tfc:stone/pressure_plate/novaculite'),
    item('tfc:stone/pressure_plate/soapstone'),
    item('tfc:stone/pressure_plate/komatiite')
  ]

  // - TFC Stone Buttons Array
  static final List tfcStoneButtons = [
    item('tfc:stone/button/granite'),
    item('tfc:stone/button/diorite'),
    item('tfc:stone/button/gabbro'),
    item('tfc:stone/button/shale'),
    item('tfc:stone/button/claystone'),
    item('tfc:stone/button/rocksalt'),
    item('tfc:stone/button/limestone'),
    item('tfc:stone/button/conglomerate'),
    item('tfc:stone/button/dolomite'),
    item('tfc:stone/button/chert'),
    item('tfc:stone/button/chalk'),
    item('tfc:stone/button/rhyolite'),
    item('tfc:stone/button/basalt'),
    item('tfc:stone/button/andesite'),
    item('tfc:stone/button/dacite'),
    item('tfc:stone/button/quartzite'),
    item('tfc:stone/button/slate'),
    item('tfc:stone/button/phyllite'),
    item('tfc:stone/button/schist'),
    item('tfc:stone/button/gneiss'),
    item('tfc:stone/button/marble'),
    item('tfc:stone/button/breccia'),
    item('tfc:stone/button/porphyry'),
    item('tfc:stone/button/peridotite'),
    item('tfc:stone/button/mudstone'),
    item('tfc:stone/button/sandstone'),
    item('tfc:stone/button/siltstone'),
    item('tfc:stone/button/catlinite'),
    item('tfc:stone/button/novaculite'),
    item('tfc:stone/button/soapstone'),
    item('tfc:stone/button/komatiite')
  ]


  // - TFC Bricks Array
  static final List tfcBricksItem = [
    item('tfc:brick/granite'),
    item('tfc:brick/diorite'),
    item('tfc:brick/gabbro'),
    item('tfc:brick/shale'),
    item('tfc:brick/claystone'),
    item('tfc:brick/rocksalt'),
    item('tfc:brick/limestone'),
    item('tfc:brick/conglomerate'),
    item('tfc:brick/dolomite'),
    item('tfc:brick/chert'),
    item('tfc:brick/chalk'),
    item('tfc:brick/rhyolite'),
    item('tfc:brick/basalt'),
    item('tfc:brick/andesite'),
    item('tfc:brick/dacite'),
    item('tfc:brick/quartzite'),
    item('tfc:brick/slate'),
    item('tfc:brick/phyllite'),
    item('tfc:brick/schist'),
    item('tfc:brick/gneiss'),
    item('tfc:brick/marble'),
    item('tfc:brick/breccia'),
    item('tfc:brick/porphyry'),
    item('tfc:brick/peridotite'),
    item('tfc:brick/mudstone'),
    item('tfc:brick/sandstone'),
    item('tfc:brick/siltstone'),
    item('tfc:brick/catlinite'),
    item('tfc:brick/novaculite'),
    item('tfc:brick/soapstone'),
    item('tfc:brick/komatiite')
  ]


  // - TFC Bricks Array
  static final List tfcBricksBlock = [
    item('tfc:bricks/granite'),
    item('tfc:bricks/diorite'),
    item('tfc:bricks/gabbro'),
    item('tfc:bricks/shale'),
    item('tfc:bricks/claystone'),
    item('tfc:bricks/rocksalt'),
    item('tfc:bricks/limestone'),
    item('tfc:bricks/conglomerate'),
    item('tfc:bricks/dolomite'),
    item('tfc:bricks/chert'),
    item('tfc:bricks/chalk'),
    item('tfc:bricks/rhyolite'),
    item('tfc:bricks/basalt'),
    item('tfc:bricks/andesite'),
    item('tfc:bricks/dacite'),
    item('tfc:bricks/quartzite'),
    item('tfc:bricks/slate'),
    item('tfc:bricks/phyllite'),
    item('tfc:bricks/schist'),
    item('tfc:bricks/gneiss'),
    item('tfc:bricks/marble'),
    item('tfc:bricks/breccia'),
    item('tfc:bricks/porphyry'),
    item('tfc:bricks/peridotite'),
    item('tfc:bricks/mudstone'),
    item('tfc:bricks/sandstone'),
    item('tfc:bricks/siltstone'),
    item('tfc:bricks/catlinite'),
    item('tfc:bricks/novaculite'),
    item('tfc:bricks/soapstone'),
    item('tfc:bricks/komatiite')
  ]


  // - TFC Saplings Array
  static final List tfcSaplings = [
    item('tfc:wood/sapling/acacia'),
    item('tfc:wood/sapling/african_padauk'),
    item('tfc:wood/sapling/alder'),
    item('tfc:wood/sapling/angelim'),
    item('tfc:wood/sapling/ash'),
    item('tfc:wood/sapling/aspen'),
    item('tfc:wood/sapling/bald_cypress'),
    item('tfc:wood/sapling/baobab'),
    item('tfc:wood/sapling/beech'),
    item('tfc:wood/sapling/birch'),
    item('tfc:wood/sapling/black_walnut'),
    item('tfc:wood/sapling/blackwood'),
    item('tfc:wood/sapling/box'),
    item('tfc:wood/sapling/brazilwood'),
    item('tfc:wood/sapling/butternut'),
    item('tfc:wood/sapling/chestnut'),
    item('tfc:wood/sapling/cocobolo'),
    item('tfc:wood/sapling/cypress'),
    item('tfc:wood/sapling/douglas_fir'),
    item('tfc:wood/sapling/ebony'),
    item('tfc:wood/sapling/european_oak'),
    item('tfc:wood/sapling/fever'),
    item('tfc:wood/sapling/fruitwood'),
    item('tfc:wood/sapling/ginkgo'),
    item('tfc:wood/sapling/greenheart'),
    item('tfc:wood/sapling/hawthorn'),
    item('tfc:wood/sapling/hazel'),
    item('tfc:wood/sapling/hemlock'),
    item('tfc:wood/sapling/hevea'),
    item('tfc:wood/sapling/hickory'),
    item('tfc:wood/sapling/holly'),
    item('tfc:wood/sapling/hornbeam'),
    item('tfc:wood/sapling/ipe'),
    item('tfc:wood/sapling/iroko'),
    item('tfc:wood/sapling/ironwood'),
    item('tfc:wood/sapling/jacaranda'),
    item('tfc:wood/sapling/juniper'),
    item('tfc:wood/sapling/kapok'),
    item('tfc:wood/sapling/kauri'),
    item('tfc:wood/sapling/larch'),
    item('tfc:wood/sapling/limba'),
    item('tfc:wood/sapling/locust'),
    item('tfc:wood/sapling/logwood'),
    item('tfc:wood/sapling/maclura'),
    item('tfc:wood/sapling/mahoe'),
    item('tfc:wood/sapling/mahogany'),
    item('tfc:wood/sapling/mangrove'),
    item('tfc:wood/sapling/maple'),
    item('tfc:wood/sapling/marblewood'),
    item('tfc:wood/sapling/messmate'),
    item('tfc:wood/sapling/mountain_ash'),
    item('tfc:wood/sapling/nordmann_fir'),
    item('tfc:wood/sapling/norway_spruce'),
    item('tfc:wood/sapling/oak'),
    item('tfc:wood/sapling/palm'),
    item('tfc:wood/sapling/pine'),
    item('tfc:wood/sapling/pink_cherry'),
    item('tfc:wood/sapling/pink_ivory'),
    item('tfc:wood/sapling/poplar'),
    item('tfc:wood/sapling/purpleheart'),
    item('tfc:wood/sapling/red_cedar'),
    item('tfc:wood/sapling/red_elm'),
    item('tfc:wood/sapling/redwood'),
    item('tfc:wood/sapling/rosewood'),
    item('tfc:wood/sapling/rowan'),
    item('tfc:wood/sapling/rubber_fig'),
    item('tfc:wood/sapling/sequoia'),
    item('tfc:wood/sapling/spruce'),
    item('tfc:wood/sapling/sweetgum'),
    item('tfc:wood/sapling/sycamore'),
    item('tfc:wood/sapling/syzygium'),
    item('tfc:wood/sapling/teak'),
    item('tfc:wood/sapling/walnut'),
    item('tfc:wood/sapling/wenge'),
    item('tfc:wood/sapling/white_cedar'),
    item('tfc:wood/sapling/white_cherry'),
    item('tfc:wood/sapling/white_elm'),
    item('tfc:wood/sapling/whitebeam'),
    item('tfc:wood/sapling/willow'),
    item('tfc:wood/sapling/yellow_meranti'),
    item('tfc:wood/sapling/yew'),
    item('tfc:wood/sapling/zebrawood'),
    item('tfcflorae:wood/sapling/joshua_tree'),
    item('tfcflorae:wood/sapling/arrow_bamboo'),
    item('tfcflorae:wood/sapling/black_bamboo'),
    item('tfcflorae:wood/sapling/blue_bamboo'),
    item('tfcflorae:wood/sapling/dragon_bamboo'),
    item('tfcflorae:wood/sapling/golden_bamboo'),
    item('tfcflorae:wood/sapling/narrow_leaf_bamboo'),
    item('tfcflorae:wood/sapling/red_bamboo'),
    item('tfcflorae:wood/sapling/temple_bamboo'),
    item('tfcflorae:wood/sapling/thorny_bamboo'),
    item('tfcflorae:wood/sapling/timber_bamboo'),
    item('tfcflorae:wood/sapling/tinwa_bamboo'),
    item('tfcflorae:wood/sapling/weavers_bamboo'),
    item('firmalife:cinnamon_sapling'),
    item('firmalife:cocoa_sapling'),
    item('tfc:fruit_trees/sapling/banana'),
    item('tfc:fruit_trees/sapling/cherry'),
    item('tfc:fruit_trees/sapling/green_apple'),
    item('tfc:fruit_trees/sapling/lemon'),
    item('tfc:fruit_trees/sapling/olive'),
    item('tfc:fruit_trees/sapling/orange'),
    item('tfc:fruit_trees/sapling/peach'),
    item('tfc:fruit_trees/sapling/plum'),
    item('tfc:fruit_trees/sapling/red_apple'),
    item('tfcflorae:wood/fruit_tree/sapling/cassia_cinnamon'),
    item('tfcflorae:wood/fruit_tree/sapling/ceylon_cinnamon'),
    item('tfc:wood/sapling/eucalyptus'),
    // item('tfc:wood/sapling/eucalyptus'),
    // item('tfc:wood/sapling/eucalyptus'),
    // item('tfc:wood/sapling/eucalyptus')
  ]

  // - Бревна
  static final List logs = [
    item('tfc:wood/log/acacia'),
    item('tfc:wood/log/african_padauk'),
    item('tfc:wood/log/alder'),
    item('tfc:wood/log/angelim'),
    item('tfc:wood/log/ash'),
    item('tfc:wood/log/aspen'),
    item('tfc:wood/log/bald_cypress'),
    item('tfc:wood/log/baobab'),
    item('tfc:wood/log/beech'),
    item('tfc:wood/log/birch'),
    item('tfc:wood/log/black_walnut'),
    item('tfc:wood/log/blackwood'),
    item('tfc:wood/log/box'),
    item('tfc:wood/log/brazilwood'),
    item('tfc:wood/log/butternut'),
    item('tfc:wood/log/chestnut'),
    item('tfc:wood/log/cocobolo'),
    item('tfc:wood/log/cypress'),
    item('tfc:wood/log/douglas_fir'),
    item('tfc:wood/log/ebony'),
    item('tfc:wood/log/european_oak'),
    item('tfc:wood/log/fever'),
    item('tfc:wood/log/fruitwood'),
    item('tfc:wood/log/ginkgo'),
    item('tfc:wood/log/greenheart'),
    item('tfc:wood/log/hawthorn'),
    item('tfc:wood/log/hazel'),
    item('tfc:wood/log/hemlock'),
    item('tfc:wood/log/hevea'),
    item('tfc:wood/log/hickory'),
    item('tfc:wood/log/holly'),
    item('tfc:wood/log/hornbeam'),
    item('tfc:wood/log/ipe'),
    item('tfc:wood/log/iroko'),
    item('tfc:wood/log/ironwood'),
    item('tfc:wood/log/jacaranda'),
    item('tfc:wood/log/juniper'),
    item('tfc:wood/log/kapok'),
    item('tfc:wood/log/kauri'),
    item('tfc:wood/log/larch'),
    item('tfc:wood/log/limba'),
    item('tfc:wood/log/locust'),
    item('tfc:wood/log/logwood'),
    item('tfc:wood/log/maclura'),
    item('tfc:wood/log/mahoe'),
    item('tfc:wood/log/mahogany'),
    item('tfc:wood/log/mangrove'),
    item('tfc:wood/log/maple'),
    item('tfc:wood/log/marblewood'),
    item('tfc:wood/log/messmate'),
    item('tfc:wood/log/mountain_ash'),
    item('tfc:wood/log/nordmann_fir'),
    item('tfc:wood/log/norway_spruce'),
    item('tfc:wood/log/oak'),
    item('tfc:wood/log/palm'),
    item('tfc:wood/log/pine'),
    item('tfc:wood/log/pink_cherry'),
    item('tfc:wood/log/pink_ivory'),
    item('tfc:wood/log/poplar'),
    item('tfc:wood/log/purpleheart'),
    item('tfc:wood/log/red_cedar'),
    item('tfc:wood/log/red_elm'),
    item('tfc:wood/log/redwood'),
    item('tfc:wood/log/rosewood'),
    item('tfc:wood/log/rowan'),
    item('tfc:wood/log/rubber_fig'),
    item('tfc:wood/log/sequoia'),
    item('tfc:wood/log/spruce'),
    item('tfc:wood/log/sweetgum'),
    item('tfc:wood/log/sycamore'),
    item('tfc:wood/log/syzygium'),
    item('tfc:wood/log/teak'),
    item('tfc:wood/log/walnut'),
    item('tfc:wood/log/wenge'),
    item('tfc:wood/log/white_cedar'),
    item('tfc:wood/log/white_cherry'),
    item('tfc:wood/log/white_elm'),
    item('tfc:wood/log/whitebeam'),
    item('tfc:wood/log/willow'),
    item('tfc:wood/log/yellow_meranti'),
    item('tfc:wood/log/yew'),
    item('tfc:wood/log/zebrawood'),
    item('tfcflorae:wood/log/joshua_tree'),
    item('tfcflorae:wood/pole/arrow_bamboo'),
    item('tfcflorae:wood/pole/black_bamboo'),
    item('tfcflorae:wood/pole/blue_bamboo'),
    item('tfcflorae:wood/pole/dragon_bamboo'),
    item('tfcflorae:wood/pole/golden_bamboo'),
    item('tfcflorae:wood/pole/narrow_leaf_bamboo'),
    item('tfcflorae:wood/pole/red_bamboo'),
    item('tfcflorae:wood/pole/temple_bamboo'),
    item('tfcflorae:wood/pole/thorny_bamboo'),
    item('tfcflorae:wood/pole/timber_bamboo'),
    item('tfcflorae:wood/pole/tinwa_bamboo'),
    item('tfcflorae:wood/pole/weavers_bamboo'),
    item('firmalife:cinnamon_pole'),
    item('firmalife:cocoa_pole'),
    item('firmalife:banana_pole'),
    item('firmalife:cherry_pole'),
    item('firmalife:green_apple_pole'),
    item('firmalife:lemon_pole'),
    item('firmalife:olive_pole'),
    item('firmalife:orange_pole'),
    item('firmalife:peach_pole'),
    item('firmalife:plum_pole'),
    item('firmalife:red_apple_pole'),
    item('tfcflorae:wood/fruit_tree/pole/cassia_cinnamon'),
    item('tfcflorae:wood/fruit_tree/pole/ceylon_cinnamon'),
    item('tfc:wood/log/eucalyptus'),
    // item('tfcflorae:wood/log/argyle_eucalyptus'),
    // item('tfcflorae:wood/log/rainbow_eucalyptus'),
    // item('tfcflorae:wood/log/snow_gum_eucalyptus')
  ]



  // - TFC Metal Trapdoors
  static final List tfcMetal_Trapdoors = [
    item('tfc:metal/trapdoor/gold'),
    item('tfc:metal/trapdoor/lead'),
    item('tfc:metal/trapdoor/nickel'),
    item('tfc:metal/trapdoor/rose_gold'),
    item('tfc:metal/trapdoor/silver'),
    item('tfc:metal/trapdoor/tin'),
    item('tfc:metal/trapdoor/zinc'),
    item('tfc:metal/trapdoor/sterling_silver'),
    item('tfc:metal/trapdoor/copper'),
    item('tfc:metal/trapdoor/bismuth'),
    item('tfc:metal/trapdoor/brass'),
    item('tfc:metal/trapdoor/bismuth_bronze'),
    item('tfc:metal/trapdoor/bronze'),
    item('tfc:metal/trapdoor/black_bronze'),
    item('tfc:metal/trapdoor/wrought_iron'),
    item('tfc:metal/trapdoor/steel'),
    item('tfc:metal/trapdoor/platinum'),
    item('tfc:metal/trapdoor/black_steel'),
    item('tfc:metal/trapdoor/blue_steel'),
    item('tfc:metal/trapdoor/red_steel')
  ]

  // - All Seeds Array
  static final List tfcSeeds = [
    item('tfc:crop/seeds/barley'),
    item('tfc:crop/seeds/maize'),
    item('tfc:crop/seeds/oat'),
    item('tfc:crop/seeds/rice'),
    item('tfc:crop/seeds/rye'),
    item('tfc:crop/seeds/wheat'),
    item('tfc:crop/seeds/beet'),
    item('tfc:crop/seeds/cabbage'),
    item('tfc:crop/seeds/carrot'),
    item('tfc:crop/seeds/garlic'),
    item('tfc:crop/seeds/green_bean'),
    item('tfc:crop/seeds/onion'),
    item('tfc:crop/seeds/potato'),
    item('tfc:crop/seeds/soybean'),
    item('tfc:crop/seeds/squash'),
    item('tfc:crop/seeds/sugarcane'),
    item('tfc:crop/seeds/tomato'),
    item('tfc:crop/seeds/red_bell_pepper'),
    item('tfc:crop/seeds/yellow_bell_pepper'),
    item('tfc:crop/seeds/jute'),
    item('tfcflorae:crop/product/malt_spelt'),
    item('tfcflorae:crop/seeds/amaranth'),
    item('tfcflorae:crop/seeds/buckwheat'),
    item('tfcflorae:crop/seeds/fonio'),
    item('tfcflorae:crop/seeds/millet'),
    item('tfcflorae:crop/seeds/quinoa'),
    item('tfcflorae:crop/seeds/spelt'),
    item('tfcflorae:crop/seeds/black_eyed_peas'),
    item('tfcflorae:crop/seeds/cayenne_pepper'),
    item('tfcflorae:crop/seeds/ginger'),
    item('tfcflorae:crop/seeds/ginseng'),
    item('tfcflorae:crop/seeds/rutabaga'),
    item('tfcflorae:crop/seeds/turnip'),
    item('tfcflorae:crop/seeds/sugar_beet'),
    item('tfcflorae:crop/seeds/purple_grape'),
    item('tfcflorae:crop/seeds/green_grape'),
    item('tfcflorae:crop/seeds/liquorice_root'),
    item('tfcflorae:crop/seeds/coffea'),
    item('tfcflorae:crop/seeds/agave'),
    item('tfcflorae:crop/seeds/coca'),
    item('tfcflorae:crop/seeds/cotton'),
    item('tfcflorae:crop/seeds/flax'),
    item('tfcflorae:crop/seeds/hemp'),
    item('tfcflorae:crop/seeds/hop'),
    item('tfcflorae:crop/seeds/indigo'),
    item('tfcflorae:crop/seeds/madder'),
    item('tfcflorae:crop/seeds/opium_poppy'),
    item('tfcflorae:crop/seeds/rape'),
    item('tfcflorae:crop/seeds/weld'),
    item('tfcflorae:crop/seeds/woad'),
    item('tfcflorae:crop/seeds/tobacco')
  ]


  static final List tfcAlabaster = [
    item('tfc:alabaster/raw/white'),
    item('tfc:alabaster/raw/orange'),
    item('tfc:alabaster/raw/magenta'),
    item('tfc:alabaster/raw/light_blue'),
    item('tfc:alabaster/raw/yellow'),
    item('tfc:alabaster/raw/lime'),
    item('tfc:alabaster/raw/pink'),
    item('tfc:alabaster/raw/gray'),
    item('tfc:alabaster/raw/silver'),
    item('tfc:alabaster/raw/cyan'),
    item('tfc:alabaster/raw/purple'),
    item('tfc:alabaster/raw/blue'),
    item('tfc:alabaster/raw/brown'),
    item('tfc:alabaster/raw/green'),
    item('tfc:alabaster/raw/red'),
    item('tfc:alabaster/raw/black')
  ]

  static final List tfcAlabasterBricks = [
    item('tfc:alabaster/bricks/white'),
    item('tfc:alabaster/bricks/orange'),
    item('tfc:alabaster/bricks/magenta'),
    item('tfc:alabaster/bricks/light_blue'),
    item('tfc:alabaster/bricks/yellow'),
    item('tfc:alabaster/bricks/lime'),
    item('tfc:alabaster/bricks/pink'),
    item('tfc:alabaster/bricks/gray'),
    item('tfc:alabaster/bricks/silver'),
    item('tfc:alabaster/bricks/cyan'),
    item('tfc:alabaster/bricks/purple'),
    item('tfc:alabaster/bricks/blue'),
    item('tfc:alabaster/bricks/brown'),
    item('tfc:alabaster/bricks/green'),
    item('tfc:alabaster/bricks/red'),
    item('tfc:alabaster/bricks/black')
  ]

  static final List tfcAlabasterPolished = [
    item('tfc:alabaster/polished/white'),
    item('tfc:alabaster/polished/orange'),
    item('tfc:alabaster/polished/magenta'),
    item('tfc:alabaster/polished/light_blue'),
    item('tfc:alabaster/polished/yellow'),
    item('tfc:alabaster/polished/lime'),
    item('tfc:alabaster/polished/pink'),
    item('tfc:alabaster/polished/gray'),
    item('tfc:alabaster/polished/silver'),
    item('tfc:alabaster/polished/cyan'),
    item('tfc:alabaster/polished/purple'),
    item('tfc:alabaster/polished/blue'),
    item('tfc:alabaster/polished/brown'),
    item('tfc:alabaster/polished/green'),
    item('tfc:alabaster/polished/red'),
    item('tfc:alabaster/polished/black')
  ]

  // - TFC Metal Trapdoors
  static final List tfcMetalTrapdoors = [
    item('tfc:metal/trapdoor/gold'),
    item('tfc:metal/trapdoor/lead'),
    item('tfc:metal/trapdoor/nickel'),
    item('tfc:metal/trapdoor/rose_gold'),
    item('tfc:metal/trapdoor/silver'),
    item('tfc:metal/trapdoor/tin'),
    item('tfc:metal/trapdoor/zinc'),
    item('tfc:metal/trapdoor/sterling_silver'),
    item('tfc:metal/trapdoor/copper'),
    item('tfc:metal/trapdoor/bismuth'),
    item('tfc:metal/trapdoor/brass'),
    item('tfc:metal/trapdoor/bismuth_bronze'),
    item('tfc:metal/trapdoor/bronze'),
    item('tfc:metal/trapdoor/black_bronze'),
    item('tfc:metal/trapdoor/wrought_iron'),
    item('tfc:metal/trapdoor/steel'),
    item('tfc:metal/trapdoor/platinum'),
    item('tfc:metal/trapdoor/black_steel'),
    item('tfc:metal/trapdoor/blue_steel'),
    item('tfc:metal/trapdoor/red_steel')
  ]

  // - All Plants Array
  static final List tfcPlants = [
    item('tfc:food/barley'),
    item('tfc:food/maize'),
    item('tfc:food/oat'),
    item('tfc:food/rice'),
    item('tfc:food/rye'),
    item('tfc:food/wheat'),
    item('tfc:food/beet'),
    item('tfc:food/cabbage'),
    item('tfc:food/carrot'),
    item('tfc:food/garlic'),
    item('tfc:food/green_bean'),
    item('tfc:food/onion'),
    item('tfc:food/potato'),
    item('tfc:food/soybean'),
    item('tfc:food/squash'),
    item('tfc:food/sugarcane'),
    item('tfc:food/tomato'),
    item('tfc:food/red_bell_pepper'),
    item('tfc:food/yellow_bell_pepper'),
    item('tfc:crop/product/jute'),
    item('tfcflorae:crop/product/malt_spelt'),
    item('tfcflorae:food/amaranth'),
    item('tfcflorae:food/buckwheat'),
    item('tfcflorae:food/fonio'),
    item('tfcflorae:food/millet'),
    item('tfcflorae:food/quinoa'),
    item('tfcflorae:food/spelt'),
    item('tfcflorae:food/black_eyed_peas'),
    item('tfcflorae:food/red_cayenne_pepper'),
    item('tfcflorae:food/ginger'),
    item('tfcflorae:food/ginseng'),
    item('tfcflorae:food/rutabaga'),
    item('tfcflorae:food/turnip'),
    item('tfcflorae:food/sugar_beet'),
    item('tfcflorae:food/purple_grape'),
    item('tfcflorae:food/green_grape'),
    item('tfcflorae:food/liquorice_root'),
    item('tfcflorae:food/coffea_cherries'),
    item('tfcflorae:crop/product/agave'),
    item('tfcflorae:food/coca_leaf'),
    item('tfcflorae:crop/product/cotton_boll'),
    item('tfcflorae:crop/product/flax'),
    item('tfcflorae:crop/product/hemp'),
    item('tfcflorae:crop/product/hops'),
    item('tfcflorae:crop/product/indigo'),
    item('tfcflorae:crop/product/madder'),
    item('tfcflorae:food/opium_poppy_seed'),
    item('tfcflorae:crop/product/rape'),
    item('tfcflorae:crop/product/weld'),
    item('tfcflorae:crop/product/woad'),
    item('tfcflorae:food/tobacco_leaf')
  ]

  static final List tfcSaws = [
    item('tfc:metal/saw/bismuth_bronze'),
    item('tfc:metal/saw/black_bronze'),
    item('tfc:metal/saw/black_steel'),
    item('tfc:metal/saw/blue_steel'),
    item('tfc:metal/saw/bronze'),
    item('tfc:metal/saw/copper'),
    item('tfc:metal/saw/red_steel'),
    item('tfc:metal/saw/steel'),
    item('tfc:metal/saw/wrought_iron'),
    item('tfc:metal/saw_blade/bismuth_bronze'),
    item('tfc:metal/saw_blade/black_bronze'),
    item('tfc:metal/saw_blade/black_steel'),
    item('tfc:metal/saw_blade/blue_steel'),
    item('tfc:metal/saw_blade/bronze'),
    item('tfc:metal/saw_blade/copper'),
    item('tfc:metal/saw_blade/red_steel'),
    item('tfc:metal/saw_blade/steel'),
    item('tfc:metal/saw_blade/wrought_iron')
  ]

  // - Fibers
  static final List tfcFibres = [
    item('tfg:animal/product/wool'),
    item('firmalife:pineapple_fiber'),
    item('tfcflorae:crop/product/yucca_fiber'),
    item('tfcflorae:crop/product/sisal_fiber'),
    item('tfcflorae:crop/product/hemp_fiber'),
    item('tfcflorae:crop/product/flax_fiber'),
    item('tfcflorae:crop/product/cotton_boll')
  ]

  // - Yarns
  static final List tfcStrings = [
    item('tfg:animal/product/wool_yarn'),
    item('firmalife:pineapple_yarn'),
    item('tfcflorae:crop/product/yucca_string'),
    item('tfcflorae:crop/product/sisal_string'),
    item('tfcflorae:crop/product/hemp_string'),
    item('tfcflorae:crop/product/linen_string'),
    item('tfcflorae:crop/product/cotton_yarn')
  ]

  static final List tfcHelmets = [
    item('tfc:metal/helmet/bismuth_bronze'),
    item('tfc:metal/helmet/black_bronze'),
    item('tfc:metal/helmet/bronze'),
    item('tfc:metal/helmet/copper'),
    item('tfc:metal/helmet/wrought_iron'),
    item('tfc:metal/helmet/steel'),
    item('tfc:metal/helmet/black_steel'),
    item('tfc:metal/helmet/blue_steel'),
    item('tfc:metal/helmet/red_steel')
  ]
  static final List tfcChestplates = [
    item('tfc:metal/chestplate/bismuth_bronze'),
    item('tfc:metal/chestplate/black_bronze'),
    item('tfc:metal/chestplate/bronze'),
    item('tfc:metal/chestplate/copper'),
    item('tfc:metal/chestplate/wrought_iron'),
    item('tfc:metal/chestplate/steel'),
    item('tfc:metal/chestplate/black_steel'),
    item('tfc:metal/chestplate/blue_steel'),
    item('tfc:metal/chestplate/red_steel')
  ]
  static final List tfcGreaves = [
    item('tfc:metal/greaves/bismuth_bronze'),
    item('tfc:metal/greaves/black_bronze'),
    item('tfc:metal/greaves/bronze'),
    item('tfc:metal/greaves/copper'),
    item('tfc:metal/greaves/wrought_iron'),
    item('tfc:metal/greaves/steel'),
    item('tfc:metal/greaves/black_steel'),
    item('tfc:metal/greaves/blue_steel'),
    item('tfc:metal/greaves/red_steel')
  ]
  static final List tfcBoots = [
    item('tfc:metal/boots/bismuth_bronze'),
    item('tfc:metal/boots/black_bronze'),
    item('tfc:metal/boots/bronze'),
    item('tfc:metal/boots/copper'),
    item('tfc:metal/boots/wrought_iron'),
    item('tfc:metal/boots/steel'),
    item('tfc:metal/boots/black_steel'),
    item('tfc:metal/boots/blue_steel'),
    item('tfc:metal/boots/red_steel')
  ]


  static final List smallClayUnfiredColoredVessels = [
    item('tfc:ceramics/unfired/vessel_glazed', 0),
    item('tfc:ceramics/unfired/vessel_glazed', 1),
    item('tfc:ceramics/unfired/vessel_glazed', 2),
    item('tfc:ceramics/unfired/vessel_glazed', 3),
    item('tfc:ceramics/unfired/vessel_glazed', 4),
    item('tfc:ceramics/unfired/vessel_glazed', 5),
    item('tfc:ceramics/unfired/vessel_glazed', 6),
    item('tfc:ceramics/unfired/vessel_glazed', 7),
    item('tfc:ceramics/unfired/vessel_glazed', 8),
    item('tfc:ceramics/unfired/vessel_glazed', 9),
    item('tfc:ceramics/unfired/vessel_glazed', 10),
    item('tfc:ceramics/unfired/vessel_glazed', 11),
    item('tfc:ceramics/unfired/vessel_glazed', 12),
    item('tfc:ceramics/unfired/vessel_glazed', 13),
    item('tfc:ceramics/unfired/vessel_glazed', 14),
    item('tfc:ceramics/unfired/vessel_glazed', 15)
  ]

  static final List smallClayFiredColoredVessels = [
    item('tfc:ceramics/fired/vessel_glazed', 0),
    item('tfc:ceramics/fired/vessel_glazed', 1),
    item('tfc:ceramics/fired/vessel_glazed', 2),
    item('tfc:ceramics/fired/vessel_glazed', 3),
    item('tfc:ceramics/fired/vessel_glazed', 4),
    item('tfc:ceramics/fired/vessel_glazed', 5),
    item('tfc:ceramics/fired/vessel_glazed', 6),
    item('tfc:ceramics/fired/vessel_glazed', 7),
    item('tfc:ceramics/fired/vessel_glazed', 8),
    item('tfc:ceramics/fired/vessel_glazed', 9),
    item('tfc:ceramics/fired/vessel_glazed', 10),
    item('tfc:ceramics/fired/vessel_glazed', 11),
    item('tfc:ceramics/fired/vessel_glazed', 12),
    item('tfc:ceramics/fired/vessel_glazed', 13),
    item('tfc:ceramics/fired/vessel_glazed', 14),
    item('tfc:ceramics/fired/vessel_glazed', 15)
  ]


  static final List clayMadeUnfiredItems = [
    item('tfc:ceramics/unfired/large_vessel'),
    item('tfc:ceramics/unfired/bowl'),
    item('tfc:ceramics/unfired/pot'),
    item('tfc:ceramics/unfired/jug'),
    item('tfc:ceramics/unfired/vessel'),
    item('tfc:ceramics/unfired/mold/scythe_blade'),
    item('tfc:ceramics/unfired/mold/knife_blade'),
    item('tfc:ceramics/unfired/mold/propick_head'),
    item('tfc:ceramics/unfired/mold/hammer_head'),
    item('tfc:ceramics/unfired/mold/javelin_head'),
    item('tfc:ceramics/unfired/mold/saw_blade'),
    item('tfc:ceramics/unfired/mold/mace_head'),
    item('tfc:ceramics/unfired/mold/sword_blade'),
    item('tfc:ceramics/unfired/mold/chisel_head'),
    item('tfc:ceramics/unfired/mold/hoe_head'),
    item('tfc:ceramics/unfired/mold/axe_head'),
    item('tfc:ceramics/unfired/mold/shovel_head'),
    item('tfc:ceramics/unfired/mold/pick_head'),
    item('tfc:ceramics/unfired/mold/ingot'),
    item('tfc:ceramics/unfired/mold/mallet_head'),
    item('tfctech:ceramics/unfired/glass_block'),
    item('tfctech:ceramics/unfired/glass_pane'),
    item('tfctech:ceramics/unfired/sleeve'),
    item('tfctech:ceramics/unfired/rackwheel_piece')
  ]

  static final List clayMadeFiredItems = [
    item('tfc:ceramics/fired/large_vessel'),
    item('tfc:ceramics/fired/bowl'),
    item('tfc:ceramics/fired/pot'),
    item('tfc:ceramics/fired/jug'),
    item('tfc:ceramics/fired/vessel'),
    item('tfc:ceramics/fired/mold/scythe_blade'),
    item('tfc:ceramics/fired/mold/knife_blade'),
    item('tfc:ceramics/fired/mold/propick_head'),
    item('tfc:ceramics/fired/mold/hammer_head'),
    item('tfc:ceramics/fired/mold/javelin_head'),
    item('tfc:ceramics/fired/mold/saw_blade'),
    item('tfc:ceramics/fired/mold/mace_head'),
    item('tfc:ceramics/fired/mold/sword_blade'),
    item('tfc:ceramics/fired/mold/chisel_head'),
    item('tfc:ceramics/fired/mold/hoe_head'),
    item('tfc:ceramics/fired/mold/axe_head'),
    item('tfc:ceramics/fired/mold/shovel_head'),
    item('tfc:ceramics/fired/mold/pick_head'),
    item('tfc:ceramics/fired/mold/ingot'),
    item('tfc:ceramics/fired/mold/mallet_head'),
    item('tfctech:ceramics/mold/glass_block'),
    item('tfctech:ceramics/mold/glass_pane'),
    item('tfctech:ceramics/mold/sleeve'),
    item('tfctech:ceramics/mold/rackwheel_piece')
  ]


}
