
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"pull_request_title": "New Crowdin updates"
"pull_request_labels": [
  "Pull request: Translation"
]
"commit_message": "[translation] New translations {fileName} ({languageName})"

"files" : [
  {
    "source" : "./groovy/assets/*/lang/en_us.lang",
    "translation" : "/%original_path%/%locale_with_underscore%.%file_extension%",
    "type": "properties",
    "update_option": "update_without_changes",
    "languages_mapping" : {
      "locale_with_underscore" : {
        "da-DK": "da_dk",
        "de-AT": "de_at",
        "de-CH": "de_ch",
        "de-US": "de_us",
        "es-AR": "es_ar",
        "es-CL": "es_cl",
        "es-EC": "es_ec",
        "es-ES": "es_es",
        "es-MX": "es_mx",
        "es-UY": "es_uy",
        "es-VE": "es_ve",
        "fr-CA": "fr_ca",
        "fr-FR": "fr_fr",
        "hr-HR": "hr_hr",
        "ko-KR": "ko_kr",
        "pl-PL": "pl_pl",
        "pt-BR": "pt_br",
        "pt-PT": "pt_pt",
        "ru-RU": "ru_ru",
        "en-CA": "en_ca",
        "uk-UA": "uk_ua",
        "en-US": "en_us"
      }
    }
  }
]