# LargeAdvancedApiaryRecipes

import crafttweaker.item.IItemStack;

print("Initializing 'LargeAdvancedApiaryRecipes'...");


// Получение пчелиной продукции 
// Лесная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesForest", UID0: "forestry.speciesForest"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Луговая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMeadows", UID0: "forestry.speciesMeadows"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Обычная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesCommon", UID0: "forestry.speciesCommon"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Развитая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesCultivated", UID0: "forestry.speciesCultivated"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 4000, 1200)
	.chancedOutput(<forestry:bee_combs>, 4000, 1200)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Знатная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesNoble", UID0: "forestry.speciesNoble"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:5>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:5>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Величавая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMajestic", UID0: "forestry.speciesMajestic"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:5>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:5>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Имперская
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesImperial", UID0: "forestry.speciesImperial"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 2000, 600)
	.chancedOutput(<forestry:bee_combs>, 2000, 600)
	.chancedOutput(<forestry:royal_jelly>, 1500, 450)
	.chancedOutput(<forestry:royal_jelly>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Прилежная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesDiligent", UID0: "forestry.speciesDiligent"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:3>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:3>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Неутомимая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesUnweary", UID0: "forestry.speciesUnweary"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:3>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:3>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Трудолюбивая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesIndustrious", UID0: "forestry.speciesIndustrious"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:3>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:3>, 2000, 600)
	.chancedOutput(<forestry:pollen>, 1500, 450)
	.chancedOutput(<forestry:pollen>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Стойкая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesSteadfast", UID0: "forestry.speciesSteadfast"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:1>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:1>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Доблесная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesValiant", UID0: "forestry.speciesValiant"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:1>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:1>, 3000, 900)
	.chancedOutput(<minecraft:sugar>, 1500, 450)
	.chancedOutput(<minecraft:sugar>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Героическая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesHeroic", UID0: "forestry.speciesHeroic"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:1>, 4000, 1200)
	.chancedOutput(<forestry:bee_combs:1>, 4000, 1200)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Зловещая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesSinister", UID0: "forestry.speciesSinister"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:2>, 4500, 1350)
	.chancedOutput(<forestry:bee_combs:2>, 4500, 1350)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Жестокая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesFiendish", UID0: "forestry.speciesFiendish"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:2>, 5500, 1650)
	.chancedOutput(<forestry:bee_combs:2>, 5500, 1650)
	.chancedOutput(<metaitem:dustAsh>, 1500, 450)
	.chancedOutput(<metaitem:dustAsh>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Одержимая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesDemonic", UID0: "forestry.speciesDemonic"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:2>, 4500, 1350)
	.chancedOutput(<forestry:bee_combs:2>, 4500, 1350)
	.chancedOutput(<minecraft:glowstone_dust>, 1500, 450)
	.chancedOutput(<minecraft:glowstone_dust>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Скромная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesModest", UID0: "forestry.speciesModest"}]}}))
        .notConsumable(<minecraft:cactus>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:7>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:7>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Бережливая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesFrugal", UID0: "forestry.speciesFrugal"}]}}))
        .notConsumable(<minecraft:cactus>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:7>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:7>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Суровая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesAustere", UID0: "forestry.speciesAustere"}]}}))
        .notConsumable(<minecraft:cactus>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:7>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:7>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:10>, 5000, 1500)
	.chancedOutput(<forestry:bee_combs:10>, 5000, 1500)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Тропическая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesTropical", UID0: "forestry.speciesTropical"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:6>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Редкая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesExotic", UID0: "forestry.speciesExotic"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:7>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:7>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Райская
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesEdenic", UID0: "forestry.speciesEdenic"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:3>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:3>, 2000, 600)
	.chancedOutput(<minecraft:experience_bottle>, 300, 90)
	.chancedOutput(<minecraft:experience_bottle>, 300, 90)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Драконья
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesEnded", UID0: "forestry.speciesEnded"}]}}))
        .notConsumable(<minecraft:chorus_plant>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:8>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:8>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Призрачная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesSpectral", UID0: "forestry.speciesSpectral"}]}}))
        .notConsumable(<minecraft:chorus_plant>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:8>, 5000, 1500)
	.chancedOutput(<forestry:bee_combs:8>, 5000, 1500)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Воображаемая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesPhantasmal", UID0: "forestry.speciesPhantasmal"}]}}))
        .notConsumable(<minecraft:chorus_plant>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:8>, 4000, 1200)
	.chancedOutput(<forestry:bee_combs:8>, 4000, 1200)
	.chancedOutput(<minecraft:chorus_fruit>, 500, 150)
	.chancedOutput(<minecraft:chorus_fruit>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Зимняя
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesWintry", UID0: "forestry.speciesWintry"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:4>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:4>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Ледяная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesIcy", UID0: "forestry.speciesIcy"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:4>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:4>, 2000, 600)
	.chancedOutput(<forestry:crafting_material:5>, 2000, 600)
	.chancedOutput(<forestry:crafting_material:5>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Ледниковая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesGlacial", UID0: "forestry.speciesGlacial"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:4>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:4>, 2000, 600)
	.chancedOutput(<forestry:crafting_material:5>, 4000, 1200)
	.chancedOutput(<forestry:crafting_material:5>, 4000, 1200)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Карательная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesVindictive", UID0: "forestry.speciesVindictive"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:9>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:9>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Мстительная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesVengeful", UID0: "forestry.speciesVengeful"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:9>, 4000, 1200)
	.chancedOutput(<forestry:bee_combs:9>, 4000, 1200)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Мстящая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesAvenging", UID0: "forestry.speciesAvenging"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:9>, 4000, 1200)
	.chancedOutput(<forestry:bee_combs:9>, 4000, 1200)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Сельская
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesRural", UID0: "forestry.speciesRural"}]}}))
        .notConsumable(<minecraft:wheat_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:14>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:14>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Прошлая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesFarmerly", UID0: "forestry.speciesFarmerly"}]}}))
        .notConsumable(<minecraft:wheat_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:14>, 2700, 810)
	.chancedOutput(<forestry:bee_combs:14>, 2700, 810)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Земельная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesAgrarian", UID0: "forestry.speciesAgrarian"}]}}))
        .notConsumable(<minecraft:wheat_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:14>, 3500, 1050)
	.chancedOutput(<forestry:bee_combs:14>, 3500, 1050)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Болотная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMarshy", UID0: "forestry.speciesMarshy"}]}}))
        .notConsumable(<minecraft:red_mushroom>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:15>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:15>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Топкая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMiry", UID0: "forestry.speciesMiry"}]}}))
        .notConsumable(<minecraft:red_mushroom>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:15>, 3600, 1080)
	.chancedOutput(<forestry:bee_combs:15>, 3600, 1080)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Болотистая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesBoggy", UID0: "forestry.speciesBoggy"}]}}))
        .notConsumable(<minecraft:red_mushroom>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:15>, 3900, 1170)
	.chancedOutput(<forestry:bee_combs:15>, 3900, 1170)
	.chancedOutput(<forestry:peat>, 800, 240)
	.chancedOutput(<forestry:peat>, 800, 240)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Монашья
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMonastic", UID0: "forestry.speciesMonastic"}]}}))
        .notConsumable(<minecraft:wheat_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:14>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:14>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:16>, 1000, 300)
	.chancedOutput(<forestry:bee_combs:16>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Укромная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesSecluded", UID0: "forestry.speciesSecluded"}]}}))
        .notConsumable(<minecraft:wheat_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:16>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:16>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Уединенная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesHermitic", UID0: "forestry.speciesHermitic"}]}}))
        .notConsumable(<minecraft:wheat_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:16>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:16>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Засушливый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.arid", UID0: "extrabees.species.arid"}]}}))
        .notConsumable(<minecraft:deadbush>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Бесплодный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.barren", UID0: "extrabees.species.barren"}]}}))
        .notConsumable(<minecraft:deadbush>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Заброшенный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.desolate", UID0: "extrabees.species.desolate"}]}}))
        .notConsumable(<minecraft:deadbush>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Разлагающийся
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.decomposing", UID0: "extrabees.species.decomposing"}]}}))
        .notConsumable(<minecraft:deadbush>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:79>, 800, 240)
	.chancedOutput(<extrabees:honey_comb:79>, 800, 240)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Ветхие
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.rotten", UID0: "extrabees.species.rotten"}]}}))
        .notConsumable(<minecraft:deadbush>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:1>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:1>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Скелетный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.bone", UID0: "extrabees.species.bone"}]}}))
        .notConsumable(<minecraft:deadbush>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:2>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:2>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Пресмыкающийся
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.creeper", UID0: "extrabees.species.creeper"}]}}))
        .notConsumable(<minecraft:deadbush>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:10>, 800, 240)
	.chancedOutput(<forestry:bee_combs:10>, 800, 240)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Скалистый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.rock", UID0: "extrabees.species.rock"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Терпимый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.stone", UID0: "extrabees.species.stone"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Крепкий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.granite", UID0: "extrabees.species.granite"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Устойчивый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.mineral", UID0: "extrabees.species.mineral"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:11>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Коррозийный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.copper", UID0: "extrabees.species.copper"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:17>, 600, 180)
	.chancedOutput(<extrabees:honey_comb:17>, 600, 180)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Потускневший
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.tin", UID0: "extrabees.species.tin"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:18>, 600, 180)
	.chancedOutput(<extrabees:honey_comb:18>, 600, 180)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Ржавый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.iron", UID0: "extrabees.species.iron"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:15>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:15>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Свинцовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lead", UID0: "extrabees.species.lead"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:37>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:37>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Гальванизированный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.zinc", UID0: "extrabees.species.zinc"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:40>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:40>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Неприступный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.titanium", UID0: "extrabees.species.titanium"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:41>, 200, 60)
	.chancedOutput(<extrabees:honey_comb:41>, 200, 60)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Неодолимый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.tungstate", UID0: "extrabees.species.tungstate"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:42>, 100, 30)
	.chancedOutput(<extrabees:honey_comb:42>, 100, 30)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Глянцевый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.nickel", UID0: "extrabees.species.nickel"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:73>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:73>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Сверкающий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.gold", UID0: "extrabees.species.gold"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:16>, 200, 60)
	.chancedOutput(<extrabees:honey_comb:16>, 200, 60)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Сияющий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.silver", UID0: "extrabees.species.silver"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:19>, 200, 60)
	.chancedOutput(<extrabees:honey_comb:19>, 200, 60)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Ценный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.platinum", UID0: "extrabees.species.platinum"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:45>, 100, 30)
	.chancedOutput(<extrabees:honey_comb:45>, 100, 30)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Лазуритовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lapis", UID0: "extrabees.species.lapis"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:46>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:46>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Пиритовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.pyrite", UID0: "extrabees.species.pyrite"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:48>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:48>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Киноварный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.cinnabar", UID0: "extrabees.species.cinnabar"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:50>, 400, 120)
	.chancedOutput(<extrabees:honey_comb:50>, 400, 120)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Сфалеритовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sphalerite", UID0: "extrabees.species.sphalerite"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:51>, 400, 120)
	.chancedOutput(<extrabees:honey_comb:51>, 400, 120)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Изумрудный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.emerald", UID0: "extrabees.species.emerald"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:52>, 400, 120)
	.chancedOutput(<extrabees:honey_comb:52>, 400, 120)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Рубиновый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.ruby", UID0: "extrabees.species.ruby"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:53>, 300, 90)
	.chancedOutput(<extrabees:honey_comb:53>, 300, 90)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Сапфировый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sapphire", UID0: "extrabees.species.sapphire"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:54>, 300, 90)
	.chancedOutput(<extrabees:honey_comb:54>, 300, 90)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Алмазный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.diamond", UID0: "extrabees.species.diamond"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:11>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:56>, 100, 30)
	.chancedOutput(<extrabees:honey_comb:56>, 100, 30)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Нестабильный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.unstable", UID0: "extrabees.species.unstable"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Ядерный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.nuclear", UID0: "extrabees.species.nuclear"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Радиоактивный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.radioactive", UID0: "extrabees.species.radioactive"}]}}))
        .notConsumable(<minecraft:stone>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:21>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:21>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Древний
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.ancient", UID0: "extrabees.species.ancient"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Первобытный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.primeval", UID0: "extrabees.species.primeval"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Доисторический
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.prehistoric", UID0: "extrabees.species.prehistoric"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Реликтовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.relic", UID0: "extrabees.species.relic"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:23>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Окаменелый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.coal", UID0: "extrabees.species.coal"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:23>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:23>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:4>, 800, 240)
	.chancedOutput(<extrabees:honey_comb:4>, 800, 240)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Мясляный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.oil", UID0: "extrabees.species.oil"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:23>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:23>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:3>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:3>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Дистиллированный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.distilled", UID0: "extrabees.species.distilled"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:23>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:23>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Изысканный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.fuel", UID0: "extrabees.species.fuel"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:3>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:3>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Смолистый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.creosote", UID0: "extrabees.species.creosote"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:4>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:4>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:25>, 700, 210)
	.chancedOutput(<extrabees:honey_comb:25>, 700, 210)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Водяной
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.water", UID0: "extrabees.species.water"}]}}))
        .notConsumable(<minecraft:waterlily>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Речной
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.river", UID0: "extrabees.species.river"}]}}))
        .notConsumable(<minecraft:waterlily>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:22>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:22>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Океанический
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.ocean", UID0: "extrabees.species.ocean"}]}}))
        .notConsumable(<minecraft:waterlily>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// В пятнах
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.ink", UID0: "extrabees.species.ink"}]}}))
        .notConsumable(<minecraft:waterlily>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:6>, 3000, 900)
	.chancedOutput(<minecraft:dye>, 1000, 300)
	.chancedOutput(<minecraft:dye>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Подрастающий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.growing", UID0: "extrabees.species.growing"}]}}))
        .notConsumable(<tfc:wood/leaves/palm>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Разводимый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.farm", UID0: "extrabees.species.farm"}]}}))
        .notConsumable(<minecraft:wheat_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:14>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:14>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:9>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:9>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Процветающий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.thriving", UID0: "extrabees.species.thriving"}]}}))
        .notConsumable(<tfc:wood/leaves/palm>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Промокший
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.boggy", UID0: "extrabees.species.boggy"}]}}))
        .notConsumable(<minecraft:red_mushroom>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:15>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:15>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Грибковый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.fungal", UID0: "extrabees.species.fungal"}]}}))
        .notConsumable(<minecraft:red_mushroom>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:15>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:15>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:24>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:24>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Мраморный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.marble", UID0: "extrabees.species.marble"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Римский
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.roman", UID0: "extrabees.species.roman"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Греческий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.greek", UID0: "extrabees.species.greek"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<tfc:food/olive>, 500, 150)
	.chancedOutput(<tfc:food/olive>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Классический
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.classical", UID0: "extrabees.species.classical"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:royal_jelly>, 2500, 750)
	.chancedOutput(<forestry:royal_jelly>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Озлобленный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.basalt", UID0: "extrabees.species.basalt"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:2>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:2>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Разъяренный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.tempered", UID0: "extrabees.species.tempered"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:2>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:2>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Вулканический
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.volcanic", UID0: "extrabees.species.volcanic"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:2>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:2>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:30>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:30>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Сердитый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.glowstone", UID0: "extrabees.species.glowstone"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:75>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:75>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Злонамеренный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.malicious", UID0: "extrabees.species.malicious"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Инфекционный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.infectious", UID0: "extrabees.species.infectious"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Вирулентный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.virulent", UID0: "extrabees.species.virulent"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:28>, 1200, 360)
	.chancedOutput(<extrabees:honey_comb:28>, 1200, 360)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Вязкий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.viscous", UID0: "extrabees.species.viscous"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Клейкий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.glutinous", UID0: "extrabees.species.glutinous"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Липкий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sticky", UID0: "extrabees.species.sticky"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:29>, 1200, 360)
	.chancedOutput(<extrabees:honey_comb:29>, 1200, 360)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Коррозийный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.corrosive", UID0: "extrabees.species.corrosive"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:6>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Едкий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.caustic", UID0: "extrabees.species.caustic"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:6>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:27>, 300, 90)
	.chancedOutput(<extrabees:honey_comb:27>, 300, 90)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Кислый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.acidic", UID0: "extrabees.species.acidic"}]}}))
        .notConsumable(<minecraft:vine>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:6>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:27>, 1600, 480)
	.chancedOutput(<extrabees:honey_comb:27>, 1600, 480)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Возбужденный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.excited", UID0: "extrabees.species.excited"}]}}))
        .notConsumable(<minecraft:redstone_ore>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:12>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:12>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Энергичный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.energetic", UID0: "extrabees.species.energetic"}]}}))
        .notConsumable(<minecraft:redstone_ore>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:12>, 1200, 360)
	.chancedOutput(<extrabees:honey_comb:12>, 1200, 360)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Экстатический
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.ecstatic", UID0: "extrabees.species.ecstatic"}]}}))
        .notConsumable(<minecraft:redstone_ore>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:12>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:12>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:14>, 800, 240)
	.chancedOutput(<extrabees:honey_comb:14>, 800, 240)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Холодный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.artic", UID0: "extrabees.species.artic"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:4>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:4>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Абсолютный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.freezing", UID0: "extrabees.species.freezing"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:4>, 2000, 600)
	.chancedOutput(<forestry:bee_combs:4>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:32>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:32>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Затененный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.shadow", UID0: "extrabees.species.shadow"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:36>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:36>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Затемненный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.darkened", UID0: "extrabees.species.darkened"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:36>, 1000, 300)
	.chancedOutput(<extrabees:honey_comb:36>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Глубинный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.abyss", UID0: "extrabees.species.abyss"}]}}))
        .notConsumable(<minecraft:nether_wart>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:36>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:36>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Подслащенный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.sweet", UID0: "extrabees.species.sweet"}]}}))
        .notConsumable(<minecraft:reeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 4000, 1200)
	.chancedOutput(<forestry:bee_combs>, 4000, 1200)
	.chancedOutput(<minecraft:sugar>, 1000, 300)
	.chancedOutput(<minecraft:sugar>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Фруктовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.fruit", UID0: "extrabees.species.fruit"}]}}))
        .notConsumable(<minecraft:reeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<minecraft:sugar>, 1500, 450)
	.chancedOutput(<minecraft:sugar>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:8>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:8>, 2000, 600)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Бордовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.red", UID0: "extrabees.species.red"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:57>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:57>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Шафран
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.yellow", UID0: "extrabees.species.yellow"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:58>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:58>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Прусский
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.blue", UID0: "extrabees.species.blue"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:59>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:59>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Природный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.green", UID0: "extrabees.species.green"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:60>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:60>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Эбеновый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.black", UID0: "extrabees.species.black"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:61>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:61>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Отбеленный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.white", UID0: "extrabees.species.white"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:62>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:62>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Сепия
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.brown", UID0: "extrabees.species.brown"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:63>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:63>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Янтарный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.orange", UID0: "extrabees.species.orange"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:64>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:64>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Бирюзовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.cyan", UID0: "extrabees.species.cyan"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:65>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:65>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Индиговый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.purple", UID0: "extrabees.species.purple"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:66>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:66>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Шиферный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.gray", UID0: "extrabees.species.gray"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:67>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:67>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Лазурный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lightblue", UID0: "extrabees.species.lightblue"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:68>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:68>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Лавандовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.pink", UID0: "extrabees.species.pink"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:69>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:69>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Лаймовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.limegreen", UID0: "extrabees.species.limegreen"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:70>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:70>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Фуксия
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.magenta", UID0: "extrabees.species.magenta"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:71>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:71>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Пепельный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.lightgray", UID0: "extrabees.species.lightgray"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<forestry:bee_combs>, 7500, 2250)
	.chancedOutput(<extrabees:honey_comb:72>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:72>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Праздничный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.celebratory", UID0: "extrabees.species.celebratory"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<minecraft:gunpowder>, 2500, 750)
	.chancedOutput(<minecraft:gunpowder>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Измученный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.jaded", UID0: "extrabees.species.jaded"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:bee_combs>, 3000, 900)
	.chancedOutput(<forestry:pollen>, 2000, 600)
	.chancedOutput(<forestry:pollen>, 2000, 600)
	.chancedOutput(<extrabees:honey_comb:66>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:66>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Опасный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.hazardous", UID0: "extrabees.species.hazardous"}]}}))
        .notConsumable(<minecraft:cactus>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:76>, 1200, 360)
	.chancedOutput(<extrabees:honey_comb:76>, 1200, 360)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Квантовый
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.quantum", UID0: "extrabees.species.quantum"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:16>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:16>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:81>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:81>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:82>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:82>, 1500, 450)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Аномальный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.unusual", UID0: "extrabees.species.unusual"}]}}))
        .notConsumable(<minecraft:chorus_plant>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:16>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:16>, 2500, 750)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Пространственный
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.spatial", UID0: "extrabees.species.spatial"}]}}))
        .notConsumable(<minecraft:chorus_plant>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:16>, 2500, 750)
	.chancedOutput(<forestry:bee_combs:16>, 2500, 750)
	.chancedOutput(<extrabees:honey_comb:81>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:81>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Заячья
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesLeporine", UID0: "forestry.speciesLeporine"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:6>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:6>, 3000, 900)
	.chancedOutput(<minecraft:egg>, 1000, 300)
	.chancedOutput(<minecraft:egg>, 1000, 300)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Цветущий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.blooming", UID0: "extrabees.species.blooming"}]}}))
        .notConsumable(<tfc:wood/sapling/palm>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
	.chancedOutput(<forestry:bee_combs>, 3500, 1050)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Веселая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesMerry", UID0: "forestry.speciesMerry"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:4>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:4>, 3000, 900)
	.chancedOutput(<forestry:crafting_material:5>, 2000, 600)
	.chancedOutput(<forestry:crafting_material:5>, 2000, 600)
	.chancedOutput(<minecraft:cookie>, 500, 150)
	.chancedOutput(<minecraft:cookie>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Пьяная
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesTipsy", UID0: "forestry.speciesTipsy"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:4>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:4>, 3000, 900)
	.chancedOutput(<forestry:crafting_material:5>, 2000, 600)
	.chancedOutput(<forestry:crafting_material:5>, 2000, 600)
	.chancedOutput(<minecraft:pumpkin_pie>, 100, 30)
	.chancedOutput(<minecraft:pumpkin_pie>, 100, 30)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Хитрая
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "forestry.speciesTricky", UID0: "forestry.speciesTricky"}]}}))
        .notConsumable(<minecraft:melon_seeds>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs>, 4000, 1200)
	.chancedOutput(<forestry:bee_combs>, 4000, 1200)
	.chancedOutput(<minecraft:cookie>, 1500, 450)
	.chancedOutput(<minecraft:cookie>, 1500, 450)
	.chancedOutput(<minecraft:skull:4>, 200, 60)
	.chancedOutput(<minecraft:skull>, 200, 60)
	.chancedOutput(<minecraft:skull:3>, 200, 60)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// С кофеином
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.coffee", UID0: "extrabees.species.coffee"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<forestry:bee_combs:14>, 3000, 900)
	.chancedOutput(<forestry:bee_combs:14>, 3000, 900)
	.chancedOutput(<extrabees:honey_comb:31>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:31>, 1500, 450)
	.chancedOutput(<minecraft:dye:3>, 500, 150)
	.chancedOutput(<minecraft:dye:3>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();
// Упругий
large_advanced_apiary.recipeBuilder()
        .notConsumable(<forestry:bee_queen_ge>.withTag({Genome: {Chromosomes: [{UID1: "extrabees.species.latex", UID0: "extrabees.species.latex"}]}}))
        .notConsumable(<minecraft:yellow_flower>)
        .fluidInputs([<liquid:seed.oil> * 1, <liquid:for.honey> * 1])
	.chancedOutput(<extrabees:honey_comb:29>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:29>, 1500, 450)
	.chancedOutput(<extrabees:honey_comb:26>, 500, 150)
	.chancedOutput(<extrabees:honey_comb:26>, 500, 150)
        .duration(28 * 20)
        .EUt(64)
        .buildAndRegister();


print("Initialized 'LargeAdvancedApiaryRecipes'");