// MODS_LOADED: tfctech
// ==== Удаление

// Удаление OreDicts у TFCTech винтов
ore('screwBismuth').remove(item('tfctech:metal/bismuth_screw'))
ore('screwBismuthBronze').remove(item('tfctech:metal/bismuth_bronze_screw'))
ore('screwBlackBronze').remove(item('tfctech:metal/black_bronze_screw'))
ore('screwBrass').remove(item('tfctech:metal/brass_screw'))
ore('screwBronze').remove(item('tfctech:metal/bronze_screw'))
ore('screwCopper').remove(item('tfctech:metal/copper_screw'))
ore('screwGold').remove(item('tfctech:metal/gold_screw'))
ore('screwLead').remove(item('tfctech:metal/lead_screw'))
ore('screwNickel').remove(item('tfctech:metal/nickel_screw'))
ore('screwSilver').remove(item('tfctech:metal/silver_screw'))
ore('screwRoseGold').remove(item('tfctech:metal/rose_gold_screw'))
ore('screwTin').remove(item('tfctech:metal/tin_screw'))
ore('screwZinc').remove(item('tfctech:metal/zinc_screw'))
ore('screwSterlingSilver').remove(item('tfctech:metal/sterling_silver_screw'))
ore('screwWroughtIron').remove(item('tfctech:metal/wrought_iron_screw'))
ore('screwPigIron').remove(item('tfctech:metal/pig_iron_screw'))
ore('screwSteel').remove(item('tfctech:metal/steel_screw'))
ore('screwPlatinum').remove(item('tfctech:metal/platinum_screw'))
ore('screwBlackSteel').remove(item('tfctech:metal/black_steel_screw'))
ore('screwBlueSteel').remove(item('tfctech:metal/blue_steel_screw'))
ore('screwRedSteel').remove(item('tfctech:metal/red_steel_screw'))

// Удаление OreDicts у TFCTech болтов
ore('boltBismuth').remove(item('tfctech:metal/bismuth_bolt'))
ore('boltBismuthBronze').remove(item('tfctech:metal/bismuth_bronze_bolt'))
ore('boltBlackBronze').remove(item('tfctech:metal/black_bronze_bolt'))
ore('boltBrass').remove(item('tfctech:metal/brass_bolt'))
ore('boltBronze').remove(item('tfctech:metal/bronze_bolt'))
ore('boltCopper').remove(item('tfctech:metal/copper_bolt'))
ore('boltGold').remove(item('tfctech:metal/gold_bolt'))
ore('boltLead').remove(item('tfctech:metal/lead_bolt'))
ore('boltNickel').remove(item('tfctech:metal/nickel_bolt'))
ore('boltSilver').remove(item('tfctech:metal/silver_bolt'))
ore('boltRoseGold').remove(item('tfctech:metal/rose_gold_bolt'))
ore('boltTin').remove(item('tfctech:metal/tin_bolt'))
ore('boltZinc').remove(item('tfctech:metal/zinc_bolt'))
ore('boltSterlingSilver').remove(item('tfctech:metal/sterling_silver_bolt'))
ore('boltWroughtIron').remove(item('tfctech:metal/wrought_iron_bolt'))
ore('boltPigIron').remove(item('tfctech:metal/pig_iron_bolt'))
ore('boltSteel').remove(item('tfctech:metal/steel_bolt'))
ore('boltPlatinum').remove(item('tfctech:metal/platinum_bolt'))
ore('boltBlackSteel').remove(item('tfctech:metal/black_steel_bolt'))
ore('boltBlueSteel').remove(item('tfctech:metal/blue_steel_bolt'))
ore('boltRedSteel').remove(item('tfctech:metal/red_steel_bolt'))

// Удаление OreDicts у TFCTech шестеренок
ore('gearBismuth').remove(item('tfctech:metal/bismuth_gear'))
ore('gearBismuthBronze').remove(item('tfctech:metal/bismuth_bronze_gear'))
ore('gearBlackBronze').remove(item('tfctech:metal/black_bronze_gear'))
ore('gearBrass').remove(item('tfctech:metal/brass_gear'))
ore('gearBronze').remove(item('tfctech:metal/bronze_gear'))
ore('gearCopper').remove(item('tfctech:metal/copper_gear'))
ore('gearGold').remove(item('tfctech:metal/gold_gear'))
ore('gearLead').remove(item('tfctech:metal/lead_gear'))
ore('gearNickel').remove(item('tfctech:metal/nickel_gear'))
ore('gearSilver').remove(item('tfctech:metal/silver_gear'))
ore('gearRoseGold').remove(item('tfctech:metal/rose_gold_gear'))
ore('gearTin').remove(item('tfctech:metal/tin_gear'))
ore('gearZinc').remove(item('tfctech:metal/zinc_gear'))
ore('gearSterlingSilver').remove(item('tfctech:metal/sterling_silver_gear'))
ore('gearWroughtIron').remove(item('tfctech:metal/wrought_iron_gear'))
ore('gearPigIron').remove(item('tfctech:metal/pig_iron_gear'))
ore('gearSteel').remove(item('tfctech:metal/steel_gear'))
ore('gearPlatinum').remove(item('tfctech:metal/platinum_gear'))
ore('gearBlackSteel').remove(item('tfctech:metal/black_steel_gear'))
ore('gearBlueSteel').remove(item('tfctech:metal/blue_steel_gear'))
ore('gearRedSteel').remove(item('tfctech:metal/red_steel_gear'))

// Удаление OreDicts у TFCTech длинных стержней
ore('stickLongBismuth').remove(item('tfctech:metal/bismuth_long_rod'))
ore('stickLongBismuthBronze').remove(item('tfctech:metal/bismuth_bronze_long_rod'))
ore('stickLongBlackBronze').remove(item('tfctech:metal/black_bronze_long_rod'))
ore('stickLongBrass').remove(item('tfctech:metal/brass_long_rod'))
ore('stickLongBronze').remove(item('tfctech:metal/bronze_long_rod'))
ore('stickLongCopper').remove(item('tfctech:metal/copper_long_rod'))
ore('stickLongGold').remove(item('tfctech:metal/gold_long_rod'))
ore('stickLongLead').remove(item('tfctech:metal/lead_long_rod'))
ore('stickLongNickel').remove(item('tfctech:metal/nickel_long_rod'))
ore('stickLongSilver').remove(item('tfctech:metal/silver_long_rod'))
ore('stickLongRoseGold').remove(item('tfctech:metal/rose_gold_long_rod'))
ore('stickLongTin').remove(item('tfctech:metal/tin_long_rod'))
ore('stickLongZinc').remove(item('tfctech:metal/zinc_long_rod'))
ore('stickLongSterlingSilver').remove(item('tfctech:metal/sterling_silver_long_rod'))
ore('stickLongWroughtIron').remove(item('tfctech:metal/wrought_iron_long_rod'))
ore('stickLongPigIron').remove(item('tfctech:metal/pig_iron_long_rod'))
ore('stickLongSteel').remove(item('tfctech:metal/steel_long_rod'))
ore('stickLongPlatinum').remove(item('tfctech:metal/platinum_long_rod'))
ore('stickLongBlackSteel').remove(item('tfctech:metal/black_steel_long_rod'))
ore('stickLongBlueSteel').remove(item('tfctech:metal/blue_steel_long_rod'))
ore('stickLongRedSteel').remove(item('tfctech:metal/red_steel_long_rod'))

// Удаление OreDicts у TFCTech стержней
ore('stickBismuth').remove(item('tfctech:metal/bismuth_rod'))
ore('stickBismuthBronze').remove(item('tfctech:metal/bismuth_bronze_rod'))
ore('stickBlackBronze').remove(item('tfctech:metal/black_bronze_rod'))
ore('stickBrass').remove(item('tfctech:metal/brass_rod'))
ore('stickBronze').remove(item('tfctech:metal/bronze_rod'))
ore('stickCopper').remove(item('tfctech:metal/copper_rod'))
ore('stickGold').remove(item('tfctech:metal/gold_rod'))
ore('stickLead').remove(item('tfctech:metal/lead_rod'))
ore('stickNickel').remove(item('tfctech:metal/nickel_rod'))
ore('stickSilver').remove(item('tfctech:metal/silver_rod'))
ore('stickRoseGold').remove(item('tfctech:metal/rose_gold_rod'))
ore('stickTin').remove(item('tfctech:metal/tin_rod'))
ore('stickZinc').remove(item('tfctech:metal/zinc_rod'))
ore('stickSterlingSilver').remove(item('tfctech:metal/sterling_silver_rod'))
ore('stickWroughtIron').remove(item('tfctech:metal/wrought_iron_rod'))
ore('stickPigIron').remove(item('tfctech:metal/pig_iron_rod'))
ore('stickSteel').remove(item('tfctech:metal/steel_rod'))
ore('stickPlatinum').remove(item('tfctech:metal/platinum_rod'))
ore('stickBlackSteel').remove(item('tfctech:metal/black_steel_rod'))
ore('stickBlueSteel').remove(item('tfctech:metal/blue_steel_rod'))
ore('stickRedSteel').remove(item('tfctech:metal/red_steel_rod'))
