#priority 3
# RecipeTable

import crafttweaker.item.IItemStack;
import crafttweaker.liquid.ILiquidStack;

print("Initializing 'RecipeTable'...");


// Рецепты получения пылек с помощью молота из иммерсива
global GTDustImmersiv as string[] = [
	"immersiveengineering:hammercrushing_kyanite",
	"immersiveengineering:hammercrushing_electrotine",
	"immersiveengineering:hammercrushing_molybdenum",
	"immersiveengineering:hammercrushing_garnierite",
	"immersiveengineering:hammercrushing_mica",
	"immersiveengineering:hammercrushing_bentonite",
	"immersiveengineering:hammercrushing_cobaltite",
	"immersiveengineering:hammercrushing_asbestos",
	"immersiveengineering:hammercrushing_chalcopyrite",
	"immersiveengineering:hammercrushing_smallwroughtiron",
	"immersiveengineering:hammercrushing_tungstate",
	"immersiveengineering:hammercrushing_smallsilver",
	"immersiveengineering:hammercrushing_magnesite",
	"immersiveengineering:hammercrushing_bauxite",
	"immersiveengineering:hammercrushing_yellowlimonite",
	"immersiveengineering:hammercrushing_chalcocite",
	"immersiveengineering:hammercrushing_bismuth",
	"immersiveengineering:hammercrushing_platinum",
	"immersiveengineering:hammercrushing_naquadah",
	"immersiveengineering:hammercrushing_ilmenite",
	"immersiveengineering:hammercrushing_chromite",
	"immersiveengineering:hammercrushing_lead",
	"immersiveengineering:hammercrushing_smallplatinum",
	"immersiveengineering:hammercrushing_cassiterite",
	"immersiveengineering:hammercrushing_trona",
	"immersiveengineering:hammercrushing_thorium",
	"immersiveengineering:hammercrushing_oilsands",
	"immersiveengineering:hammercrushing_smallnickel",
	"immersiveengineering:hammercrushing_tricalciumphosphate",
	"immersiveengineering:hammercrushing_fullersearth",
	"immersiveengineering:hammercrushing_bandediron",
	"immersiveengineering:hammercrushing_scheelite",
	"immersiveengineering:hammercrushing_calcite",
	"immersiveengineering:hammercrushing_lepidolite",
	"immersiveengineering:hammercrushing_plutonium",
	"immersiveengineering:hammercrushing_molybdenite",
	"immersiveengineering:hammercrushing_galena",
	"immersiveengineering:hammercrushing_cobalt",
	"immersiveengineering:hammercrushing_aluminium",
	"immersiveengineering:hammercrushing_smalllead",
	"immersiveengineering:hammercrushing_soapstone",
	"immersiveengineering:hammercrushing_smallbismuth",
	"immersiveengineering:hammercrushing_graniticmineralsand",
	"immersiveengineering:hammercrushing_wulfenite",
	"immersiveengineering:hammercrushing_pollucite",
	"immersiveengineering:hammercrushing_palladium",
	"immersiveengineering:hammercrushing_bastnasite",
	"immersiveengineering:hammercrushing_pyrochlore",
	"immersiveengineering:hammercrushing_beryllium",
	"immersiveengineering:hammercrushing_uranium",
	"immersiveengineering:hammercrushing_barite",
	"immersiveengineering:hammercrushing_spodumene",
	"immersiveengineering:hammercrushing_cooperite",
	"immersiveengineering:hammercrushing_smallcopper",
	"immersiveengineering:hammercrushing_vanadiummagnetite",
	"immersiveengineering:hammercrushing_garnetsand",
	"immersiveengineering:hammercrushing_glowstone",
	"immersiveengineering:hammercrushing_pyrolusite",
	"immersiveengineering:hammercrushing_silver",
	"immersiveengineering:hammercrushing_cassiteritesand",
	"immersiveengineering:hammercrushing_brownlimonite",
	"immersiveengineering:hammercrushing_lithium",
	"immersiveengineering:hammercrushing_smallzinc",
	"immersiveengineering:hammercrushing_gold",
	"immersiveengineering:hammercrushing_tetrahedrite",
	"immersiveengineering:hammercrushing_nickel",
	"immersiveengineering:hammercrushing_talc",
	"immersiveengineering:hammercrushing_pentlandite",
	"immersiveengineering:hammercrushing_iron",
	"immersiveengineering:hammercrushing_stibnite",
	"immersiveengineering:hammercrushing_magnetite",
	"immersiveengineering:hammercrushing_neodymium",
	"immersiveengineering:hammercrushing_sphalerite",
	"immersiveengineering:hammercrushing_pyrite",
	"immersiveengineering:hammercrushing_uraninite",
	"immersiveengineering:hammercrushing_smalltin",
	"immersiveengineering:hammercrushing_bornite",
	"immersiveengineering:hammercrushing_copper",
	"immersiveengineering:hammercrushing_tin",
	"immersiveengineering:hammercrushing_glauconitesand",
	"immersiveengineering:hammercrushing_smallgold",
	"immersiveengineering:hammercrushing_zeolite",
	"immersiveengineering:hammercrushing_alunite",
	"immersiveengineering:hammercrushing_basalticmineralsand",
	"immersiveengineering:hammercrushing_diatomite",
	"immersiveengineering:hammercrushing_powellite",
	"immersiveengineering:hammercrushing_tantalite"
];

// Удаление рецептов получения пылек с помощью молота из иммерсива
for item in GTDustImmersiv{
    recipes.removeByRecipeName(item);
}

// Рецепты получения грязных пылек с помощью молота из грега
global GTDustGregImpure as string[] = [
	"gregtech:crushed_ore_to_dust_molybdenum",
	"gregtech:crushed_ore_to_dust_glowstone",
	"gregtech:crushed_ore_to_dust_alunite",
	"gregtech:crushed_ore_to_dust_apatite",
	"gregtech:crushed_ore_to_dust_nickel",
	"gregtech:crushed_ore_to_dust_sodalite",
	"gregtech:crushed_ore_to_dust_beryllium",
	"gregtech:crushed_ore_to_dust_tricalcium_phosphate",
	"gregtech:crushed_ore_to_dust_garnierite",
	"gregtech:crushed_ore_to_dust_garnet_red",
	"gregtech:crushed_ore_to_dust_chromite",
	"gregtech:crushed_ore_to_dust_barite",
	"gregtech:crushed_ore_to_dust_realgar",
	"gregtech:crushed_ore_to_dust_granitic_mineral_sand",
	"gregtech:crushed_ore_to_dust_yellow_limonite",
	"gregtech:crushed_ore_to_dust_bastnasite",
	"gregtech:crushed_ore_to_dust_pyrochlore",
	"gregtech:crushed_ore_to_dust_iron",
	"gregtech:crushed_ore_to_dust_talc",
	"gregtech:crushed_ore_to_dust_powellite",
	"gregtech:crushed_ore_to_dust_cinnabar",
	"gregtech:crushed_ore_to_dust_molybdenite",
	"gregtech:crushed_ore_to_dust_scheelite",
	"gregtech:crushed_ore_to_dust_naquadah",
	"gregtech:crushed_ore_to_dust_cassiterite_sand",
	"gregtech:crushed_ore_to_dust_chalcopyrite",
	"gregtech:crushed_ore_to_dust_tantalite",
	"gregtech:crushed_ore_to_dust_blue_topaz",
	"gregtech:crushed_ore_to_dust_uraninite",
	"gregtech:crushed_ore_to_dust_garnet_sand",
	"gregtech:crushed_ore_to_dust_tin",
	"gregtech:crushed_ore_to_dust_sapphire",
	"gregtech:crushed_ore_to_dust_bornite",
	"gregtech:crushed_ore_to_dust_asbestos",
	"gregtech:crushed_ore_to_dust_spodumene",
	"gregtech:crushed_ore_to_dust_magnetite",
	"gregtech:crushed_ore_to_dust_pyrite",
	"gregtech:crushed_ore_to_dust_sulfur",
	"gregtech:crushed_ore_to_dust_electrotine",
	"gregtech:crushed_ore_to_dust_nether_quartz",
	"gregtech:crushed_ore_to_dust_emerald",
	"gregtech:crushed_ore_to_dust_stibnite",
	"gregtech:crushed_ore_to_dust_grossular",
	"gregtech:crushed_ore_to_dust_almandine",
	"gregtech:crushed_ore_to_dust_brown_limonite",
	"gregtech:crushed_ore_to_dust_copper",
	"gregtech:crushed_ore_to_dust_magnesite",
	"gregtech:crushed_ore_to_dust_zeolite",
	"gregtech:crushed_ore_to_dust_tetrahedrite",
	"gregtech:crushed_ore_to_dust_diamond",
	"gregtech:crushed_ore_to_dust_lepidolite",
	"gregtech:crushed_ore_to_dust_cooperite",
	"gregtech:crushed_ore_to_dust_quartzite",
	"gregtech:crushed_ore_to_dust_topaz",
	"gregtech:crushed_ore_to_dust_gold",
	"gregtech:crushed_ore_to_dust_salt",
	"gregtech:crushed_ore_to_dust_bentonite",
	"gregtech:crushed_ore_to_dust_glauconite_sand",
	"gregtech:crushed_ore_to_dust_cobaltite",
	"gregtech:crushed_ore_to_dust_tungstate",
	"gregtech:crushed_ore_to_dust_diatomite",
	"gregtech:crushed_ore_to_dust_trona",
	"gregtech:crushed_ore_to_dust_thorium",
	"gregtech:crushed_ore_to_dust_green_sapphire",
	"gregtech:crushed_ore_to_dust_basaltic_mineral_sand",
	"gregtech:crushed_ore_to_dust_malachite",
	"gregtech:crushed_ore_to_dust_fullers_earth",
	"gregtech:crushed_ore_to_dust_aluminium",
	"gregtech:crushed_ore_to_dust_pentlandite",
	"gregtech:crushed_ore_to_dust_wulfenite",
	"gregtech:crushed_ore_to_dust_monazite",
	"gregtech:crushed_ore_to_dust_ruby",
	"gregtech:crushed_ore_to_dust_rock_salt",
	"gregtech:crushed_ore_to_dust_amethyst",
	"gregtech:crushed_ore_to_dust_garnet_yellow",
	"gregtech:crushed_ore_to_dust_palladium",
	"gregtech:crushed_ore_to_dust_pyrolusite",
	"gregtech:crushed_ore_to_dust_plutonium",
	"gregtech:crushed_ore_to_dust_redstone",
	"gregtech:crushed_ore_to_dust_bauxite",
	"gregtech:crushed_ore_to_dust_coal",
	"gregtech:crushed_ore_to_dust_pollucite",
	"gregtech:crushed_ore_to_dust_platinum",
	"gregtech:crushed_ore_to_dust_vanadium_magnetite",
	"gregtech:crushed_ore_to_dust_silver",
	"gregtech:crushed_ore_to_dust_sphalerite",
	"gregtech:crushed_ore_to_dust_spessartine",
	"gregtech:crushed_ore_to_dust_saltpeter",
	"gregtech:crushed_ore_to_dust_certus_quartz",
	"gregtech:crushed_ore_to_dust_cobalt",
	"gregtech:crushed_ore_to_dust_neodymium",
	"gregtech:crushed_ore_to_dust_lazurite",
	"gregtech:crushed_ore_to_dust_cassiterite",
	"gregtech:crushed_ore_to_dust_ilmenite",
	"gregtech:crushed_ore_to_dust_kyanite",
	"gregtech:crushed_ore_to_dust_lithium",
	"gregtech:crushed_ore_to_dust_lapis",
	"gregtech:crushed_ore_to_dust_soapstone",
	"gregtech:crushed_ore_to_dust_banded_iron",
	"gregtech:crushed_ore_to_dust_opal",
	"gregtech:crushed_ore_to_dust_mica",
	"gregtech:crushed_ore_to_dust_pyrope",
	"gregtech:crushed_ore_to_dust_oilsands",
	"gregtech:crushed_ore_to_dust_galena",
	"gregtech:crushed_ore_to_dust_bismuth",
	"gregtech:crushed_ore_to_dust_graphite",
	"gregtech:crushed_ore_to_dust_gypsum",
	"gregtech:crushed_ore_to_dust_lead",
	"gregtech:crushed_ore_to_dust_pitchblende",
	"gregtech:crushed_ore_to_dust_calcite",
	"gregtech:crushed_ore_to_dust_chalcocite",
	"gregtech:crushed_ore_to_dust_olivine"
];

// Удаление рецептов получения грязных пылек с помощью молота из грега
for item in GTDustGregImpure{
    recipes.removeByRecipeName(item);
}

// Рецепты получения очищенных кучек пыли с помощью молота из грега
global GTDustGregPure as string[] = [
	"gregtech:purified_ore_to_dust_spodumene",
	"gregtech:purified_ore_to_dust_bismuth",
	"gregtech:purified_ore_to_dust_lepidolite",
	"gregtech:purified_ore_to_dust_beryllium",
	"gregtech:purified_ore_to_dust_cassiterite_sand",
	"gregtech:purified_ore_to_dust_zeolite",
	"gregtech:purified_ore_to_dust_tantalite",
	"gregtech:purified_ore_to_dust_yellow_limonite",
	"gregtech:purified_ore_to_dust_topaz",
	"gregtech:purified_ore_to_dust_banded_iron",
	"gregtech:purified_ore_to_dust_opal",
	"gregtech:purified_ore_to_dust_barite",
	"gregtech:purified_ore_to_dust_cobalt",
	"gregtech:purified_ore_to_dust_nickel",
	"gregtech:purified_ore_to_dust_powellite",
	"gregtech:purified_ore_to_dust_oilsands",
	"gregtech:purified_ore_to_dust_pentlandite",
	"gregtech:purified_ore_to_dust_realgar",
	"gregtech:purified_ore_to_dust_silver",
	"gregtech:purified_ore_to_dust_vanadium_magnetite",
	"gregtech:purified_ore_to_dust_green_sapphire",
	"gregtech:purified_ore_to_dust_apatite",
	"gregtech:purified_ore_to_dust_tetrahedrite",
	"gregtech:purified_ore_to_dust_cassiterite",
	"gregtech:purified_ore_to_dust_coal",
	"gregtech:purified_ore_to_dust_glowstone",
	"gregtech:purified_ore_to_dust_sphalerite",
	"gregtech:purified_ore_to_dust_calcite",
	"gregtech:purified_ore_to_dust_scheelite",
	"gregtech:purified_ore_to_dust_chalcocite",
	"gregtech:purified_ore_to_dust_molybdenum",
	"gregtech:purified_ore_to_dust_magnetite",
	"gregtech:purified_ore_to_dust_uraninite",
	"gregtech:purified_ore_to_dust_garnierite",
	"gregtech:purified_ore_to_dust_chromite",
	"gregtech:purified_ore_to_dust_blue_topaz",
	"gregtech:purified_ore_to_dust_neodymium",
	"gregtech:purified_ore_to_dust_sodalite",
	"gregtech:purified_ore_to_dust_ruby",
	"gregtech:purified_ore_to_dust_saltpeter",
	"gregtech:purified_ore_to_dust_fullers_earth",
	"gregtech:purified_ore_to_dust_graphite",
	"gregtech:purified_ore_to_dust_bastnasite",
	"gregtech:purified_ore_to_dust_spessartine",
	"gregtech:purified_ore_to_dust_pyrope",
	"gregtech:purified_ore_to_dust_pyrochlore",
	"gregtech:purified_ore_to_dust_alunite",
	"gregtech:purified_ore_to_dust_pollucite",
	"gregtech:purified_ore_to_dust_naquadah",
	"gregtech:purified_ore_to_dust_aluminium",
	"gregtech:purified_ore_to_dust_soapstone",
	"gregtech:purified_ore_to_dust_pyrolusite",
	"gregtech:purified_ore_to_dust_glauconite_sand",
	"gregtech:purified_ore_to_dust_lead",
	"gregtech:purified_ore_to_dust_pitchblende",
	"gregtech:purified_ore_to_dust_asbestos",
	"gregtech:purified_ore_to_dust_mica",
	"gregtech:purified_ore_to_dust_bornite",
	"gregtech:purified_ore_to_dust_brown_limonite",
	"gregtech:purified_ore_to_dust_nether_quartz",
	"gregtech:purified_ore_to_dust_emerald",
	"gregtech:purified_ore_to_dust_tungstate",
	"gregtech:purified_ore_to_dust_platinum",
	"gregtech:purified_ore_to_dust_lithium",
	"gregtech:purified_ore_to_dust_stibnite",
	"gregtech:purified_ore_to_dust_ilmenite",
	"gregtech:purified_ore_to_dust_trona",
	"gregtech:purified_ore_to_dust_malachite",
	"gregtech:purified_ore_to_dust_plutonium",
	"gregtech:purified_ore_to_dust_sulfur",
	"gregtech:purified_ore_to_dust_thorium",
	"gregtech:purified_ore_to_dust_certus_quartz",
	"gregtech:purified_ore_to_dust_olivine",
	"gregtech:purified_ore_to_dust_galena",
	"gregtech:purified_ore_to_dust_lazurite",
	"gregtech:purified_ore_to_dust_molybdenite",
	"gregtech:purified_ore_to_dust_rock_salt",
	"gregtech:purified_ore_to_dust_wulfenite",
	"gregtech:purified_ore_to_dust_lapis",
	"gregtech:purified_ore_to_dust_diatomite",
	"gregtech:purified_ore_to_dust_palladium",
	"gregtech:purified_ore_to_dust_gypsum",
	"gregtech:purified_ore_to_dust_cobaltite",
	"gregtech:purified_ore_to_dust_garnet_sand",
	"gregtech:purified_ore_to_dust_copper",
	"gregtech:purified_ore_to_dust_iron",
	"gregtech:purified_ore_to_dust_talc",
	"gregtech:purified_ore_to_dust_granitic_mineral_sand",
	"gregtech:purified_ore_to_dust_monazite",
	"gregtech:purified_ore_to_dust_cinnabar",
	"gregtech:purified_ore_to_dust_diamond",
	"gregtech:purified_ore_to_dust_electrotine",
	"gregtech:purified_ore_to_dust_grossular",
	"gregtech:purified_ore_to_dust_almandine",
	"gregtech:purified_ore_to_dust_kyanite",
	"gregtech:purified_ore_to_dust_garnet_red",
	"gregtech:purified_ore_to_dust_garnet_yellow",
	"gregtech:purified_ore_to_dust_sapphire",
	"gregtech:purified_ore_to_dust_amethyst",
	"gregtech:purified_ore_to_dust_redstone",
	"gregtech:purified_ore_to_dust_magnesite",
	"gregtech:purified_ore_to_dust_chalcopyrite",
	"gregtech:purified_ore_to_dust_basaltic_mineral_sand",
	"gregtech:purified_ore_to_dust_tin",
	"gregtech:purified_ore_to_dust_quartzite",
	"gregtech:purified_ore_to_dust_gold",
	"gregtech:purified_ore_to_dust_salt",
	"gregtech:purified_ore_to_dust_tricalcium_phosphate",
	"gregtech:purified_ore_to_dust_pyrite",
	"gregtech:purified_ore_to_dust_bauxite",
	"gregtech:purified_ore_to_dust_bentonite",
	"gregtech:purified_ore_to_dust_cooperite"
];

// Удаление рецептов получения очищенных кучек пыли с помощью молота из грега
for item in GTDustGregPure{
    recipes.removeByRecipeName(item);
}

// Рецепты крафта молота из грега из слитков в верстаке
global GTHammerCraft as string[] = [
	"gregtech:hammer_neutronium",
	"gregtech:hammer_steel",
	"gregtech:hammer_opal",
	"gregtech:hammer_garnet_yellow",
	"gregtech:hammer_tritanium",
	"gregtech:hammer_amethyst",
	"gregtech:hammer_aluminium",
	"gregtech:hammer_blue_topaz",
	"gregtech:hammer_palladium",
	"gregtech:hammer_iron",
	"gregtech:hammer_green_sapphire",
	"gregtech:hammer_uranium",
	"gregtech:hammer_black_steel",
	"gregtech:hammer_damascus_steel",
	"gregtech:hammer_naquadah_alloy",
	"gregtech:hammer_bismuth_bronze",
	"gregtech:hammer_rhodium_plated_palladium",
	"gregtech:hammer_emerald",
	"gregtech:hammer_cobalt",
	"gregtech:hammer_vanadium_steel",
	"gregtech:hammer_diamond",
	"gregtech:hammer_duranium",
	"gregtech:hammer_invar",
	"gregtech:hammer_titanium",
	"gregtech:hammer_black_bronze",
	"gregtech:hammer_bronze",
	"gregtech:hammer_blue_steel",
	"gregtech:hammer_olivine",
	"gregtech:hammer_hsss",
	"gregtech:hammer_uranium_235",
	"gregtech:hammer_cobalt_brass",
	"gregtech:hammer_hsse",
	"gregtech:hammer_hssg",
	"gregtech:hammer_tungsten_steel",
	"gregtech:hammer_rose_gold",
	"gregtech:hammer_sapphire",
	"gregtech:hammer_osmium",
	"gregtech:hammer_naquadah",
	"gregtech:hammer_chrome",
	"gregtech:hammer_wrought_iron",
	"gregtech:hammer_tungsten_carbide",
	"gregtech:hammer_garnet_red",
	"gregtech:hammer_neodymium",
	"gregtech:hammer_molybdenum",
	"gregtech:hammer_ruby",
	"gregtech:hammer_manganese",
	"gregtech:hammer_ultimet",
	"gregtech:hammer_iridium",
	"gregtech:hammer_red_steel",
	"gregtech:hammer_osmiridium",
	"gregtech:hammer_stainless_steel",
	"gregtech:hammer_magnalium",
	"gregtech:hammer_naquadah_enriched",
	"gregtech:hammer_tungsten",
	"gregtech:hammer_topaz",
	"gregtech:hammer_brass",
	"gregtech:hammer_sterling_silver",
	"gregtech:hammer_thorium"
];

// Удаление рецептов крафта молота из грега из слитков в верстаке
for item in GTHammerCraft{
    recipes.removeByRecipeName(item);
}

// Рецепты крафта шахтерского молота из грега из пластин в верстаке
global GTMiningHammerCraft as string[] = [
	"gregtech:mining_hammer_diamond",
	"gregtech:mining_hammer_iron",
	"gregtech:mining_hammer_iridium",
	"gregtech:mining_hammer_amethyst",
	"gregtech:mining_hammer_thorium",
	"gregtech:mining_hammer_tungsten_carbide",
	"gregtech:mining_hammer_tritanium",
	"gregtech:mining_hammer_chrome",
	"gregtech:mining_hammer_invar",
	"gregtech:mining_hammer_tungsten",
	"gregtech:mining_hammer_molybdenum",
	"gregtech:mining_hammer_green_sapphire",
	"gregtech:mining_hammer_neodymium",
	"gregtech:mining_hammer_palladium",
	"gregtech:mining_hammer_garnet_red",
	"gregtech:mining_hammer_emerald",
	"gregtech:mining_hammer_osmiridium",
	"gregtech:mining_hammer_aluminium",
	"gregtech:mining_hammer_wrought_iron",
	"gregtech:mining_hammer_olivine",
	"gregtech:mining_hammer_opal",
	"gregtech:mining_hammer_vanadium_steel",
	"gregtech:mining_hammer_rose_gold",
	"gregtech:mining_hammer_garnet_yellow",
	"gregtech:mining_hammer_uranium_235",
	"gregtech:mining_hammer_bismuth_bronze",
	"gregtech:mining_hammer_rhodium_plated_palladium",
	"gregtech:mining_hammer_manganese",
	"gregtech:mining_hammer_naquadah_alloy",
	"gregtech:mining_hammer_neutronium",
	"gregtech:mining_hammer_damascus_steel",
	"gregtech:mining_hammer_black_bronze",
	"gregtech:mining_hammer_ruby",
	"gregtech:mining_hammer_uranium",
	"gregtech:mining_hammer_duranium",
	"gregtech:mining_hammer_black_steel",
	"gregtech:mining_hammer_tungsten_steel",
	"gregtech:mining_hammer_sterling_silver",
	"gregtech:mining_hammer_bronze",
	"gregtech:mining_hammer_naquadah",
	"gregtech:mining_hammer_steel",
	"gregtech:mining_hammer_sapphire",
	"gregtech:mining_hammer_red_steel",
	"gregtech:mining_hammer_magnalium",
	"gregtech:mining_hammer_ultimet",
	"gregtech:mining_hammer_brass",
	"gregtech:mining_hammer_topaz",
	"gregtech:mining_hammer_blue_topaz",
	"gregtech:mining_hammer_cobalt_brass",
	"gregtech:mining_hammer_hsse",
	"gregtech:mining_hammer_hssg",
	"gregtech:mining_hammer_hsss",
	"gregtech:mining_hammer_titanium",
	"gregtech:mining_hammer_blue_steel",
	"gregtech:mining_hammer_cobalt",
	"gregtech:mining_hammer_naquadah_enriched",
	"gregtech:mining_hammer_osmium",
	"gregtech:mining_hammer_stainless_steel"
];

// Удаление рецептов крафта шахтерского молота из грега из пластин в верстаке
for item in GTMiningHammerCraft{
    recipes.removeByRecipeName(item);
}

// Рецепты крафта напильника из грега из пластин в верстаке
global GTToolFileCraft as string[] = [
	"gregtech:file_naquadah",
	"gregtech:file_cobalt",
	"gregtech:file_titanium",
	"gregtech:file_osmiridium",
	"gregtech:file_tungsten_carbide",
	"gregtech:file_rose_gold",
	"gregtech:file_invar",
	"gregtech:file_damascus_steel",
	"gregtech:file_neutronium",
	"gregtech:file_tungsten_steel",
	"gregtech:file_black_bronze",
	"gregtech:file_palladium",
	"gregtech:file_duranium",
	"gregtech:file_cobalt_brass",
	"gregtech:file_uranium",
	"gregtech:file_bismuth_bronze",
	"gregtech:file_naquadah_alloy",
	"gregtech:file_hssg",
	"gregtech:file_hsse",
	"gregtech:file_hsss",
	"gregtech:file_steel",
	"gregtech:file_naquadah_enriched",
	"gregtech:file_molybdenum",
	"gregtech:file_iridium",
	"gregtech:file_black_steel",
	"gregtech:file_tritanium",
	"gregtech:file_wrought_iron",
	"gregtech:file_brass",
	"gregtech:file_chrome",
	"gregtech:file_vanadium_steel",
	"gregtech:file_aluminium",
	"gregtech:file_osmium",
	"gregtech:file_neodymium",
	"gregtech:file_iron",
	"gregtech:file_rhodium_plated_palladium",
	"gregtech:file_ultimet",
	"gregtech:file_manganese",
	"gregtech:file_red_steel",
	"gregtech:file_magnalium",
	"gregtech:file_stainless_steel",
	"gregtech:file_tungsten",
	"gregtech:file_blue_steel",
	"gregtech:file_sterling_silver",
	"gregtech:file_bronze",
	"gregtech:file_uranium_235",
	"gregtech:file_thorium"
];

// Удаление рецептов крафта напильника из грега из пластин в верстаке
for item in GTToolFileCraft{
    recipes.removeByRecipeName(item);
}

// Рецепты крафта некоторых предметов из Форестри и Бинни
global GTForestry as string[] = [
	"extrabees:diamond_shard_gem",
	"extrabees:emerald_shard_gem",
	"extrabees:sapphire_shard_gem",
	"extrabees:ruby_shard_gem"
];

// Удаление рецептов крафта некоторых предметов из Форестри и Бинни
for item in GTForestry{
    recipes.removeByRecipeName(item);
}


// Рецепты крафта проводов из грега из пластин в верстаке
global GTWireSingle as string[] = [
	"gregtech:cupronickel_wire_single",
	"gregtech:annealed_copper_wire_single",
	"gregtech:tungsten_wire_single",
	"gregtech:aluminium_wire_single",
	"gregtech:indium_tin_barium_titanium_cuprate_wire_single",
	"gregtech:trinium_wire_single",
	"gregtech:naquadah_alloy_wire_single",
	"gregtech:naquadah_wire_single",
	"gregtech:hssg_wire_single",
	"gregtech:cobalt_wire_single",
	"gregtech:nichrome_wire_single",
	"gregtech:enriched_naquadah_trinium_europium_duranide_wire_single",
	"gregtech:silver_wire_single",
	"gregtech:platinum_wire_single",
	"gregtech:iron_wire_single",
	"gregtech:niobium_nitride_wire_single",
	"gregtech:uranium_rhodium_dinaquadide_wire_single",
	"gregtech:steel_wire_single",
	"gregtech:europium_wire_single",
	"gregtech:tin_wire_single",
	"gregtech:vanadium_gallium_wire_single",
	"gregtech:niobium_titanium_wire_single",
	"gregtech:tritanium_wire_single",
	"gregtech:osmium_wire_single",
	"gregtech:graphene_wire_single",
	"gregtech:copper_wire_single",
	"gregtech:gold_wire_single",
	"gregtech:black_steel_wire_single",
	"gregtech:kanthal_wire_single",
	"gregtech:nickel_wire_single",
	"gregtech:yttrium_barium_cuprate_wire_single",
	"gregtech:electrum_wire_single",
	"gregtech:tungsten_steel_wire_single",
	"gregtech:lead_wire_single",
	"gregtech:blue_alloy_wire_single",
	"gregtech:red_alloy_wire_single"
];

// Удаление рецептов крафта проводов из грега из пластин в верстаке
for item in GTWireSingle{
    recipes.removeByRecipeName(item);
}

// Рецепты крафта шестерен в верстаке
global GTCraftGear as string[] = [
	"gregtech:gear_rose_gold",
	"gregtech:gear_brass",
	"gregtech:gear_iridium",
	"gregtech:gear_silver",
	"gregtech:gear_iron",
	"gregtech:gear_sterling_silver",
	"gregtech:gear_red_steel",
	"gregtech:gear_gold",
	"gregtech:gear_potin",
	"gregtech:gear_ruridit",
	"gregtech:gear_naquadria",
	"gregtech:gear_platinum",
	"gregtech:gear_bronze",
	"gregtech:gear_blue_steel",
	"gregtech:gear_stainless_steel",
	"gregtech:gear_cobalt_brass",
	"gregtech:gear_ultimet",
	"gregtech:gear_ruthenium",
	"gregtech:gear_rhodium",
	"gregtech:gear_invar",
	"gregtech:gear_tungsten",
	"gregtech:gear_black_steel",
	"gregtech:gear_lead",
	"gregtech:gear_silicone_rubber",
	"gregtech:gear_copper",
	"gregtech:gear_black_bronze",
	"gregtech:gear_rubber",
	"gregtech:gear_tritanium",
	"gregtech:gear_tungsten_steel",
	"gregtech:gear_aluminium",
	"gregtech:gear_tin",
	"gregtech:gear_titanium",
	"gregtech:gear_trinium",
	"gregtech:gear_hssg",
	"gregtech:gear_hsss",
	"gregtech:gear_vanadium_steel",
	"gregtech:gear_osmiridium",
	"gregtech:gear_duranium",
	"gregtech:gear_naquadah_alloy",
	"gregtech:gear_bismuth_bronze",
	"gregtech:gear_zinc",
	"gregtech:gear_tungsten_carbide",
	"gregtech:gear_wrought_iron",
	"gregtech:gear_steel"
];

// Удаление рецептов крафта шестерен в верстаке
for item in GTCraftGear{
    recipes.removeByRecipeName(item);
}

// Рецепты крафта маленьких шестерен в верстаке
global GTCraftSmallGear as string[] = [
	"gregtech:small_gear_darmstadtium",
	"gregtech:small_gear_naquadah_alloy",
	"gregtech:small_gear_tungsten_carbide",
	"gregtech:small_gear_titanium",
	"gregtech:small_gear_tungsten_steel",
	"gregtech:small_gear_tritanium",
	"gregtech:small_gear_osmiridium",
	"gregtech:small_gear_hssg",
	"gregtech:small_gear_hsss",
	"gregtech:small_gear_rhodium_plated_palladium",
	"gregtech:small_gear_bronze",
	"gregtech:small_gear_aluminium",
	"gregtech:small_gear_steel",
	"gregtech:small_gear_iron",
	"gregtech:small_gear_stainless_steel"
];

// Удаление рецептов крафта маленьких шестерен в верстаке
for item in GTCraftSmallGear{
    recipes.removeByRecipeName(item);
}

// Рецепты крафта стержней в верстаке
global GTCraftStickLong as string[] = [
	"gregtech:stick_long_stick_ruridit",
	"gregtech:stick_long_stick_lead",
	"gregtech:stick_long_stick_bronze",
	"gregtech:stick_long_stick_hsla_steel",
	"gregtech:stick_long_stick_nickel",
	"gregtech:stick_long_stick_osmium",
	"gregtech:stick_long_stick_copper",
	"gregtech:stick_long_stick_brass",
	"gregtech:stick_long_stick_annealed_copper",
	"gregtech:stick_long_stick_potin",
	"gregtech:stick_long_stick_platinum",
	"gregtech:stick_long_stick_aluminium",
	"gregtech:stick_long_stick_iridium",
	"gregtech:stick_long_stick_europium",
	"gregtech:stick_long_stick_bismuth",
	"gregtech:stick_long_stick_naquadah",
	"gregtech:stick_long_stick_ultimet",
	"gregtech:stick_long_stick_nichrome",
	"gregtech:stick_long_stick_titanium",
	"gregtech:stick_long_stick_red_steel",
	"gregtech:stick_long_stick_osmiridium",
	"gregtech:stick_long_stick_rhodium_plated_palladium",
	"gregtech:stick_long_stick_samarium",
	"gregtech:stick_long_stick_wrought_iron",
	"gregtech:stick_long_stick_neutronium",
	"gregtech:stick_long_stick_blue_steel",
	"gregtech:stick_long_stick_cupronickel",
	"gregtech:stick_long_stick_black_steel",
	"gregtech:stick_long_stick_yttrium_barium_cuprate",
	"gregtech:stick_long_stick_molybdenum_disilicide",
	"gregtech:stick_long_stick_black_bronze",
	"gregtech:stick_long_stick_niobium_titanium",
	"gregtech:stick_long_stick_samarium_magnetic",
	"gregtech:stick_long_stick_magnalium",
	"gregtech:stick_long_stick_rhodium",
	"gregtech:stick_long_stick_invar",
	"gregtech:stick_long_stick_iron",
	"gregtech:stick_long_stick_electrum",
	"gregtech:stick_long_stick_darmstadtium",
	"gregtech:stick_long_stick_tin_alloy",
	"gregtech:stick_long_stick_vanadium_gallium",
	"gregtech:stick_long_stick_tungsten_steel",
	"gregtech:stick_long_stick_sterling_silver",
	"gregtech:stick_long_stick_silver",
	"gregtech:stick_long_stick_rose_gold",
	"gregtech:stick_long_stick_zinc",
	"gregtech:stick_long_stick_tungsten_carbide",
	"gregtech:stick_long_stick_tritanium",
	"gregtech:stick_long_stick_cobalt_brass",
	"gregtech:stick_long_stick_tungsten",
	"gregtech:stick_long_stick_bismuth_bronze",
	"gregtech:stick_long_stick_wood",
	"gregtech:stick_long_stick_tin",
	"gregtech:stick_long_stick_kanthal",
	"gregtech:stick_long_stick_hsss",
	"gregtech:stick_long_stick_hsse",
	"gregtech:stick_long_stick_hssg",
	"gregtech:stick_long_stick_stainless_steel",
	"gregtech:stick_long_stick_vanadium_steel",
	"gregtech:stick_long_stick_steel",
	"gregtech:stick_long_stick_gold",
	"gregtech:stick_long_stick_naquadah_alloy"
];

// Удаление рецептов крафта стержней в верстаке
for item in GTCraftStickLong{
    recipes.removeByRecipeName(item);
}


print("Initialized 'RecipeTable'");