#priority 3
# TableMaterials

import crafttweaker.item.IItemStack;
import crafttweaker.liquid.ILiquidStack;

print("Initializing 'TableMaterials'...");


// Таблица всех руд из Грега
global GregtechOres as IItemStack[] = [
	<gregtech:ore_aluminium_0>,
	<gregtech:ore_aluminium_1>,
	<gregtech:ore_aluminium_2>,
	<gregtech:ore_beryllium_0>,
	<gregtech:ore_beryllium_1>,
	<gregtech:ore_beryllium_2>,
	<gregtech:ore_bismuth_0>,
	<gregtech:ore_bismuth_1>,
	<gregtech:ore_bismuth_2>,
	<gregtech:ore_cobalt_0>,
	<gregtech:ore_cobalt_1>,
	<gregtech:ore_cobalt_2>,
	<gregtech:ore_copper_0>,
	<gregtech:ore_copper_1>,
	<gregtech:ore_copper_2>,
	<gregtech:ore_gold_0>,
	<gregtech:ore_gold_1>,
	<gregtech:ore_gold_2>,
	<gregtech:ore_iron_0>,
	<gregtech:ore_iron_1>,
	<gregtech:ore_iron_2>,
	<gregtech:ore_lead_0>,
	<gregtech:ore_lead_1>,
	<gregtech:ore_lead_2>,
	<gregtech:ore_lithium_0>,
	<gregtech:ore_lithium_1>,
	<gregtech:ore_lithium_2>,
	<gregtech:ore_molybdenum_0>,
	<gregtech:ore_molybdenum_1>,
	<gregtech:ore_molybdenum_2>,
	<gregtech:ore_neodymium_0>,
	<gregtech:ore_neodymium_1>,
	<gregtech:ore_neodymium_2>,
	<gregtech:ore_nickel_0>,
	<gregtech:ore_nickel_1>,
	<gregtech:ore_nickel_2>,
	<gregtech:ore_palladium_0>,
	<gregtech:ore_palladium_1>,
	<gregtech:ore_palladium_2>,
	<gregtech:ore_platinum_0>,
	<gregtech:ore_platinum_1>,
	<gregtech:ore_platinum_2>,
	<gregtech:ore_plutonium_0>,
	<gregtech:ore_plutonium_1>,
	<gregtech:ore_plutonium_2>,
	<gregtech:ore_silver_0>,
	<gregtech:ore_silver_1>,
	<gregtech:ore_silver_2>,
	<gregtech:ore_sulfur_0>,
	<gregtech:ore_sulfur_1>,
	<gregtech:ore_sulfur_2>,
	<gregtech:ore_thorium_0>,
	<gregtech:ore_thorium_1>,
	<gregtech:ore_thorium_2>,
	<gregtech:ore_tin_0>,
	<gregtech:ore_tin_1>,
	<gregtech:ore_tin_2>,
	<gregtech:ore_naquadah_0>,
	<gregtech:ore_naquadah_1>,
	<gregtech:ore_naquadah_2>,
	<gregtech:ore_certus_quartz_0>,
	<gregtech:ore_certus_quartz_1>,
	<gregtech:ore_certus_quartz_2>,
	<gregtech:ore_almandine_0>,
	<gregtech:ore_almandine_1>,
	<gregtech:ore_almandine_2>,
	<gregtech:ore_asbestos_0>,
	<gregtech:ore_asbestos_1>,
	<gregtech:ore_asbestos_2>,
	<gregtech:ore_banded_iron_0>,
	<gregtech:ore_banded_iron_1>,
	<gregtech:ore_banded_iron_2>,
	<gregtech:ore_blue_topaz_0>,
	<gregtech:ore_blue_topaz_1>,
	<gregtech:ore_blue_topaz_2>,
	<gregtech:ore_brown_limonite_0>,
	<gregtech:ore_brown_limonite_1>,
	<gregtech:ore_brown_limonite_2>,
	<gregtech:ore_calcite_0>,
	<gregtech:ore_calcite_1>,
	<gregtech:ore_calcite_2>,
	<gregtech:ore_cassiterite_0>,
	<gregtech:ore_cassiterite_1>,
	<gregtech:ore_cassiterite_2>,
	<gregtech:ore_cassiterite_sand_0>,
	<gregtech:ore_cassiterite_sand_1>,
	<gregtech:ore_cassiterite_sand_2>,
	<gregtech:ore_chalcopyrite_0>,
	<gregtech:ore_chalcopyrite_1>,
	<gregtech:ore_chalcopyrite_2>,
	<gregtech:ore_chromite_0>,
	<gregtech:ore_chromite_1>,
	<gregtech:ore_chromite_2>,
	<gregtech:ore_cinnabar_0>,
	<gregtech:ore_cinnabar_1>,
	<gregtech:ore_cinnabar_2>,
	<gregtech:ore_coal_0>,
	<gregtech:ore_coal_1>,
	<gregtech:ore_coal_2>,
	<gregtech:ore_cobaltite_0>,
	<gregtech:ore_cobaltite_1>,
	<gregtech:ore_cobaltite_2>,
	<gregtech:ore_cooperite_0>,
	<gregtech:ore_cooperite_1>,
	<gregtech:ore_cooperite_2>,
	<gregtech:ore_diamond_0>,
	<gregtech:ore_diamond_1>,
	<gregtech:ore_diamond_2>,
	<gregtech:ore_emerald_0>,
	<gregtech:ore_emerald_1>,
	<gregtech:ore_emerald_2>,
	<gregtech:ore_galena_0>,
	<gregtech:ore_galena_1>,
	<gregtech:ore_galena_2>,
	<gregtech:ore_garnierite_0>,
	<gregtech:ore_garnierite_1>,
	<gregtech:ore_garnierite_2>,
	<gregtech:ore_green_sapphire_0>,
	<gregtech:ore_green_sapphire_1>,
	<gregtech:ore_green_sapphire_2>,
	<gregtech:ore_grossular_0>,
	<gregtech:ore_grossular_1>,
	<gregtech:ore_grossular_2>,
	<gregtech:ore_ilmenite_0>,
	<gregtech:ore_ilmenite_1>,
	<gregtech:ore_ilmenite_2>,
	<gregtech:ore_bauxite_0>,
	<gregtech:ore_bauxite_1>,
	<gregtech:ore_bauxite_2>,
	<gregtech:ore_lazurite_0>,
	<gregtech:ore_lazurite_1>,
	<gregtech:ore_lazurite_2>,
	<gregtech:ore_magnesite_0>,
	<gregtech:ore_magnesite_1>,
	<gregtech:ore_magnesite_2>,
	<gregtech:ore_magnetite_0>,
	<gregtech:ore_magnetite_1>,
	<gregtech:ore_magnetite_2>,
	<gregtech:ore_molybdenite_0>,
	<gregtech:ore_molybdenite_1>,
	<gregtech:ore_molybdenite_2>,
	<gregtech:ore_powellite_0>,
	<gregtech:ore_powellite_1>,
	<gregtech:ore_powellite_2>,
	<gregtech:ore_pyrite_0>,
	<gregtech:ore_pyrite_1>,
	<gregtech:ore_pyrite_2>,
	<gregtech:ore_pyrolusite_0>,
	<gregtech:ore_pyrolusite_1>,
	<gregtech:ore_pyrolusite_2>,
	<gregtech:ore_pyrope_0>,
	<gregtech:ore_pyrope_1>,
	<gregtech:ore_pyrope_2>,
	<gregtech:ore_rock_salt_0>,
	<gregtech:ore_rock_salt_1>,
	<gregtech:ore_rock_salt_2>,
	<gregtech:ore_ruby_0>,
	<gregtech:ore_ruby_1>,
	<gregtech:ore_ruby_2>,
	<gregtech:ore_salt_0>,
	<gregtech:ore_salt_1>,
	<gregtech:ore_salt_2>,
	<gregtech:ore_saltpeter_0>,
	<gregtech:ore_saltpeter_1>,
	<gregtech:ore_saltpeter_2>,
	<gregtech:ore_sapphire_0>,
	<gregtech:ore_sapphire_1>,
	<gregtech:ore_sapphire_2>,
	<gregtech:ore_scheelite_0>,
	<gregtech:ore_scheelite_1>,
	<gregtech:ore_scheelite_2>,
	<gregtech:ore_sodalite_0>,
	<gregtech:ore_sodalite_1>,
	<gregtech:ore_sodalite_2>,
	<gregtech:ore_tantalite_0>,
	<gregtech:ore_tantalite_1>,
	<gregtech:ore_tantalite_2>,
	<gregtech:ore_spessartine_0>,
	<gregtech:ore_spessartine_1>,
	<gregtech:ore_spessartine_2>,
	<gregtech:ore_sphalerite_0>,
	<gregtech:ore_sphalerite_1>,
	<gregtech:ore_sphalerite_2>,
	<gregtech:ore_stibnite_0>,
	<gregtech:ore_stibnite_1>,
	<gregtech:ore_stibnite_2>,
	<gregtech:ore_tetrahedrite_0>,
	<gregtech:ore_tetrahedrite_1>,
	<gregtech:ore_tetrahedrite_2>,
	<gregtech:ore_topaz_0>,
	<gregtech:ore_topaz_1>,
	<gregtech:ore_topaz_2>,
	<gregtech:ore_tungstate_0>,
	<gregtech:ore_tungstate_1>,
	<gregtech:ore_tungstate_2>,
	<gregtech:ore_uraninite_0>,
	<gregtech:ore_uraninite_1>,
	<gregtech:ore_uraninite_2>,
	<gregtech:ore_wulfenite_0>,
	<gregtech:ore_wulfenite_1>,
	<gregtech:ore_wulfenite_2>,
	<gregtech:ore_yellow_limonite_0>,
	<gregtech:ore_yellow_limonite_1>,
	<gregtech:ore_yellow_limonite_2>,
	<gregtech:ore_nether_quartz_0>,
	<gregtech:ore_nether_quartz_1>,
	<gregtech:ore_nether_quartz_2>,
	<gregtech:ore_quartzite_0>,
	<gregtech:ore_quartzite_1>,
	<gregtech:ore_quartzite_2>,
	<gregtech:ore_graphite_0>,
	<gregtech:ore_graphite_1>,
	<gregtech:ore_graphite_2>,
	<gregtech:ore_bornite_0>,
	<gregtech:ore_bornite_1>,
	<gregtech:ore_bornite_2>,
	<gregtech:ore_chalcocite_0>,
	<gregtech:ore_chalcocite_1>,
	<gregtech:ore_chalcocite_2>,
	<gregtech:ore_realgar_0>,
	<gregtech:ore_realgar_1>,
	<gregtech:ore_realgar_2>,
	<gregtech:ore_bastnasite_0>,
	<gregtech:ore_bastnasite_1>,
	<gregtech:ore_bastnasite_2>,
	<gregtech:ore_pentlandite_0>,
	<gregtech:ore_pentlandite_1>,
	<gregtech:ore_pentlandite_2>,
	<gregtech:ore_spodumene_0>,
	<gregtech:ore_spodumene_1>,
	<gregtech:ore_spodumene_2>,
	<gregtech:ore_lepidolite_0>,
	<gregtech:ore_lepidolite_1>,
	<gregtech:ore_lepidolite_2>,
	<gregtech:ore_glauconite_sand_0>,
	<gregtech:ore_glauconite_sand_1>,
	<gregtech:ore_glauconite_sand_2>,
	<gregtech:ore_malachite_0>,
	<gregtech:ore_malachite_1>,
	<gregtech:ore_malachite_2>,
	<gregtech:ore_mica_0>,
	<gregtech:ore_mica_1>,
	<gregtech:ore_mica_2>,
	<gregtech:ore_barite_0>,
	<gregtech:ore_barite_1>,
	<gregtech:ore_barite_2>,
	<gregtech:ore_alunite_0>,
	<gregtech:ore_alunite_1>,
	<gregtech:ore_alunite_2>,
	<gregtech:ore_talc_0>,
	<gregtech:ore_talc_1>,
	<gregtech:ore_talc_2>,
	<gregtech:ore_soapstone_0>,
	<gregtech:ore_soapstone_1>,
	<gregtech:ore_soapstone_2>,
	<gregtech:ore_kyanite_0>,
	<gregtech:ore_kyanite_1>,
	<gregtech:ore_kyanite_2>,
	<gregtech:ore_pyrochlore_0>,
	<gregtech:ore_pyrochlore_1>,
	<gregtech:ore_pyrochlore_2>,
	<gregtech:ore_oilsands_0>,
	<gregtech:ore_oilsands_1>,
	<gregtech:ore_oilsands_2>,
	<gregtech:ore_glowstone_0>,
	<gregtech:ore_glowstone_1>,
	<gregtech:ore_glowstone_2>,
	<gregtech:ore_olivine_0>,
	<gregtech:ore_olivine_1>,
	<gregtech:ore_olivine_2>,
	<gregtech:ore_opal_0>,
	<gregtech:ore_opal_1>,
	<gregtech:ore_opal_2>,
	<gregtech:ore_amethyst_0>,
	<gregtech:ore_amethyst_1>,
	<gregtech:ore_amethyst_2>,
	<gregtech:ore_lapis_0>,
	<gregtech:ore_lapis_1>,
	<gregtech:ore_lapis_2>,
	<gregtech:ore_apatite_0>,
	<gregtech:ore_apatite_1>,
	<gregtech:ore_apatite_2>,
	<gregtech:ore_tricalcium_phosphate_0>,
	<gregtech:ore_tricalcium_phosphate_1>,
	<gregtech:ore_tricalcium_phosphate_2>,
	<gregtech:ore_garnet_red_0>,
	<gregtech:ore_garnet_red_1>,
	<gregtech:ore_garnet_red_2>,
	<gregtech:ore_garnet_yellow_0>,
	<gregtech:ore_garnet_yellow_1>,
	<gregtech:ore_garnet_yellow_2>,
	<gregtech:ore_vanadium_magnetite_0>,
	<gregtech:ore_vanadium_magnetite_1>,
	<gregtech:ore_vanadium_magnetite_2>,
	<gregtech:ore_pollucite_0>,
	<gregtech:ore_pollucite_1>,
	<gregtech:ore_pollucite_2>,
	<gregtech:ore_bentonite_0>,
	<gregtech:ore_bentonite_1>,
	<gregtech:ore_bentonite_2>,
	<gregtech:ore_fullers_earth_0>,
	<gregtech:ore_fullers_earth_1>,
	<gregtech:ore_fullers_earth_2>,
	<gregtech:ore_pitchblende_0>,
	<gregtech:ore_pitchblende_1>,
	<gregtech:ore_pitchblende_2>,
	<gregtech:ore_monazite_0>,
	<gregtech:ore_monazite_1>,
	<gregtech:ore_monazite_2>,
	<gregtech:ore_trona_0>,
	<gregtech:ore_trona_1>,
	<gregtech:ore_trona_2>,
	<gregtech:ore_gypsum_0>,
	<gregtech:ore_gypsum_1>,
	<gregtech:ore_gypsum_2>,
	<gregtech:ore_zeolite_0>,
	<gregtech:ore_zeolite_1>,
	<gregtech:ore_zeolite_2>,
	<gregtech:ore_redstone_0>,
	<gregtech:ore_redstone_1>,
	<gregtech:ore_redstone_2>,
	<gregtech:ore_electrotine_0>,
	<gregtech:ore_electrotine_1>,
	<gregtech:ore_electrotine_2>,
	<gregtech:ore_diatomite_0>,
	<gregtech:ore_diatomite_1>,
	<gregtech:ore_diatomite_2>,
	<gregtech:ore_granitic_mineral_sand_0>,
	<gregtech:ore_granitic_mineral_sand_1>,
	<gregtech:ore_granitic_mineral_sand_2>,
	<gregtech:ore_garnet_sand_0>,
	<gregtech:ore_garnet_sand_1>,
	<gregtech:ore_garnet_sand_2>,
	<gregtech:ore_basaltic_mineral_sand_0>,
	<gregtech:ore_basaltic_mineral_sand_1>,
	<gregtech:ore_basaltic_mineral_sand_2>
];

// Таблица необработанных магматических интрузивных пород
global RawIgneousIntrusive as IItemStack[] = [
	<tfc:raw/granite>, 
	<tfc:raw/gabbro>, 
	<tfc:raw/rhyolite>, 
	<tfc:raw/diorite>
];

// Таблица необработанных магматических экструзионных пород
global RawIgneousExtrusive as IItemStack[] = [
	<tfc:raw/basalt>, 
	<tfc:raw/dacite>, 
	<tfc:raw/andesite>
];

// Таблица необработанных метаморфических пород
global RawMetamorphic as IItemStack[] = [
	<tfc:raw/marble>, 
	<tfc:raw/gneiss>, 
	<tfc:raw/schist>, 
	<tfc:raw/quartzite>, 
	<tfc:raw/phyllite>, 
	<tfc:raw/slate>
];

// Таблица необработанных осадочных пород
global RawSedimentary as IItemStack[] = [
	<tfc:raw/shale>, 
	<tfc:raw/dolomite>, 
	<tfc:raw/conglomerate>, 
	<tfc:raw/limestone>, 
	<tfc:raw/rocksalt>, 
	<tfc:raw/claystone>, 
	<tfc:raw/chert>, 
	<tfc:raw/chalk>
];

// Рецепты для переработки растительности к красители в измельчителе (вход)
global TFC_QuernToMaceratorInput as IItemStack[] = [
	<tfc:plants/sargassum>,
	<tfc:plants/rough_horsetail>,
	<tfc:plants/grape_hyacinth>,
	<tfc:plants/blue_orchid>,
	<tfc:plants/snapdragon_pink>,
	<tfc:plants/tulip_pink>,
	<tfc:plants/sacred_datura>,
	<tfc:plants/foxglove>,
	<tfc:plants/moss>,
	<tfc:plants/sapphire_tower>,
	<tfc:plants/labrador_tea>,
	<tfc:plants/black_orchid>,
	<tfc:plants/perovskia>,
	<tfc:plants/allium>,
	<tfc:plants/sagebrush>,
	<tfc:plants/snapdragon_yellow>,
	<tfc:plants/dandelion>,
	<tfc:plants/goldenrod>,
	<tfc:plants/calendula>,
	<tfc:plants/meads_milkweed>,
	<tfc:plants/tropical_milkweed>,
	<tfc:plants/tulip_red>,
	<tfc:plants/vriesea>,
	<tfc:plants/snapdragon_red>,
	<tfc:plants/rose>,
	<tfc:plants/poppy>,
	<tfc:plants/guzmania>,
	<tfc:plants/strelitzia>,
	<tfc:plants/canna>,
	<tfc:plants/water_canna>,
	<tfc:plants/tulip_orange>,
	<tfc:plants/butterfly_milkweed>,
	<tfc:plants/nasturtium>,
	<tfc:plants/yucca>,
	<tfc:plants/trillium>,
	<tfc:plants/snapdragon_white>,
	<tfc:plants/primrose>,
	<tfc:plants/reindeer_lichen>,
	<tfc:plants/oxeye_daisy>,
	<tfc:plants/houstonia>,
	<tfc:plants/tulip_white>,
	<tfc:plants/spanish_moss>,
	<tfc:plants/athyrium_fern>,
	<tfc:plants/pulsatilla>,
	<tfc:plants/blood_lily>,
	<tfc:plants/morning_glory>,
	<tfc:plants/ryegrass>,
	<tfc:plants/orchard_grass>,
	<tfc:plants/switchgrass>,
	<tfc:plants/licorice_fern>,
	<tfc:plants/duckweed>,
	<tfc:plants/ostrich_fern>,
	<tfc:plants/field_horsetail>,
	<tfc:plants/fountain_grass>,
	<tfc:plants/lady_fern>,
	<tfc:plants/water_lily>,
	<tfc:plants/barrel_cactus>,
	<tfc:plants/scutch_grass>,
	<tfc:plants/tall_fescue_grass>,
	<tfc:plants/lotus>,
	<tfc:plants/pistia>,
	<tfc:plants/toquilla_palm>,
	<tfc:plants/timothy_grass>,
	<tfc:plants/sword_fern>,
	<tfc:plants/tree_fern>,
	<tfc:plants/pampas_grass>
];

// Рецепты для переработки растительности к красители в измельчителе (выход)
global TFC_QuernToMaceratorOutput as IItemStack[] = [
	<tfc:dye/brown>,
	<tfc:dye/brown>,
	<tfc:dye/blue>,
	<tfc:dye/blue>,
	<minecraft:dye:9>,
	<minecraft:dye:9>,
	<minecraft:dye:9>,
	<minecraft:dye:9>,
	<minecraft:dye:10>,
	<minecraft:dye:12>,
	<minecraft:dye:12>,
	<minecraft:dye:5>,
	<minecraft:dye:5>,
	<minecraft:dye:5>,
	<minecraft:dye:11>,
	<minecraft:dye:11>,
	<minecraft:dye:11>,
	<minecraft:dye:11>,
	<minecraft:dye:11>,
	<minecraft:dye:11>,
	<minecraft:dye:1>,
	<minecraft:dye:1>,
	<minecraft:dye:1>,
	<minecraft:dye:1>,
	<minecraft:dye:1>,
	<minecraft:dye:1>,
	<minecraft:dye:1>,
	<minecraft:dye:14>,
	<minecraft:dye:14>,
	<minecraft:dye:14>,
	<minecraft:dye:14>,
	<minecraft:dye:14>,
	<minecraft:dye:14>,
	<minecraft:dye:7>,
	<tfc:dye/white>,
	<tfc:dye/white>,
	<tfc:dye/white>,
	<tfc:dye/white>,
	<tfc:dye/white>,
	<tfc:dye/white>,
	<tfc:dye/white>,
	<tfc:dye/white>,
	<minecraft:dye:13>,
	<minecraft:dye:13>,
	<minecraft:dye:13>,
	<minecraft:dye:13>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>,
	<minecraft:dye:2>
];

// Рецепты для переработки зерновых в измельчителе (вход)
global TFC_GrainCentrifugeInput as IItemStack[] = [
	<tfc:food/rye>,
	<tfc:food/oat>,
	<tfc:food/barley>,
	<tfc:food/wheat>,
	<tfc:food/rice>,
	<tfc:food/maize>
];

// Рецепты для переработки зерновых в измельчителе (выход)
global TFC_GrainCentrifugeOutput as IItemStack[] = [
	<tfc:food/rye_grain>,
	<tfc:food/oat_grain>,
	<tfc:food/barley_grain>,
	<tfc:food/wheat_grain>,
	<tfc:food/rice_grain>,
	<tfc:food/maize_grain>
];

// Рецепты для переработки муки в измельчителе (вход)
global TFC_FlourCentrifugeInput as IItemStack[] = [
	<tfc:food/rye_grain>,
	<tfc:food/oat_grain>,
	<tfc:food/barley_grain>,
	<tfc:food/wheat_grain>,
	<tfc:food/rice_grain>,
	<tfc:food/maize_grain>
];

// Рецепты для переработки муки в измельчителе (выход)
global TFC_FlourCentrifugeOutput as IItemStack[] = [
	<tfc:food/rye_flour>,
	<tfc:food/oat_flour>,
	<tfc:food/barley_flour>,
	<tfc:food/wheat_flour>,
	<tfc:food/rice_flour>,
	<tfc:food/cornmeal_flour>
];

// Таблица готового мяса из ТФК
global TFC_Cooked_Meat as IItemStack[] = [
	<tfc:food/cooked_beef>,
	<tfc:food/cooked_pork>,
	<tfc:food/cooked_chicken>,
	<tfc:food/cooked_mutton>,
	<tfc:food/cooked_fish>,
	<tfc:food/cooked_bear>,
	<tfc:food/cooked_calamari>,
	<tfc:food/cooked_horse_meat>,
	<tfc:food/cooked_pheasant>,
	<tfc:food/cooked_mongoose>,
	<tfc:food/cooked_gran_feline>,
	<tfc:food/cooked_camelidae>,
	<tfc:food/cooked_rabbit>,
	<tfc:food/cooked_wolf>,
	<tfc:food/cooked_venison>
];

// Таблица сырого мяса из ТФК
global TFC_Raw_Meat as IItemStack[] = [
	<tfc:food/beef>,
	<tfc:food/pork>,
	<tfc:food/chicken>,
	<tfc:food/mutton>,
	<tfc:food/fish>,
	<tfc:food/bear>,
	<tfc:food/calamari>,
	<tfc:food/horse_meat>,
	<tfc:food/pheasant>,
	<tfc:food/mongoose>,
	<tfc:food/gran_feline>,
	<tfc:food/camelidae>,
	<tfc:food/rabbit>,
	<tfc:food/wolf>,
	<tfc:food/venison>
];

// Таблица готовых керамических изделий
global TFC_Fired_Ceramics as IItemStack[] = [
	<tfc:ceramics/fired/mold/hammer_head>,
	<tfc:ceramics/fired/mold/knife_blade>,
	<tfc:ceramics/fired/mold/scythe_blade>,
	<tfc:ceramics/fired/mold/ingot>,
	<tfc:ceramics/fired/mold/pick_head>,
	<tfc:ceramics/fired/mold/shovel_head>,
	<tfc:ceramics/fired/mold/axe_head>,
	<tfc:ceramics/fired/mold/hoe_head>,
	<tfc:ceramics/fired/mold/chisel_head>,
	<tfc:ceramics/fired/mold/sword_blade>,
	<tfc:ceramics/fired/mold/mace_head>,
	<tfc:ceramics/fired/mold/saw_blade>,
	<tfc:ceramics/fired/mold/javelin_head>,
	<tfc:ceramics/fired/mold/hammer_head>,
	<tfc:ceramics/fired/mold/propick_head>,
	<tfc:ceramics/fired/large_vessel>,
	<tfc:ceramics/fired/vessel>,
	<tfc:ceramics/fired/vessel_glazed:15>,
	<tfc:ceramics/fired/vessel_glazed:14>,
	<tfc:ceramics/fired/vessel_glazed:13>,
	<tfc:ceramics/fired/vessel_glazed:12>,
	<tfc:ceramics/fired/vessel_glazed:11>,
	<tfc:ceramics/fired/vessel_glazed:10>,
	<tfc:ceramics/fired/vessel_glazed:9>,
	<tfc:ceramics/fired/vessel_glazed:8>,
	<tfc:ceramics/fired/vessel_glazed:7>,
	<tfc:ceramics/fired/vessel_glazed:6>,
	<tfc:ceramics/fired/vessel_glazed:5>,
	<tfc:ceramics/fired/vessel_glazed:4>,
	<tfc:ceramics/fired/vessel_glazed:3>,
	<tfc:ceramics/fired/vessel_glazed:2>,
	<tfc:ceramics/fired/vessel_glazed:1>,
	<tfc:ceramics/fired/vessel_glazed:0>,
	<tfc:ceramics/fired/pot>,
	<tfc:ceramics/fired/bowl>,
	<tfc:ceramics/fired/spindle>,
	<tfc:ceramics/fired/fire_brick>,
	<tfc:ceramics/fired/jug>,
	<tfc:crucible>,
	<minecraft:brick>,
	<minecraft:flower_pot>
];

// Таблица сырых керамических изделий
global TFC_Unfired_Ceramics as IItemStack[] = [
	<tfc:ceramics/unfired/mold/hammer_head>,
	<tfc:ceramics/unfired/mold/knife_blade>,
	<tfc:ceramics/unfired/mold/scythe_blade>,
	<tfc:ceramics/unfired/mold/ingot>,
	<tfc:ceramics/unfired/mold/pick_head>,
	<tfc:ceramics/unfired/mold/shovel_head>,
	<tfc:ceramics/unfired/mold/axe_head>,
	<tfc:ceramics/unfired/mold/hoe_head>,
	<tfc:ceramics/unfired/mold/chisel_head>,
	<tfc:ceramics/unfired/mold/sword_blade>,
	<tfc:ceramics/unfired/mold/mace_head>,
	<tfc:ceramics/unfired/mold/saw_blade>,
	<tfc:ceramics/unfired/mold/javelin_head>,
	<tfc:ceramics/unfired/mold/hammer_head>,
	<tfc:ceramics/unfired/mold/propick_head>,
	<tfc:ceramics/unfired/large_vessel>,
	<tfc:ceramics/unfired/vessel>,
	<tfc:ceramics/unfired/vessel_glazed:15>,
	<tfc:ceramics/unfired/vessel_glazed:14>,
	<tfc:ceramics/unfired/vessel_glazed:13>,
	<tfc:ceramics/unfired/vessel_glazed:12>,
	<tfc:ceramics/unfired/vessel_glazed:11>,
	<tfc:ceramics/unfired/vessel_glazed:10>,
	<tfc:ceramics/unfired/vessel_glazed:9>,
	<tfc:ceramics/unfired/vessel_glazed:8>,
	<tfc:ceramics/unfired/vessel_glazed:7>,
	<tfc:ceramics/unfired/vessel_glazed:6>,
	<tfc:ceramics/unfired/vessel_glazed:5>,
	<tfc:ceramics/unfired/vessel_glazed:4>,
	<tfc:ceramics/unfired/vessel_glazed:3>,
	<tfc:ceramics/unfired/vessel_glazed:2>,
	<tfc:ceramics/unfired/vessel_glazed:1>,
	<tfc:ceramics/unfired/vessel_glazed:0>,
	<tfc:ceramics/unfired/pot>,
	<tfc:ceramics/unfired/bowl>,
	<tfc:ceramics/unfired/spindle>,
	<tfc:ceramics/unfired/fire_brick>,
	<tfc:ceramics/unfired/jug>,
	<tfc:ceramics/unfired/crucible>,
	<tfc:ceramics/unfired/clay_brick>,
	<tfc:ceramics/unfired/clay_flower_pot>
];

// Таблица необработанных горных пород ТФК
global TFC_Raws as IItemStack[] = [
	<tfc:raw/granite>,
	<tfc:raw/diorite>,
	<tfc:raw/gabbro>,
	<tfc:raw/shale>,
	<tfc:raw/claystone>,
	<tfc:raw/rocksalt>,
	<tfc:raw/limestone>,
	<tfc:raw/conglomerate>,
	<tfc:raw/dolomite>,
	<tfc:raw/chert>,
	<tfc:raw/chalk>,
	<tfc:raw/rhyolite>,
	<tfc:raw/basalt>,
	<tfc:raw/andesite>,
	<tfc:raw/dacite>,
	<tfc:raw/quartzite>,
	<tfc:raw/slate>,
	<tfc:raw/phyllite>,
	<tfc:raw/schist>,
	<tfc:raw/gneiss>,
	<tfc:raw/marble>
];

// Таблица гладких горных пород ТФК
global TFC_Smooths as IItemStack[] = [
	<tfc:smooth/granite>,
	<tfc:smooth/diorite>,
	<tfc:smooth/gabbro>,
	<tfc:smooth/shale>,
	<tfc:smooth/claystone>,
	<tfc:smooth/rocksalt>,
	<tfc:smooth/limestone>,
	<tfc:smooth/conglomerate>,
	<tfc:smooth/dolomite>,
	<tfc:smooth/chert>,
	<tfc:smooth/chalk>,
	<tfc:smooth/rhyolite>,
	<tfc:smooth/basalt>,
	<tfc:smooth/andesite>,
	<tfc:smooth/dacite>,
	<tfc:smooth/quartzite>,
	<tfc:smooth/slate>,
	<tfc:smooth/phyllite>,
	<tfc:smooth/schist>,
	<tfc:smooth/gneiss>,
	<tfc:smooth/marble>
];

// Таблица булыжника для разных горных пород ТФК
global TFC_Cobbles as IItemStack[] = [
	<tfc:cobble/granite>,
	<tfc:cobble/diorite>,
	<tfc:cobble/gabbro>,
	<tfc:cobble/shale>,
	<tfc:cobble/claystone>,
	<tfc:cobble/rocksalt>,
	<tfc:cobble/limestone>,
	<tfc:cobble/conglomerate>,
	<tfc:cobble/dolomite>,
	<tfc:cobble/chert>,
	<tfc:cobble/chalk>,
	<tfc:cobble/rhyolite>,
	<tfc:cobble/basalt>,
	<tfc:cobble/andesite>,
	<tfc:cobble/dacite>,
	<tfc:cobble/quartzite>,
	<tfc:cobble/slate>,
	<tfc:cobble/phyllite>,
	<tfc:cobble/schist>,
	<tfc:cobble/gneiss>,
	<tfc:cobble/marble>
];

// Таблица гравия для разных горных пород ТФК
global TFC_Gravel as IItemStack[] = [
	<tfc:gravel/granite>,
	<tfc:gravel/diorite>,
	<tfc:gravel/gabbro>,
	<tfc:gravel/shale>,
	<tfc:gravel/claystone>,
	<tfc:gravel/rocksalt>,
	<tfc:gravel/limestone>,
	<tfc:gravel/conglomerate>,
	<tfc:gravel/dolomite>,
	<tfc:gravel/chert>,
	<tfc:gravel/chalk>,
	<tfc:gravel/rhyolite>,
	<tfc:gravel/basalt>,
	<tfc:gravel/andesite>,
	<tfc:gravel/dacite>,
	<tfc:gravel/quartzite>,
	<tfc:gravel/slate>,
	<tfc:gravel/phyllite>,
	<tfc:gravel/schist>,
	<tfc:gravel/gneiss>,
	<tfc:gravel/marble>
];

// Таблица песка для разных горных пород ТФК
global TFC_Sands as IItemStack[] = [
	<tfc:sand/granite>,
	<tfc:sand/diorite>,
	<tfc:sand/gabbro>,
	<tfc:sand/shale>,
	<tfc:sand/claystone>,
	<tfc:sand/rocksalt>,
	<tfc:sand/limestone>,
	<tfc:sand/conglomerate>,
	<tfc:sand/dolomite>,
	<tfc:sand/chert>,
	<tfc:sand/chalk>,
	<tfc:sand/rhyolite>,
	<tfc:sand/basalt>,
	<tfc:sand/andesite>,
	<tfc:sand/dacite>,
	<tfc:sand/quartzite>,
	<tfc:sand/slate>,
	<tfc:sand/phyllite>,
	<tfc:sand/schist>,
	<tfc:sand/gneiss>,
	<tfc:sand/marble>
];

// Таблица полублоков булыжника для разных горных пород ТФК
global TFC_Slabs_Cobble as IItemStack[] = [
	<tfc:slab/cobble/granite>,
	<tfc:slab/cobble/diorite>,
	<tfc:slab/cobble/gabbro>,
	<tfc:slab/cobble/shale>,
	<tfc:slab/cobble/claystone>,
	<tfc:slab/cobble/rocksalt>,
	<tfc:slab/cobble/limestone>,
	<tfc:slab/cobble/conglomerate>,
	<tfc:slab/cobble/dolomite>,
	<tfc:slab/cobble/chert>,
	<tfc:slab/cobble/chalk>,
	<tfc:slab/cobble/rhyolite>,
	<tfc:slab/cobble/basalt>,
	<tfc:slab/cobble/andesite>,
	<tfc:slab/cobble/dacite>,
	<tfc:slab/cobble/quartzite>,
	<tfc:slab/cobble/slate>,
	<tfc:slab/cobble/phyllite>,
	<tfc:slab/cobble/schist>,
	<tfc:slab/cobble/gneiss>,
	<tfc:slab/cobble/marble>
];

// Таблица гладких полублоков для разных горных пород ТФК
global TFC_Slabs_Smooth as IItemStack[] = [
	<tfc:slab/smooth/granite>,
	<tfc:slab/smooth/diorite>,
	<tfc:slab/smooth/gabbro>,
	<tfc:slab/smooth/shale>,
	<tfc:slab/smooth/claystone>,
	<tfc:slab/smooth/rocksalt>,
	<tfc:slab/smooth/limestone>,
	<tfc:slab/smooth/conglomerate>,
	<tfc:slab/smooth/dolomite>,
	<tfc:slab/smooth/chert>,
	<tfc:slab/smooth/chalk>,
	<tfc:slab/smooth/rhyolite>,
	<tfc:slab/smooth/basalt>,
	<tfc:slab/smooth/andesite>,
	<tfc:slab/smooth/dacite>,
	<tfc:slab/smooth/quartzite>,
	<tfc:slab/smooth/slate>,
	<tfc:slab/smooth/phyllite>,
	<tfc:slab/smooth/schist>,
	<tfc:slab/smooth/gneiss>,
	<tfc:slab/smooth/marble>
];

// Таблица кирпичных полублоков для разных горных пород ТФК
global TFC_Slabs_Bricks as IItemStack[] = [
	<tfc:slab/bricks/granite>,
	<tfc:slab/bricks/diorite>,
	<tfc:slab/bricks/gabbro>,
	<tfc:slab/bricks/shale>,
	<tfc:slab/bricks/claystone>,
	<tfc:slab/bricks/rocksalt>,
	<tfc:slab/bricks/limestone>,
	<tfc:slab/bricks/conglomerate>,
	<tfc:slab/bricks/dolomite>,
	<tfc:slab/bricks/chert>,
	<tfc:slab/bricks/chalk>,
	<tfc:slab/bricks/rhyolite>,
	<tfc:slab/bricks/basalt>,
	<tfc:slab/bricks/andesite>,
	<tfc:slab/bricks/dacite>,
	<tfc:slab/bricks/quartzite>,
	<tfc:slab/bricks/slate>,
	<tfc:slab/bricks/phyllite>,
	<tfc:slab/bricks/schist>,
	<tfc:slab/bricks/gneiss>,
	<tfc:slab/bricks/marble>
];

// Таблица булыжниковых лестниц для разных горных пород ТФК
global TFC_Stairs_Cobble as IItemStack[] = [
	<tfc:stairs/cobble/granite>,
	<tfc:stairs/cobble/diorite>,
	<tfc:stairs/cobble/gabbro>,
	<tfc:stairs/cobble/shale>,
	<tfc:stairs/cobble/claystone>,
	<tfc:stairs/cobble/rocksalt>,
	<tfc:stairs/cobble/limestone>,
	<tfc:stairs/cobble/conglomerate>,
	<tfc:stairs/cobble/dolomite>,
	<tfc:stairs/cobble/chert>,
	<tfc:stairs/cobble/chalk>,
	<tfc:stairs/cobble/rhyolite>,
	<tfc:stairs/cobble/basalt>,
	<tfc:stairs/cobble/andesite>,
	<tfc:stairs/cobble/dacite>,
	<tfc:stairs/cobble/quartzite>,
	<tfc:stairs/cobble/slate>,
	<tfc:stairs/cobble/phyllite>,
	<tfc:stairs/cobble/schist>,
	<tfc:stairs/cobble/gneiss>,
	<tfc:stairs/cobble/marble>
];

// Таблица гладких лестниц для разных горных пород ТФК
global TFC_Stairs_Smooth as IItemStack[] = [
	<tfc:stairs/smooth/granite>,
	<tfc:stairs/smooth/diorite>,
	<tfc:stairs/smooth/gabbro>,
	<tfc:stairs/smooth/shale>,
	<tfc:stairs/smooth/claystone>,
	<tfc:stairs/smooth/rocksalt>,
	<tfc:stairs/smooth/limestone>,
	<tfc:stairs/smooth/conglomerate>,
	<tfc:stairs/smooth/dolomite>,
	<tfc:stairs/smooth/chert>,
	<tfc:stairs/smooth/chalk>,
	<tfc:stairs/smooth/rhyolite>,
	<tfc:stairs/smooth/basalt>,
	<tfc:stairs/smooth/andesite>,
	<tfc:stairs/smooth/dacite>,
	<tfc:stairs/smooth/quartzite>,
	<tfc:stairs/smooth/slate>,
	<tfc:stairs/smooth/phyllite>,
	<tfc:stairs/smooth/schist>,
	<tfc:stairs/smooth/gneiss>,
	<tfc:stairs/smooth/marble>
];

// Таблица кирпичных лестниц для разных горных пород ТФК
global TFC_Stairs_Bricks as IItemStack[] = [
	<tfc:stairs/bricks/granite>,
	<tfc:stairs/bricks/diorite>,
	<tfc:stairs/bricks/gabbro>,
	<tfc:stairs/bricks/shale>,
	<tfc:stairs/bricks/claystone>,
	<tfc:stairs/bricks/rocksalt>,
	<tfc:stairs/bricks/limestone>,
	<tfc:stairs/bricks/conglomerate>,
	<tfc:stairs/bricks/dolomite>,
	<tfc:stairs/bricks/chert>,
	<tfc:stairs/bricks/chalk>,
	<tfc:stairs/bricks/rhyolite>,
	<tfc:stairs/bricks/basalt>,
	<tfc:stairs/bricks/andesite>,
	<tfc:stairs/bricks/dacite>,
	<tfc:stairs/bricks/quartzite>,
	<tfc:stairs/bricks/slate>,
	<tfc:stairs/bricks/phyllite>,
	<tfc:stairs/bricks/schist>,
	<tfc:stairs/bricks/gneiss>,
	<tfc:stairs/bricks/marble>
];

// Таблица нажимных плит для разных горных пород ТФК
global TFC_Stone_Pressure_Plates as IItemStack[] = [
	<tfc:stone/pressure_plate/granite>,
	<tfc:stone/pressure_plate/diorite>,
	<tfc:stone/pressure_plate/gabbro>,
	<tfc:stone/pressure_plate/shale>,
	<tfc:stone/pressure_plate/claystone>,
	<tfc:stone/pressure_plate/rocksalt>,
	<tfc:stone/pressure_plate/limestone>,
	<tfc:stone/pressure_plate/conglomerate>,
	<tfc:stone/pressure_plate/dolomite>,
	<tfc:stone/pressure_plate/chert>,
	<tfc:stone/pressure_plate/chalk>,
	<tfc:stone/pressure_plate/rhyolite>,
	<tfc:stone/pressure_plate/basalt>,
	<tfc:stone/pressure_plate/andesite>,
	<tfc:stone/pressure_plate/dacite>,
	<tfc:stone/pressure_plate/quartzite>,
	<tfc:stone/pressure_plate/slate>,
	<tfc:stone/pressure_plate/phyllite>,
	<tfc:stone/pressure_plate/schist>,
	<tfc:stone/pressure_plate/gneiss>,
	<tfc:stone/pressure_plate/marble>
];

// Таблица кнопок для разных горных пород ТФК
global TFC_Stone_Buttons as IItemStack[] = [
	<tfc:stone/button/granite>,
	<tfc:stone/button/diorite>,
	<tfc:stone/button/gabbro>,
	<tfc:stone/button/shale>,
	<tfc:stone/button/claystone>,
	<tfc:stone/button/rocksalt>,
	<tfc:stone/button/limestone>,
	<tfc:stone/button/conglomerate>,
	<tfc:stone/button/dolomite>,
	<tfc:stone/button/chert>,
	<tfc:stone/button/chalk>,
	<tfc:stone/button/rhyolite>,
	<tfc:stone/button/basalt>,
	<tfc:stone/button/andesite>,
	<tfc:stone/button/dacite>,
	<tfc:stone/button/quartzite>,
	<tfc:stone/button/slate>,
	<tfc:stone/button/phyllite>,
	<tfc:stone/button/schist>,
	<tfc:stone/button/gneiss>,
	<tfc:stone/button/marble>
];

// Таблица кирпичей (слиток) для разных горных пород ТФК
global TFC_Bricks_Item as IItemStack[] = [
	<tfc:brick/granite>,
	<tfc:brick/diorite>,
	<tfc:brick/gabbro>,
	<tfc:brick/shale>,
	<tfc:brick/claystone>,
	<tfc:brick/rocksalt>,
	<tfc:brick/limestone>,
	<tfc:brick/conglomerate>,
	<tfc:brick/dolomite>,
	<tfc:brick/chert>,
	<tfc:brick/chalk>,
	<tfc:brick/rhyolite>,
	<tfc:brick/basalt>,
	<tfc:brick/andesite>,
	<tfc:brick/dacite>,
	<tfc:brick/quartzite>,
	<tfc:brick/slate>,
	<tfc:brick/phyllite>,
	<tfc:brick/schist>,
	<tfc:brick/gneiss>,
	<tfc:brick/marble>
];

// Таблица ткацких станков из разных пород дерева ТФК
global TFC_Loom as IItemStack[] = [
	<tfc:wood/loom/acacia>,
	<tfc:wood/loom/ash>,
	<tfc:wood/loom/aspen>,
	<tfc:wood/loom/birch>,
	<tfc:wood/loom/blackwood>,
	<tfc:wood/loom/chestnut>,
	<tfc:wood/loom/douglas_fir>,
	<tfc:wood/loom/hickory>,
	<tfc:wood/loom/kapok>,
	<tfc:wood/loom/maple>,
	<tfc:wood/loom/oak>,
	<tfc:wood/loom/palm>,
	<tfc:wood/loom/pine>,
	<tfc:wood/loom/rosewood>,
	<tfc:wood/loom/sequoia>,
	<tfc:wood/loom/spruce>,
	<tfc:wood/loom/sycamore>,
	<tfc:wood/loom/white_cedar>,
	<tfc:wood/loom/willow>,
	<tfc:wood/loom/hevea>
];

// Таблица кирпичей (блок) для разных горных пород ТФК
global TFC_Bricks_Block as IItemStack[] = [
	<tfc:bricks/granite>,
	<tfc:bricks/diorite>,
	<tfc:bricks/gabbro>,
	<tfc:bricks/shale>,
	<tfc:bricks/claystone>,
	<tfc:bricks/rocksalt>,
	<tfc:bricks/limestone>,
	<tfc:bricks/conglomerate>,
	<tfc:bricks/dolomite>,
	<tfc:bricks/chert>,
	<tfc:bricks/chalk>,
	<tfc:bricks/rhyolite>,
	<tfc:bricks/basalt>,
	<tfc:bricks/andesite>,
	<tfc:bricks/dacite>,
	<tfc:bricks/quartzite>,
	<tfc:bricks/slate>,
	<tfc:bricks/phyllite>,
	<tfc:bricks/schist>,
	<tfc:bricks/gneiss>,
	<tfc:bricks/marble>
];

// Таблица саженцев из ТФК
global TFC_Saplings as IItemStack[] = [
	<tfc:wood/sapling/acacia>,
	<tfc:wood/sapling/ash>,
	<tfc:wood/sapling/aspen>,
	<tfc:wood/sapling/birch>,
	<tfc:wood/sapling/blackwood>,
	<tfc:wood/sapling/chestnut>,
	<tfc:wood/sapling/douglas_fir>,
	<tfc:wood/sapling/hickory>,
	<tfc:wood/sapling/kapok>,
	<tfc:wood/sapling/maple>,
	<tfc:wood/sapling/oak>,
	<tfc:wood/sapling/palm>,
	<tfc:wood/sapling/pine>,
	<tfc:wood/sapling/rosewood>,
	<tfc:wood/sapling/sequoia>,
	<tfc:wood/sapling/spruce>,
	<tfc:wood/sapling/sycamore>,
	<tfc:wood/sapling/white_cedar>,
	<tfc:wood/sapling/willow>,
	<tfc:wood/sapling/hevea>
];

// Таблица бревен из ТФК
global TFC_Logs as IItemStack[] = [
	<tfc:wood/log/acacia>,
	<tfc:wood/log/ash>,
	<tfc:wood/log/aspen>,
	<tfc:wood/log/birch>,
	<tfc:wood/log/blackwood>,
	<tfc:wood/log/chestnut>,
	<tfc:wood/log/douglas_fir>,
	<tfc:wood/log/hickory>,
	<tfc:wood/log/kapok>,
	<tfc:wood/log/maple>,
	<tfc:wood/log/oak>,
	<tfc:wood/log/palm>,
	<tfc:wood/log/pine>,
	<tfc:wood/log/rosewood>,
	<tfc:wood/log/sequoia>,
	<tfc:wood/log/spruce>,
	<tfc:wood/log/sycamore>,
	<tfc:wood/log/white_cedar>,
	<tfc:wood/log/willow>,
	<tfc:wood/log/hevea>
];

// Таблица досок из ТФК
global TFC_Planks as IItemStack[] = [
	<tfc:wood/planks/acacia>,
	<tfc:wood/planks/ash>,
	<tfc:wood/planks/aspen>,
	<tfc:wood/planks/birch>,
	<tfc:wood/planks/blackwood>,
	<tfc:wood/planks/chestnut>,
	<tfc:wood/planks/douglas_fir>,
	<tfc:wood/planks/hickory>,
	<tfc:wood/planks/kapok>,
	<tfc:wood/planks/maple>,
	<tfc:wood/planks/oak>,
	<tfc:wood/planks/palm>,
	<tfc:wood/planks/pine>,
	<tfc:wood/planks/rosewood>,
	<tfc:wood/planks/sequoia>,
	<tfc:wood/planks/spruce>,
	<tfc:wood/planks/sycamore>,
	<tfc:wood/planks/white_cedar>,
	<tfc:wood/planks/willow>,
	<tfc:wood/planks/hevea>
];

// Таблица пиломатериалов из ТФК
global TFC_Lumber as IItemStack[] = [
	<tfc:wood/lumber/acacia>,
	<tfc:wood/lumber/ash>,
	<tfc:wood/lumber/aspen>,
	<tfc:wood/lumber/birch>,
	<tfc:wood/lumber/blackwood>,
	<tfc:wood/lumber/chestnut>,
	<tfc:wood/lumber/douglas_fir>,
	<tfc:wood/lumber/hickory>,
	<tfc:wood/lumber/kapok>,
	<tfc:wood/lumber/maple>,
	<tfc:wood/lumber/oak>,
	<tfc:wood/lumber/palm>,
	<tfc:wood/lumber/pine>,
	<tfc:wood/lumber/rosewood>,
	<tfc:wood/lumber/sequoia>,
	<tfc:wood/lumber/spruce>,
	<tfc:wood/lumber/sycamore>,
	<tfc:wood/lumber/white_cedar>,
	<tfc:wood/lumber/willow>,
	<tfc:wood/lumber/hevea>
];

// Таблица полублоков из досок из ТФК
global TFC_Slabs as IItemStack[] = [
	<tfc:slab/wood/acacia>,
	<tfc:slab/wood/ash>,
	<tfc:slab/wood/aspen>,
	<tfc:slab/wood/birch>,
	<tfc:slab/wood/blackwood>,
	<tfc:slab/wood/chestnut>,
	<tfc:slab/wood/douglas_fir>,
	<tfc:slab/wood/hickory>,
	<tfc:slab/wood/kapok>,
	<tfc:slab/wood/maple>,
	<tfc:slab/wood/oak>,
	<tfc:slab/wood/palm>,
	<tfc:slab/wood/pine>,
	<tfc:slab/wood/rosewood>,
	<tfc:slab/wood/sequoia>,
	<tfc:slab/wood/spruce>,
	<tfc:slab/wood/sycamore>,
	<tfc:slab/wood/white_cedar>,
	<tfc:slab/wood/willow>,
	<tfc:slab/wood/hevea>
];

// Таблица лестниц из досок из ТФК
global TFC_Stairs as IItemStack[] = [
	<tfc:stairs/wood/acacia>,
	<tfc:stairs/wood/ash>,
	<tfc:stairs/wood/aspen>,
	<tfc:stairs/wood/birch>,
	<tfc:stairs/wood/blackwood>,
	<tfc:stairs/wood/chestnut>,
	<tfc:stairs/wood/douglas_fir>,
	<tfc:stairs/wood/hickory>,
	<tfc:stairs/wood/kapok>,
	<tfc:stairs/wood/maple>,
	<tfc:stairs/wood/oak>,
	<tfc:stairs/wood/palm>,
	<tfc:stairs/wood/pine>,
	<tfc:stairs/wood/rosewood>,
	<tfc:stairs/wood/sequoia>,
	<tfc:stairs/wood/spruce>,
	<tfc:stairs/wood/sycamore>,
	<tfc:stairs/wood/white_cedar>,
	<tfc:stairs/wood/willow>,
	<tfc:stairs/wood/hevea>
];

// Таблица нажимных плит из досок из ТФК
global TFC_Pressure_Plates as IItemStack[] = [
	<tfc:wood/pressure_plate/acacia>,
	<tfc:wood/pressure_plate/ash>,
	<tfc:wood/pressure_plate/aspen>,
	<tfc:wood/pressure_plate/birch>,
	<tfc:wood/pressure_plate/blackwood>,
	<tfc:wood/pressure_plate/chestnut>,
	<tfc:wood/pressure_plate/douglas_fir>,
	<tfc:wood/pressure_plate/hickory>,
	<tfc:wood/pressure_plate/kapok>,
	<tfc:wood/pressure_plate/maple>,
	<tfc:wood/pressure_plate/oak>,
	<tfc:wood/pressure_plate/palm>,
	<tfc:wood/pressure_plate/pine>,
	<tfc:wood/pressure_plate/rosewood>,
	<tfc:wood/pressure_plate/sequoia>,
	<tfc:wood/pressure_plate/spruce>,
	<tfc:wood/pressure_plate/sycamore>,
	<tfc:wood/pressure_plate/white_cedar>,
	<tfc:wood/pressure_plate/willow>,
	<minecraft:wooden_pressure_plate>
];

// Таблица кнопок из досок из ТФК
global TFC_Buttons as IItemStack[] = [
	<tfc:wood/button/acacia>,
	<tfc:wood/button/ash>,
	<tfc:wood/button/aspen>,
	<tfc:wood/button/birch>,
	<tfc:wood/button/blackwood>,
	<tfc:wood/button/chestnut>,
	<tfc:wood/button/douglas_fir>,
	<tfc:wood/button/hickory>,
	<tfc:wood/button/kapok>,
	<tfc:wood/button/maple>,
	<tfc:wood/button/oak>,
	<tfc:wood/button/palm>,
	<tfc:wood/button/pine>,
	<tfc:wood/button/rosewood>,
	<tfc:wood/button/sequoia>,
	<tfc:wood/button/spruce>,
	<tfc:wood/button/sycamore>,
	<tfc:wood/button/white_cedar>,
	<tfc:wood/button/willow>,
	<tfc:wood/button/hevea>
];

// Таблица дверей из досок из ТФК
global TFC_Doors as IItemStack[] = [
	<tfc:wood/door/acacia>,
	<tfc:wood/door/ash>,
	<tfc:wood/door/aspen>,
	<tfc:wood/door/birch>,
	<tfc:wood/door/blackwood>,
	<tfc:wood/door/chestnut>,
	<tfc:wood/door/douglas_fir>,
	<tfc:wood/door/hickory>,
	<tfc:wood/door/kapok>,
	<tfc:wood/door/maple>,
	<tfc:wood/door/oak>,
	<tfc:wood/door/palm>,
	<tfc:wood/door/pine>,
	<tfc:wood/door/rosewood>,
	<tfc:wood/door/sequoia>,
	<tfc:wood/door/spruce>,
	<tfc:wood/door/sycamore>,
	<tfc:wood/door/white_cedar>,
	<tfc:wood/door/willow>,
	<tfc:wood/door/hevea>
];

// Таблица люков из досок из ТФК
global TFC_Trapdoors as IItemStack[] = [
	<tfc:wood/trapdoor/acacia>,
	<tfc:wood/trapdoor/ash>,
	<tfc:wood/trapdoor/aspen>,
	<tfc:wood/trapdoor/birch>,
	<tfc:wood/trapdoor/blackwood>,
	<tfc:wood/trapdoor/chestnut>,
	<tfc:wood/trapdoor/douglas_fir>,
	<tfc:wood/trapdoor/hickory>,
	<tfc:wood/trapdoor/kapok>,
	<tfc:wood/trapdoor/maple>,
	<tfc:wood/trapdoor/oak>,
	<tfc:wood/trapdoor/palm>,
	<tfc:wood/trapdoor/pine>,
	<tfc:wood/trapdoor/rosewood>,
	<tfc:wood/trapdoor/sequoia>,
	<tfc:wood/trapdoor/spruce>,
	<tfc:wood/trapdoor/sycamore>,
	<tfc:wood/trapdoor/white_cedar>,
	<tfc:wood/trapdoor/willow>,
	<tfc:wood/trapdoor/hevea>
];

// Таблица опор из досок из ТФК
global TFC_Supports as IItemStack[] = [
	<tfc:wood/support/acacia>,
	<tfc:wood/support/ash>,
	<tfc:wood/support/aspen>,
	<tfc:wood/support/birch>,
	<tfc:wood/support/blackwood>,
	<tfc:wood/support/chestnut>,
	<tfc:wood/support/douglas_fir>,
	<tfc:wood/support/hickory>,
	<tfc:wood/support/kapok>,
	<tfc:wood/support/maple>,
	<tfc:wood/support/oak>,
	<tfc:wood/support/palm>,
	<tfc:wood/support/pine>,
	<tfc:wood/support/rosewood>,
	<tfc:wood/support/sequoia>,
	<tfc:wood/support/spruce>,
	<tfc:wood/support/sycamore>,
	<tfc:wood/support/white_cedar>,
	<tfc:wood/support/willow>,
	<tfc:wood/support/hevea>
];

// Таблица заборов из досок из ТФК
global TFC_Fences as IItemStack[] = [
	<tfc:wood/fence/acacia>,
	<tfc:wood/fence/ash>,
	<tfc:wood/fence/aspen>,
	<tfc:wood/fence/birch>,
	<tfc:wood/fence/blackwood>,
	<tfc:wood/fence/chestnut>,
	<tfc:wood/fence/douglas_fir>,
	<tfc:wood/fence/hickory>,
	<tfc:wood/fence/kapok>,
	<tfc:wood/fence/maple>,
	<tfc:wood/fence/oak>,
	<tfc:wood/fence/palm>,
	<tfc:wood/fence/pine>,
	<tfc:wood/fence/rosewood>,
	<tfc:wood/fence/sequoia>,
	<tfc:wood/fence/spruce>,
	<tfc:wood/fence/sycamore>,
	<tfc:wood/fence/white_cedar>,
	<tfc:wood/fence/willow>,
	<tfc:wood/fence/hevea>
];

// Таблица калиток из досок из ТФК
global TFC_Fence_Gates as IItemStack[] = [
	<tfc:wood/fence_gate/acacia>,
	<tfc:wood/fence_gate/ash>,
	<tfc:wood/fence_gate/aspen>,
	<tfc:wood/fence_gate/birch>,
	<tfc:wood/fence_gate/blackwood>,
	<tfc:wood/fence_gate/chestnut>,
	<tfc:wood/fence_gate/douglas_fir>,
	<tfc:wood/fence_gate/hickory>,
	<tfc:wood/fence_gate/kapok>,
	<tfc:wood/fence_gate/maple>,
	<tfc:wood/fence_gate/oak>,
	<tfc:wood/fence_gate/palm>,
	<tfc:wood/fence_gate/pine>,
	<tfc:wood/fence_gate/rosewood>,
	<tfc:wood/fence_gate/sequoia>,
	<tfc:wood/fence_gate/spruce>,
	<tfc:wood/fence_gate/sycamore>,
	<tfc:wood/fence_gate/white_cedar>,
	<tfc:wood/fence_gate/willow>,
	<tfc:wood/fence_gate/hevea>
];

// Таблица семян из ТФК
global All_Seeds as IItemStack[] = [
	<tfc:crop/seeds/barley>,
	<tfc:crop/seeds/maize>,
	<tfc:crop/seeds/oat>,
	<tfc:crop/seeds/rice>,
	<tfc:crop/seeds/rye>,
	<tfc:crop/seeds/wheat>,
	<tfc:crop/seeds/beet>,
	<tfc:crop/seeds/cabbage>,
	<tfc:crop/seeds/carrot>,
	<tfc:crop/seeds/garlic>,
	<tfc:crop/seeds/green_bean>,
	<tfc:crop/seeds/onion>,
	<tfc:crop/seeds/potato>,
	<tfc:crop/seeds/soybean>,
	<tfc:crop/seeds/squash>,
	<tfc:crop/seeds/sugarcane>,
	<tfc:crop/seeds/tomato>,
	<tfc:crop/seeds/red_bell_pepper>,
	<tfc:crop/seeds/yellow_bell_pepper>,
	<tfc:crop/seeds/jute>
];

// Таблица продукции из семян из ТФК
global All_Plants as IItemStack[] = [
	<tfc:food/barley>,
	<tfc:food/maize>,
	<tfc:food/oat>,
	<tfc:food/rice>,
	<tfc:food/rye>,
	<tfc:food/wheat>,
	<tfc:food/beet>,
	<tfc:food/cabbage>,
	<tfc:food/carrot>,
	<tfc:food/garlic>,
	<tfc:food/green_bean>,
	<tfc:food/onion>,
	<tfc:food/potato>,
	<tfc:food/soybean>,
	<tfc:food/squash>,
	<tfc:food/sugarcane>,
	<tfc:food/tomato>,
	<tfc:food/red_bell_pepper>,
	<tfc:food/yellow_bell_pepper>,
	<tfc:crop/product/jute>
];

// Таблица панелей стекла
global Glass_Panes as IItemStack[] = [
    <minecraft:stained_glass_pane>,
    <minecraft:stained_glass_pane:1>,
    <minecraft:stained_glass_pane:2>,
    <minecraft:stained_glass_pane:3>,
    <minecraft:stained_glass_pane:4>,
    <minecraft:stained_glass_pane:5>,
    <minecraft:stained_glass_pane:6>,
    <minecraft:stained_glass_pane:7>,
    <minecraft:stained_glass_pane:8>,
    <minecraft:stained_glass_pane:9>,
    <minecraft:stained_glass_pane:10>,
    <minecraft:stained_glass_pane:11>,
    <minecraft:stained_glass_pane:12>,
    <minecraft:stained_glass_pane:13>,
    <minecraft:stained_glass_pane:14>,
    <minecraft:stained_glass_pane:15>
];

// Таблица жидких красителей
global All_Liquid_Dyes as ILiquidStack[] = [
	<liquid:dye_white>,
	<liquid:dye_orange>,
	<liquid:dye_magenta>,
	<liquid:dye_light_blue>,
	<liquid:dye_yellow>,
	<liquid:dye_lime>,
	<liquid:dye_pink>,
	<liquid:dye_gray>,
	<liquid:dye_light_gray>,
	<liquid:dye_cyan>,
	<liquid:dye_purple>,
	<liquid:dye_blue>,
	<liquid:dye_brown>,
	<liquid:dye_green>,
	<liquid:dye_red>,
	<liquid:dye_black>
];

// Таблица всех пластин из грега 
global GTPlates as IItemStack[] = [
	<gregtech:meta_plate:2>,
	<gregtech:meta_plate:3>,
	<gregtech:meta_plate:10>,
	<gregtech:meta_plate:11>,
	<gregtech:meta_plate:22>,
	<gregtech:meta_plate:23>,
	<gregtech:meta_plate:25>,
	<gregtech:meta_plate:27>,
	<gregtech:meta_plate:33>,
	<gregtech:meta_plate:39>,
	<gregtech:meta_plate:41>,
	<gregtech:meta_plate:50>,
	<gregtech:meta_plate:51>,
	<gregtech:meta_plate:55>,
	<gregtech:meta_plate:61>,
	<gregtech:meta_plate:64>,
	<gregtech:meta_plate:66>,
	<gregtech:meta_plate:69>,
	<gregtech:meta_plate:75>,
	<gregtech:meta_plate:77>,
	<gregtech:meta_plate:80>,
	<gregtech:meta_plate:82>,
	<gregtech:meta_plate:90>,
	<gregtech:meta_plate:93>,
	<gregtech:meta_plate:99>,
	<gregtech:meta_plate:100>,
	<gregtech:meta_plate:104>,
	<gregtech:meta_plate:109>,
	<gregtech:meta_plate:112>,
	<gregtech:meta_plate:113>,
	<gregtech:meta_plate:115>,
	<gregtech:meta_plate:116>,
	<gregtech:meta_plate:117>,
	<gregtech:meta_plate:122>,
	<gregtech:meta_plate:124>,
	<gregtech:meta_plate:125>,
	<gregtech:meta_plate:126>,
	<gregtech:meta_plate:127>,
	<gregtech:meta_plate:128>,
	<gregtech:meta_plate:129>,
	<gregtech:meta_plate:130>,
	<gregtech:meta_plate:214>,
	<gregtech:meta_plate:252>,
	<gregtech:meta_plate:256>,
	<gregtech:meta_plate:257>,
	<gregtech:meta_plate:259>,
	<gregtech:meta_plate:260>,
	<gregtech:meta_plate:274>,
	<gregtech:meta_plate:276>,
	<gregtech:meta_plate:277>,
	<gregtech:meta_plate:278>,
	<gregtech:meta_plate:281>,
	<gregtech:meta_plate:287>,
	<gregtech:meta_plate:288>,
	<gregtech:meta_plate:289>,
	<gregtech:meta_plate:290>,
	<gregtech:meta_plate:294>,
	<gregtech:meta_plate:295>,
	<gregtech:meta_plate:296>,
	<gregtech:meta_plate:297>,
	<gregtech:meta_plate:300>,
	<gregtech:meta_plate:301>,
	<gregtech:meta_plate:302>,
	<gregtech:meta_plate:303>,
	<gregtech:meta_plate:310>,
	<gregtech:meta_plate:311>,
	<gregtech:meta_plate:314>,
	<gregtech:meta_plate:316>,
	<gregtech:meta_plate:323>,
	<gregtech:meta_plate:324>,
	<gregtech:meta_plate:328>,
	<gregtech:meta_plate:329>,
	<gregtech:meta_plate:331>,
	<gregtech:meta_plate:334>,
	<gregtech:meta_plate:335>,
	<gregtech:meta_plate:338>,
	<gregtech:meta_plate:339>,
	<gregtech:meta_plate:340>,
	<gregtech:meta_plate:342>,
	<gregtech:meta_plate:344>,
	<gregtech:meta_plate:351>,
	<gregtech:meta_plate:354>,
	<gregtech:meta_plate:396>,
	<gregtech:meta_plate:416>,
	<gregtech:meta_plate:429>,
	<gregtech:meta_plate:430>,
	<gregtech:meta_plate:431>,
	<gregtech:meta_plate:1074>,
	<gregtech:meta_plate:1599>,
	<gregtech:meta_plate:1601>,
	<gregtech:meta_plate:1602>,
	<gregtech:meta_plate:2004>,
	<gregtech:meta_plate:2005>,
	<gregtech:meta_plate:2006>,
	<gregtech:meta_plate:2007>,
	<gregtech:meta_plate:2011>,
	<gregtech:meta_plate:2012>,
	<gregtech:meta_plate:2013>,
	<gregtech:meta_plate:2014>,
	<gregtech:meta_plate:2016>,
	<gregtech:meta_plate:2036>,
	<gregtech:meta_plate:2037>,
	<gregtech:meta_plate:2042>,
	<gregtech:meta_plate:2062>,
	<gregtech:meta_plate:2064>,
	<gregtech:meta_plate:2510>,
	<gregtech:meta_plate:2511>,
	<gregtech:meta_plate:2516>,
	<gregtech:meta_plate:2517>,
	<gregtech:meta_plate:2519>,
	<gregtech:meta_plate:2520>,
	<gregtech:meta_plate:2527>,
	<gregtech:meta_plate:3000>,
	<gregtech:meta_plate:3001>,
	<gregtech:meta_plate:3002>,
	<gregtech:meta_plate:3003>,
	<gregtech:meta_plate:3004>,
	<gregtech:meta_plate:3005>,
	<gregtech:meta_plate:3006>,
	<gregtech:meta_plate:3007>,
	<gregtech:meta_plate:3008>,
	<gregtech:meta_plate:3009>,
	<gregtech:meta_plate:3020>,
	<gregtech:meta_plate:3021>,
	<gregtech:meta_plate:3022>
];

// Удаление крафта из верстака всех пластин из грега
for item in GTPlates{
    recipes.remove(item);
}

// Таблица всех двойных пластин из грега 
global GTDoublePlates as IItemStack[] = [
	<gregtech:meta_plate_double:2>,
	<gregtech:meta_plate_double:3>,
	<gregtech:meta_plate_double:10>,
	<gregtech:meta_plate_double:11>,
	<gregtech:meta_plate_double:22>,
	<gregtech:meta_plate_double:23>,
	<gregtech:meta_plate_double:25>,
	<gregtech:meta_plate_double:27>,
	<gregtech:meta_plate_double:33>,
	<gregtech:meta_plate_double:39>,
	<gregtech:meta_plate_double:41>,
	<gregtech:meta_plate_double:50>,
	<gregtech:meta_plate_double:51>,
	<gregtech:meta_plate_double:55>,
	<gregtech:meta_plate_double:61>,
	<gregtech:meta_plate_double:64>,
	<gregtech:meta_plate_double:66>,
	<gregtech:meta_plate_double:69>,
	<gregtech:meta_plate_double:75>,
	<gregtech:meta_plate_double:77>,
	<gregtech:meta_plate_double:80>,
	<gregtech:meta_plate_double:82>,
	<gregtech:meta_plate_double:90>,
	<gregtech:meta_plate_double:93>,
	<gregtech:meta_plate_double:99>,
	<gregtech:meta_plate_double:100>,
	<gregtech:meta_plate_double:104>,
	<gregtech:meta_plate_double:109>,
	<gregtech:meta_plate_double:112>,
	<gregtech:meta_plate_double:113>,
	<gregtech:meta_plate_double:115>,
	<gregtech:meta_plate_double:116>,
	<gregtech:meta_plate_double:117>,
	<gregtech:meta_plate_double:122>,
	<gregtech:meta_plate_double:124>,
	<gregtech:meta_plate_double:125>,
	<gregtech:meta_plate_double:126>,
	<gregtech:meta_plate_double:127>,
	<gregtech:meta_plate_double:128>,
	<gregtech:meta_plate_double:129>,
	<gregtech:meta_plate_double:130>,
	<gregtech:meta_plate_double:252>,
	<gregtech:meta_plate_double:256>,
	<gregtech:meta_plate_double:259>,
	<gregtech:meta_plate_double:260>,
	<gregtech:meta_plate_double:274>,
	<gregtech:meta_plate_double:277>,
	<gregtech:meta_plate_double:287>,
	<gregtech:meta_plate_double:288>,
	<gregtech:meta_plate_double:290>,
	<gregtech:meta_plate_double:294>,
	<gregtech:meta_plate_double:295>,
	<gregtech:meta_plate_double:296>,
	<gregtech:meta_plate_double:300>,
	<gregtech:meta_plate_double:301>,
	<gregtech:meta_plate_double:302>,
	<gregtech:meta_plate_double:303>,
	<gregtech:meta_plate_double:310>,
	<gregtech:meta_plate_double:323>,
	<gregtech:meta_plate_double:324>,
	<gregtech:meta_plate_double:328>,
	<gregtech:meta_plate_double:331>,
	<gregtech:meta_plate_double:334>,
	<gregtech:meta_plate_double:335>,
	<gregtech:meta_plate_double:338>,
	<gregtech:meta_plate_double:344>,
	<gregtech:meta_plate_double:351>,
	<gregtech:meta_plate_double:354>,
	<gregtech:meta_plate_double:396>,
	<gregtech:meta_plate_double:429>,
	<gregtech:meta_plate_double:430>,
	<gregtech:meta_plate_double:431>,
	<gregtech:meta_plate_double:1008>,
	<gregtech:meta_plate_double:1074>,
	<gregtech:meta_plate_double:2011>,
	<gregtech:meta_plate_double:2012>,
	<gregtech:meta_plate_double:2013>,
	<gregtech:meta_plate_double:2014>,
	<gregtech:meta_plate_double:2036>,
	<gregtech:meta_plate_double:2037>,
	<gregtech:meta_plate_double:2042>,
	<gregtech:meta_plate_double:2062>,
	<gregtech:meta_plate_double:2510>,
	<gregtech:meta_plate_double:2511>,
	<gregtech:meta_plate_double:2516>,
	<gregtech:meta_plate_double:2517>,
	<gregtech:meta_plate_double:2519>,
	<gregtech:meta_plate_double:2520>,
	<gregtech:meta_plate_double:2527>,
	<gregtech:meta_plate_double:3000>,
	<gregtech:meta_plate_double:3001>,
	<gregtech:meta_plate_double:3002>,
	<gregtech:meta_plate_double:3003>,
	<gregtech:meta_plate_double:3004>,
	<gregtech:meta_plate_double:3005>,
	<gregtech:meta_plate_double:3006>,
	<gregtech:meta_plate_double:3007>,
	<gregtech:meta_plate_double:3008>,
	<gregtech:meta_plate_double:3009>,
	<gregtech:meta_plate_double:3020>,
	<gregtech:meta_plate_double:3021>,
	<gregtech:meta_plate_double:3022>
];

// Удаление крафта из верстака всех двойных пластин из грега
for item in GTDoublePlates{
    recipes.remove(item);
}

// Таблица всех кайло для кирок из грега 
global GTtoolHeadPickaxe as IItemStack[] = [
	<gregtech:meta_tool_head_pickaxe:2>,
	<gregtech:meta_tool_head_pickaxe:22>,
	<gregtech:meta_tool_head_pickaxe:23>,
	<gregtech:meta_tool_head_pickaxe:50>,
	<gregtech:meta_tool_head_pickaxe:51>,
	<gregtech:meta_tool_head_pickaxe:61>,
	<gregtech:meta_tool_head_pickaxe:64>,
	<gregtech:meta_tool_head_pickaxe:66>,
	<gregtech:meta_tool_head_pickaxe:75>,
	<gregtech:meta_tool_head_pickaxe:77>,
	<gregtech:meta_tool_head_pickaxe:109>,
	<gregtech:meta_tool_head_pickaxe:113>,
	<gregtech:meta_tool_head_pickaxe:115>,
	<gregtech:meta_tool_head_pickaxe:116>,
	<gregtech:meta_tool_head_pickaxe:117>,
	<gregtech:meta_tool_head_pickaxe:124>,
	<gregtech:meta_tool_head_pickaxe:125>,
	<gregtech:meta_tool_head_pickaxe:127>,
	<gregtech:meta_tool_head_pickaxe:128>,
	<gregtech:meta_tool_head_pickaxe:129>,
	<gregtech:meta_tool_head_pickaxe:257>,
	<gregtech:meta_tool_head_pickaxe:259>,
	<gregtech:meta_tool_head_pickaxe:260>,
	<gregtech:meta_tool_head_pickaxe:276>,
	<gregtech:meta_tool_head_pickaxe:278>,
	<gregtech:meta_tool_head_pickaxe:281>,
	<gregtech:meta_tool_head_pickaxe:287>,
	<gregtech:meta_tool_head_pickaxe:290>,
	<gregtech:meta_tool_head_pickaxe:300>,
	<gregtech:meta_tool_head_pickaxe:301>,
	<gregtech:meta_tool_head_pickaxe:302>,
	<gregtech:meta_tool_head_pickaxe:303>,
	<gregtech:meta_tool_head_pickaxe:311>,
	<gregtech:meta_tool_head_pickaxe:314>,
	<gregtech:meta_tool_head_pickaxe:323>,
	<gregtech:meta_tool_head_pickaxe:324>,
	<gregtech:meta_tool_head_pickaxe:329>,
	<gregtech:meta_tool_head_pickaxe:331>,
	<gregtech:meta_tool_head_pickaxe:335>,
	<gregtech:meta_tool_head_pickaxe:344>,
	<gregtech:meta_tool_head_pickaxe:396>,
	<gregtech:meta_tool_head_pickaxe:2004>,
	<gregtech:meta_tool_head_pickaxe:2005>,
	<gregtech:meta_tool_head_pickaxe:2006>,
	<gregtech:meta_tool_head_pickaxe:2011>,
	<gregtech:meta_tool_head_pickaxe:2012>,
	<gregtech:meta_tool_head_pickaxe:2013>,
	<gregtech:meta_tool_head_pickaxe:2014>,
	<gregtech:meta_tool_head_pickaxe:2016>,
	<gregtech:meta_tool_head_pickaxe:2017>,
	<gregtech:meta_tool_head_pickaxe:2036>,
	<gregtech:meta_tool_head_pickaxe:2042>,
	<gregtech:meta_tool_head_pickaxe:2049>,
	<gregtech:meta_tool_head_pickaxe:2062>,
	<gregtech:meta_tool_head_pickaxe:2510>,
	<gregtech:meta_tool_head_pickaxe:2511>,
	<gregtech:meta_tool_head_pickaxe:2516>,
	<gregtech:meta_tool_head_pickaxe:2519>,
	<gregtech:meta_tool_head_pickaxe:2520>
];

// Удаление крафта из верстака всех кайло для кирок из грега
for item in GTtoolHeadPickaxe{
    recipes.remove(item);
}

// Таблица всех бойков для молотов из грега 
global GTtoolHeadHammer as IItemStack[] = [
	<gregtech:meta_tool_head_hammer:2>,
	<gregtech:meta_tool_head_hammer:22>,
	<gregtech:meta_tool_head_hammer:23>,
	<gregtech:meta_tool_head_hammer:50>,
	<gregtech:meta_tool_head_hammer:51>,
	<gregtech:meta_tool_head_hammer:61>,
	<gregtech:meta_tool_head_hammer:64>,
	<gregtech:meta_tool_head_hammer:66>,
	<gregtech:meta_tool_head_hammer:75>,
	<gregtech:meta_tool_head_hammer:77>,
	<gregtech:meta_tool_head_hammer:109>,
	<gregtech:meta_tool_head_hammer:113>,
	<gregtech:meta_tool_head_hammer:115>,
	<gregtech:meta_tool_head_hammer:116>,
	<gregtech:meta_tool_head_hammer:117>,
	<gregtech:meta_tool_head_hammer:124>,
	<gregtech:meta_tool_head_hammer:125>,
	<gregtech:meta_tool_head_hammer:127>,
	<gregtech:meta_tool_head_hammer:128>,
	<gregtech:meta_tool_head_hammer:129>,
	<gregtech:meta_tool_head_hammer:257>,
	<gregtech:meta_tool_head_hammer:259>,
	<gregtech:meta_tool_head_hammer:260>,
	<gregtech:meta_tool_head_hammer:276>,
	<gregtech:meta_tool_head_hammer:278>,
	<gregtech:meta_tool_head_hammer:281>,
	<gregtech:meta_tool_head_hammer:287>,
	<gregtech:meta_tool_head_hammer:290>,
	<gregtech:meta_tool_head_hammer:300>,
	<gregtech:meta_tool_head_hammer:301>,
	<gregtech:meta_tool_head_hammer:302>,
	<gregtech:meta_tool_head_hammer:303>,
	<gregtech:meta_tool_head_hammer:311>,
	<gregtech:meta_tool_head_hammer:314>,
	<gregtech:meta_tool_head_hammer:323>,
	<gregtech:meta_tool_head_hammer:324>,
	<gregtech:meta_tool_head_hammer:329>,
	<gregtech:meta_tool_head_hammer:331>,
	<gregtech:meta_tool_head_hammer:335>,
	<gregtech:meta_tool_head_hammer:344>,
	<gregtech:meta_tool_head_hammer:396>,
	<gregtech:meta_tool_head_hammer:2004>,
	<gregtech:meta_tool_head_hammer:2005>,
	<gregtech:meta_tool_head_hammer:2006>,
	<gregtech:meta_tool_head_hammer:2011>,
	<gregtech:meta_tool_head_hammer:2012>,
	<gregtech:meta_tool_head_hammer:2013>,
	<gregtech:meta_tool_head_hammer:2014>,
	<gregtech:meta_tool_head_hammer:2016>,
	<gregtech:meta_tool_head_hammer:2017>,
	<gregtech:meta_tool_head_hammer:2036>,
	<gregtech:meta_tool_head_hammer:2042>,
	<gregtech:meta_tool_head_hammer:2062>,
	<gregtech:meta_tool_head_hammer:2510>,
	<gregtech:meta_tool_head_hammer:2511>,
	<gregtech:meta_tool_head_hammer:2516>,
	<gregtech:meta_tool_head_hammer:2519>,
	<gregtech:meta_tool_head_hammer:2520>
];

// Удаление крафта из верстака всех бойков для молотов из грега
for item in GTtoolHeadHammer{
    recipes.remove(item);
}

// Таблица всех лезвий для пил из грега 
global GTtoolHeadSaw as IItemStack[] = [
	<gregtech:meta_tool_head_saw:2>,
	<gregtech:meta_tool_head_saw:22>,
	<gregtech:meta_tool_head_saw:23>,
	<gregtech:meta_tool_head_saw:50>,
	<gregtech:meta_tool_head_saw:51>,
	<gregtech:meta_tool_head_saw:61>,
	<gregtech:meta_tool_head_saw:64>,
	<gregtech:meta_tool_head_saw:66>,
	<gregtech:meta_tool_head_saw:75>,
	<gregtech:meta_tool_head_saw:77>,
	<gregtech:meta_tool_head_saw:109>,
	<gregtech:meta_tool_head_saw:113>,
	<gregtech:meta_tool_head_saw:115>,
	<gregtech:meta_tool_head_saw:116>,
	<gregtech:meta_tool_head_saw:117>,
	<gregtech:meta_tool_head_saw:124>,
	<gregtech:meta_tool_head_saw:125>,
	<gregtech:meta_tool_head_saw:127>,
	<gregtech:meta_tool_head_saw:128>,
	<gregtech:meta_tool_head_saw:129>,
	<gregtech:meta_tool_head_saw:257>,
	<gregtech:meta_tool_head_saw:259>,
	<gregtech:meta_tool_head_saw:260>,
	<gregtech:meta_tool_head_saw:276>,
	<gregtech:meta_tool_head_saw:278>,
	<gregtech:meta_tool_head_saw:281>,
	<gregtech:meta_tool_head_saw:287>,
	<gregtech:meta_tool_head_saw:290>,
	<gregtech:meta_tool_head_saw:300>,
	<gregtech:meta_tool_head_saw:301>,
	<gregtech:meta_tool_head_saw:302>,
	<gregtech:meta_tool_head_saw:303>,
	<gregtech:meta_tool_head_saw:311>,
	<gregtech:meta_tool_head_saw:314>,
	<gregtech:meta_tool_head_saw:323>,
	<gregtech:meta_tool_head_saw:324>,
	<gregtech:meta_tool_head_saw:329>,
	<gregtech:meta_tool_head_saw:331>,
	<gregtech:meta_tool_head_saw:335>,
	<gregtech:meta_tool_head_saw:344>,
	<gregtech:meta_tool_head_saw:396>,
	<gregtech:meta_tool_head_saw:2004>,
	<gregtech:meta_tool_head_saw:2005>,
	<gregtech:meta_tool_head_saw:2006>,
	<gregtech:meta_tool_head_saw:2011>,
	<gregtech:meta_tool_head_saw:2012>,
	<gregtech:meta_tool_head_saw:2013>,
	<gregtech:meta_tool_head_saw:2014>,
	<gregtech:meta_tool_head_saw:2016>,
	<gregtech:meta_tool_head_saw:2017>,
	<gregtech:meta_tool_head_saw:2036>,
	<gregtech:meta_tool_head_saw:2042>,
	<gregtech:meta_tool_head_saw:2062>,
	<gregtech:meta_tool_head_saw:2510>,
	<gregtech:meta_tool_head_saw:2511>,
	<gregtech:meta_tool_head_saw:2516>,
	<gregtech:meta_tool_head_saw:2519>,
	<gregtech:meta_tool_head_saw:2520>
];

// Удаление крафта из верстака всех лезвий для пил из грега
for item in GTtoolHeadSaw{
    recipes.remove(item);
}

// Таблица всех оголовий напильков из грега 
global GTtoolHeadFile as IItemStack[] = [
	<gregtech:meta_tool_head_file:2>,
	<gregtech:meta_tool_head_file:22>,
	<gregtech:meta_tool_head_file:23>,
	<gregtech:meta_tool_head_file:50>,
	<gregtech:meta_tool_head_file:51>,
	<gregtech:meta_tool_head_file:61>,
	<gregtech:meta_tool_head_file:64>,
	<gregtech:meta_tool_head_file:66>,
	<gregtech:meta_tool_head_file:75>,
	<gregtech:meta_tool_head_file:77>,
	<gregtech:meta_tool_head_file:109>,
	<gregtech:meta_tool_head_file:113>,
	<gregtech:meta_tool_head_file:115>,
	<gregtech:meta_tool_head_file:116>,
	<gregtech:meta_tool_head_file:117>,
	<gregtech:meta_tool_head_file:124>,
	<gregtech:meta_tool_head_file:125>,
	<gregtech:meta_tool_head_file:127>,
	<gregtech:meta_tool_head_file:128>,
	<gregtech:meta_tool_head_file:129>,
	<gregtech:meta_tool_head_file:257>,
	<gregtech:meta_tool_head_file:259>,
	<gregtech:meta_tool_head_file:260>,
	<gregtech:meta_tool_head_file:276>,
	<gregtech:meta_tool_head_file:278>,
	<gregtech:meta_tool_head_file:281>,
	<gregtech:meta_tool_head_file:287>,
	<gregtech:meta_tool_head_file:290>,
	<gregtech:meta_tool_head_file:300>,
	<gregtech:meta_tool_head_file:301>,
	<gregtech:meta_tool_head_file:302>,
	<gregtech:meta_tool_head_file:303>,
	<gregtech:meta_tool_head_file:311>,
	<gregtech:meta_tool_head_file:314>,
	<gregtech:meta_tool_head_file:323>,
	<gregtech:meta_tool_head_file:324>,
	<gregtech:meta_tool_head_file:329>,
	<gregtech:meta_tool_head_file:331>,
	<gregtech:meta_tool_head_file:335>,
	<gregtech:meta_tool_head_file:344>,
	<gregtech:meta_tool_head_file:396>,
	<gregtech:meta_tool_head_file:2004>,
	<gregtech:meta_tool_head_file:2005>,
	<gregtech:meta_tool_head_file:2006>,
	<gregtech:meta_tool_head_file:2011>,
	<gregtech:meta_tool_head_file:2012>,
	<gregtech:meta_tool_head_file:2013>,
	<gregtech:meta_tool_head_file:2014>,
	<gregtech:meta_tool_head_file:2016>,
	<gregtech:meta_tool_head_file:2017>,
	<gregtech:meta_tool_head_file:2036>,
	<gregtech:meta_tool_head_file:2042>,
	<gregtech:meta_tool_head_file:2062>,
	<gregtech:meta_tool_head_file:2510>,
	<gregtech:meta_tool_head_file:2511>,
	<gregtech:meta_tool_head_file:2516>,
	<gregtech:meta_tool_head_file:2519>,
	<gregtech:meta_tool_head_file:2520>
];

// Удаление крафта из верстака всех оголовий напильников из грега
for item in GTtoolHeadFile{
    recipes.remove(item);
}

// Таблица всех оголовий лопат из грега 
global GTtoolHeadShovel as IItemStack[] = [
	<gregtech:meta_tool_head_shovel:2>,
	<gregtech:meta_tool_head_shovel:22>,
	<gregtech:meta_tool_head_shovel:23>,
	<gregtech:meta_tool_head_shovel:50>,
	<gregtech:meta_tool_head_shovel:51>,
	<gregtech:meta_tool_head_shovel:61>,
	<gregtech:meta_tool_head_shovel:64>,
	<gregtech:meta_tool_head_shovel:66>,
	<gregtech:meta_tool_head_shovel:75>,
	<gregtech:meta_tool_head_shovel:77>,
	<gregtech:meta_tool_head_shovel:109>,
	<gregtech:meta_tool_head_shovel:113>,
	<gregtech:meta_tool_head_shovel:115>,
	<gregtech:meta_tool_head_shovel:116>,
	<gregtech:meta_tool_head_shovel:117>,
	<gregtech:meta_tool_head_shovel:124>,
	<gregtech:meta_tool_head_shovel:125>,
	<gregtech:meta_tool_head_shovel:127>,
	<gregtech:meta_tool_head_shovel:128>,
	<gregtech:meta_tool_head_shovel:129>,
	<gregtech:meta_tool_head_shovel:257>,
	<gregtech:meta_tool_head_shovel:259>,
	<gregtech:meta_tool_head_shovel:260>,
	<gregtech:meta_tool_head_shovel:276>,
	<gregtech:meta_tool_head_shovel:278>,
	<gregtech:meta_tool_head_shovel:281>,
	<gregtech:meta_tool_head_shovel:287>,
	<gregtech:meta_tool_head_shovel:290>,
	<gregtech:meta_tool_head_shovel:300>,
	<gregtech:meta_tool_head_shovel:301>,
	<gregtech:meta_tool_head_shovel:302>,
	<gregtech:meta_tool_head_shovel:303>,
	<gregtech:meta_tool_head_shovel:311>,
	<gregtech:meta_tool_head_shovel:314>,
	<gregtech:meta_tool_head_shovel:323>,
	<gregtech:meta_tool_head_shovel:324>,
	<gregtech:meta_tool_head_shovel:329>,
	<gregtech:meta_tool_head_shovel:331>,
	<gregtech:meta_tool_head_shovel:335>,
	<gregtech:meta_tool_head_shovel:344>,
	<gregtech:meta_tool_head_shovel:396>,
	<gregtech:meta_tool_head_shovel:2004>,
	<gregtech:meta_tool_head_shovel:2005>,
	<gregtech:meta_tool_head_shovel:2006>,
	<gregtech:meta_tool_head_shovel:2011>,
	<gregtech:meta_tool_head_shovel:2012>,
	<gregtech:meta_tool_head_shovel:2013>,
	<gregtech:meta_tool_head_shovel:2014>,
	<gregtech:meta_tool_head_shovel:2016>,
	<gregtech:meta_tool_head_shovel:2017>,
	<gregtech:meta_tool_head_shovel:2036>,
	<gregtech:meta_tool_head_shovel:2042>,
	<gregtech:meta_tool_head_shovel:2049>,
	<gregtech:meta_tool_head_shovel:2062>,
	<gregtech:meta_tool_head_shovel:2510>,
	<gregtech:meta_tool_head_shovel:2511>,
	<gregtech:meta_tool_head_shovel:2516>,
	<gregtech:meta_tool_head_shovel:2519>,
	<gregtech:meta_tool_head_shovel:2520>
];

// Удаление крафта из верстака всех оголовий лопат из грега
for item in GTtoolHeadShovel{
    recipes.remove(item);
}

// Таблица всех клинков меча из грега 
global GTtoolHeadSword as IItemStack[] = [
	<gregtech:meta_tool_head_sword:2>,
	<gregtech:meta_tool_head_sword:22>,
	<gregtech:meta_tool_head_sword:23>,
	<gregtech:meta_tool_head_sword:50>,
	<gregtech:meta_tool_head_sword:51>,
	<gregtech:meta_tool_head_sword:61>,
	<gregtech:meta_tool_head_sword:64>,
	<gregtech:meta_tool_head_sword:66>,
	<gregtech:meta_tool_head_sword:75>,
	<gregtech:meta_tool_head_sword:77>,
	<gregtech:meta_tool_head_sword:109>,
	<gregtech:meta_tool_head_sword:113>,
	<gregtech:meta_tool_head_sword:115>,
	<gregtech:meta_tool_head_sword:116>,
	<gregtech:meta_tool_head_sword:117>,
	<gregtech:meta_tool_head_sword:124>,
	<gregtech:meta_tool_head_sword:125>,
	<gregtech:meta_tool_head_sword:127>,
	<gregtech:meta_tool_head_sword:128>,
	<gregtech:meta_tool_head_sword:129>,
	<gregtech:meta_tool_head_sword:257>,
	<gregtech:meta_tool_head_sword:259>,
	<gregtech:meta_tool_head_sword:260>,
	<gregtech:meta_tool_head_sword:276>,
	<gregtech:meta_tool_head_sword:278>,
	<gregtech:meta_tool_head_sword:281>,
	<gregtech:meta_tool_head_sword:287>,
	<gregtech:meta_tool_head_sword:290>,
	<gregtech:meta_tool_head_sword:300>,
	<gregtech:meta_tool_head_sword:301>,
	<gregtech:meta_tool_head_sword:302>,
	<gregtech:meta_tool_head_sword:303>,
	<gregtech:meta_tool_head_sword:311>,
	<gregtech:meta_tool_head_sword:314>,
	<gregtech:meta_tool_head_sword:323>,
	<gregtech:meta_tool_head_sword:324>,
	<gregtech:meta_tool_head_sword:329>,
	<gregtech:meta_tool_head_sword:331>,
	<gregtech:meta_tool_head_sword:335>,
	<gregtech:meta_tool_head_sword:344>,
	<gregtech:meta_tool_head_sword:396>,
	<gregtech:meta_tool_head_sword:2004>,
	<gregtech:meta_tool_head_sword:2005>,
	<gregtech:meta_tool_head_sword:2006>,
	<gregtech:meta_tool_head_sword:2011>,
	<gregtech:meta_tool_head_sword:2012>,
	<gregtech:meta_tool_head_sword:2013>,
	<gregtech:meta_tool_head_sword:2014>,
	<gregtech:meta_tool_head_sword:2016>,
	<gregtech:meta_tool_head_sword:2017>,
	<gregtech:meta_tool_head_sword:2036>,
	<gregtech:meta_tool_head_sword:2042>,
	<gregtech:meta_tool_head_sword:2049>,
	<gregtech:meta_tool_head_sword:2062>,
	<gregtech:meta_tool_head_sword:2510>,
	<gregtech:meta_tool_head_sword:2511>,
	<gregtech:meta_tool_head_sword:2516>,
	<gregtech:meta_tool_head_sword:2519>,
	<gregtech:meta_tool_head_sword:2520>
];

// Удаление крафта из верстака всех клинков меча из грега
for item in GTtoolHeadSword{
    recipes.remove(item);
}

// Таблица всех оголовьев топоров из грега 
global GTtoolHeadAxe as IItemStack[] = [
	<gregtech:meta_tool_head_axe:2>,
	<gregtech:meta_tool_head_axe:22>,
	<gregtech:meta_tool_head_axe:23>,
	<gregtech:meta_tool_head_axe:50>,
	<gregtech:meta_tool_head_axe:51>,
	<gregtech:meta_tool_head_axe:61>,
	<gregtech:meta_tool_head_axe:64>,
	<gregtech:meta_tool_head_axe:66>,
	<gregtech:meta_tool_head_axe:75>,
	<gregtech:meta_tool_head_axe:77>,
	<gregtech:meta_tool_head_axe:109>,
	<gregtech:meta_tool_head_axe:113>,
	<gregtech:meta_tool_head_axe:115>,
	<gregtech:meta_tool_head_axe:116>,
	<gregtech:meta_tool_head_axe:117>,
	<gregtech:meta_tool_head_axe:124>,
	<gregtech:meta_tool_head_axe:125>,
	<gregtech:meta_tool_head_axe:127>,
	<gregtech:meta_tool_head_axe:128>,
	<gregtech:meta_tool_head_axe:129>,
	<gregtech:meta_tool_head_axe:257>,
	<gregtech:meta_tool_head_axe:259>,
	<gregtech:meta_tool_head_axe:260>,
	<gregtech:meta_tool_head_axe:276>,
	<gregtech:meta_tool_head_axe:278>,
	<gregtech:meta_tool_head_axe:281>,
	<gregtech:meta_tool_head_axe:287>,
	<gregtech:meta_tool_head_axe:290>,
	<gregtech:meta_tool_head_axe:300>,
	<gregtech:meta_tool_head_axe:301>,
	<gregtech:meta_tool_head_axe:302>,
	<gregtech:meta_tool_head_axe:303>,
	<gregtech:meta_tool_head_axe:311>,
	<gregtech:meta_tool_head_axe:314>,
	<gregtech:meta_tool_head_axe:323>,
	<gregtech:meta_tool_head_axe:324>,
	<gregtech:meta_tool_head_axe:329>,
	<gregtech:meta_tool_head_axe:331>,
	<gregtech:meta_tool_head_axe:335>,
	<gregtech:meta_tool_head_axe:344>,
	<gregtech:meta_tool_head_axe:396>,
	<gregtech:meta_tool_head_axe:2004>,
	<gregtech:meta_tool_head_axe:2005>,
	<gregtech:meta_tool_head_axe:2006>,
	<gregtech:meta_tool_head_axe:2011>,
	<gregtech:meta_tool_head_axe:2012>,
	<gregtech:meta_tool_head_axe:2013>,
	<gregtech:meta_tool_head_axe:2014>,
	<gregtech:meta_tool_head_axe:2016>,
	<gregtech:meta_tool_head_axe:2017>,
	<gregtech:meta_tool_head_axe:2036>,
	<gregtech:meta_tool_head_axe:2042>,
	<gregtech:meta_tool_head_axe:2049>,
	<gregtech:meta_tool_head_axe:2062>,
	<gregtech:meta_tool_head_axe:2510>,
	<gregtech:meta_tool_head_axe:2511>,
	<gregtech:meta_tool_head_axe:2516>,
	<gregtech:meta_tool_head_axe:2519>,
	<gregtech:meta_tool_head_axe:2520>
];

// Удаление крафта из верстака всех оголовьев топоров из грега
for item in GTtoolHeadAxe{
    recipes.remove(item);
}

// Таблица всех оголовьев лезвий мотыг из грега
global GTtoolHeadHoe as IItemStack[] = [
	<gregtech:meta_tool_head_hoe:2>,
	<gregtech:meta_tool_head_hoe:22>,
	<gregtech:meta_tool_head_hoe:23>,
	<gregtech:meta_tool_head_hoe:50>,
	<gregtech:meta_tool_head_hoe:51>,
	<gregtech:meta_tool_head_hoe:61>,
	<gregtech:meta_tool_head_hoe:64>,
	<gregtech:meta_tool_head_hoe:66>,
	<gregtech:meta_tool_head_hoe:75>,
	<gregtech:meta_tool_head_hoe:77>,
	<gregtech:meta_tool_head_hoe:109>,
	<gregtech:meta_tool_head_hoe:113>,
	<gregtech:meta_tool_head_hoe:115>,
	<gregtech:meta_tool_head_hoe:116>,
	<gregtech:meta_tool_head_hoe:117>,
	<gregtech:meta_tool_head_hoe:124>,
	<gregtech:meta_tool_head_hoe:125>,
	<gregtech:meta_tool_head_hoe:127>,
	<gregtech:meta_tool_head_hoe:128>,
	<gregtech:meta_tool_head_hoe:129>,
	<gregtech:meta_tool_head_hoe:257>,
	<gregtech:meta_tool_head_hoe:259>,
	<gregtech:meta_tool_head_hoe:260>,
	<gregtech:meta_tool_head_hoe:276>,
	<gregtech:meta_tool_head_hoe:278>,
	<gregtech:meta_tool_head_hoe:281>,
	<gregtech:meta_tool_head_hoe:287>,
	<gregtech:meta_tool_head_hoe:290>,
	<gregtech:meta_tool_head_hoe:300>,
	<gregtech:meta_tool_head_hoe:301>,
	<gregtech:meta_tool_head_hoe:302>,
	<gregtech:meta_tool_head_hoe:303>,
	<gregtech:meta_tool_head_hoe:311>,
	<gregtech:meta_tool_head_hoe:314>,
	<gregtech:meta_tool_head_hoe:323>,
	<gregtech:meta_tool_head_hoe:324>,
	<gregtech:meta_tool_head_hoe:329>,
	<gregtech:meta_tool_head_hoe:331>,
	<gregtech:meta_tool_head_hoe:335>,
	<gregtech:meta_tool_head_hoe:344>,
	<gregtech:meta_tool_head_hoe:396>,
	<gregtech:meta_tool_head_hoe:2004>,
	<gregtech:meta_tool_head_hoe:2005>,
	<gregtech:meta_tool_head_hoe:2006>,
	<gregtech:meta_tool_head_hoe:2011>,
	<gregtech:meta_tool_head_hoe:2012>,
	<gregtech:meta_tool_head_hoe:2013>,
	<gregtech:meta_tool_head_hoe:2014>,
	<gregtech:meta_tool_head_hoe:2016>,
	<gregtech:meta_tool_head_hoe:2017>,
	<gregtech:meta_tool_head_hoe:2036>,
	<gregtech:meta_tool_head_hoe:2042>,
	<gregtech:meta_tool_head_hoe:2049>,
	<gregtech:meta_tool_head_hoe:2062>,
	<gregtech:meta_tool_head_hoe:2510>,
	<gregtech:meta_tool_head_hoe:2511>,
	<gregtech:meta_tool_head_hoe:2516>,
	<gregtech:meta_tool_head_hoe:2519>,
	<gregtech:meta_tool_head_hoe:2520>
];

// Удаление крафта из верстака всех оголовьев лезвий мотыг из грега + удаление из NEI
for item in GTtoolHeadHoe{
    mods.jei.JEI.removeAndHide(item);
	item.addTooltip("");
}

// Таблица всех оголовий кос из грега 
global GTtoolHeadSense as IItemStack[] = [
	<gregtech:meta_tool_head_sense:2>,
	<gregtech:meta_tool_head_sense:22>,
	<gregtech:meta_tool_head_sense:23>,
	<gregtech:meta_tool_head_sense:50>,
	<gregtech:meta_tool_head_sense:51>,
	<gregtech:meta_tool_head_sense:61>,
	<gregtech:meta_tool_head_sense:64>,
	<gregtech:meta_tool_head_sense:66>,
	<gregtech:meta_tool_head_sense:75>,
	<gregtech:meta_tool_head_sense:77>,
	<gregtech:meta_tool_head_sense:109>,
	<gregtech:meta_tool_head_sense:113>,
	<gregtech:meta_tool_head_sense:115>,
	<gregtech:meta_tool_head_sense:116>,
	<gregtech:meta_tool_head_sense:117>,
	<gregtech:meta_tool_head_sense:124>,
	<gregtech:meta_tool_head_sense:125>,
	<gregtech:meta_tool_head_sense:127>,
	<gregtech:meta_tool_head_sense:128>,
	<gregtech:meta_tool_head_sense:129>,
	<gregtech:meta_tool_head_sense:257>,
	<gregtech:meta_tool_head_sense:259>,
	<gregtech:meta_tool_head_sense:260>,
	<gregtech:meta_tool_head_sense:276>,
	<gregtech:meta_tool_head_sense:278>,
	<gregtech:meta_tool_head_sense:281>,
	<gregtech:meta_tool_head_sense:287>,
	<gregtech:meta_tool_head_sense:290>,
	<gregtech:meta_tool_head_sense:300>,
	<gregtech:meta_tool_head_sense:301>,
	<gregtech:meta_tool_head_sense:302>,
	<gregtech:meta_tool_head_sense:303>,
	<gregtech:meta_tool_head_sense:311>,
	<gregtech:meta_tool_head_sense:314>,
	<gregtech:meta_tool_head_sense:323>,
	<gregtech:meta_tool_head_sense:324>,
	<gregtech:meta_tool_head_sense:329>,
	<gregtech:meta_tool_head_sense:331>,
	<gregtech:meta_tool_head_sense:335>,
	<gregtech:meta_tool_head_sense:344>,
	<gregtech:meta_tool_head_sense:396>,
	<gregtech:meta_tool_head_sense:2004>,
	<gregtech:meta_tool_head_sense:2005>,
	<gregtech:meta_tool_head_sense:2006>,
	<gregtech:meta_tool_head_sense:2011>,
	<gregtech:meta_tool_head_sense:2012>,
	<gregtech:meta_tool_head_sense:2013>,
	<gregtech:meta_tool_head_sense:2014>,
	<gregtech:meta_tool_head_sense:2016>,
	<gregtech:meta_tool_head_sense:2017>,
	<gregtech:meta_tool_head_sense:2036>,
	<gregtech:meta_tool_head_sense:2042>,
	<gregtech:meta_tool_head_sense:2049>,
	<gregtech:meta_tool_head_sense:2062>,
	<gregtech:meta_tool_head_sense:2510>,
	<gregtech:meta_tool_head_sense:2511>,
	<gregtech:meta_tool_head_sense:2516>,
	<gregtech:meta_tool_head_sense:2519>,
	<gregtech:meta_tool_head_sense:2520>
];

// Удаление крафта из верстака всех оголовий кос из грега
for item in GTtoolHeadSense{
    recipes.remove(item);
}

// Таблица всех шахтерских молотов из грега 
global GTtoolMiningHammer as IItemStack[] = [
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "aluminium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "chrome"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "cobalt"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "iridium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "iron"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "manganese"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "molybdenum"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "neodymium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "osmium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "palladium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "thorium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "titanium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "tungsten"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "uranium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "uranium_235"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "naquadah"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "neutronium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "tritanium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "duranium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "brass"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "bronze"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "diamond"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "emerald"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "invar"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "magnalium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "rose_gold"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "black_bronze"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "ruby"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "sapphire"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "topaz"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "ultimet"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "osmiridium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "olivine"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "opal"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "amethyst"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "black_steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "garnet_red"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "rhodium_plated_palladium"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "red_steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "blue_steel"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "hssg"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "hsse"}}),
	<gregtech:meta_tool:19>.withTag({"GT.ToolStats": {Material: "hsss"}})
];

// Таблица муки из ТФК
global TFC_flour as IItemStack[] = [
	<tfc:food/barley_flour>,
	<tfc:food/cornmeal_flour>,
	<tfc:food/oat_flour>,
	<tfc:food/rice_flour>,
	<tfc:food/rye_flour>,
	<tfc:food/wheat_flour>
];

// Таблица теста из ТФК
global TFC_dough as IItemStack[] = [
	<tfc:food/barley_dough>,
	<tfc:food/cornmeal_dough>,
	<tfc:food/rice_dough>,
	<tfc:food/oat_dough>,
	<tfc:food/rye_dough>,
	<tfc:food/wheat_dough>
];

// Таблица хлеба из ТФК
global TFC_bread as IItemStack[] = [
	<tfc:food/barley_bread>,
	<tfc:food/cornbread>,
	<tfc:food/rice_bread>,
	<tfc:food/oat_bread>,
	<tfc:food/rye_bread>,
	<tfc:food/wheat_bread>
];

// Таблица кустов из ТФК
global TFC_berry_bush as IItemStack[] = [
	<tfc:berry_bush/blackberry>,
	<tfc:berry_bush/blueberry>,
	<tfc:berry_bush/bunch_berry>,
	<tfc:berry_bush/cloud_berry>,
	<tfc:berry_bush/cranberry>,
	<tfc:berry_bush/elderberry>,
	<tfc:berry_bush/gooseberry>,
	<tfc:berry_bush/raspberry>,
	<tfc:berry_bush/snow_berry>,
	<tfc:berry_bush/strawberry>,
	<tfc:berry_bush/wintergreen_berry>,
	<ca:tea_bush>
];

// Таблица ягод из кустов из ТФК
global TFC_berry as IItemStack[] = [
	<tfc:food/blackberry>,
	<tfc:food/blueberry>,
	<tfc:food/bunch_berry>,
	<tfc:food/cloud_berry>,
	<tfc:food/cranberry>,
	<tfc:food/elderberry>,
	<tfc:food/gooseberry>,
	<tfc:food/raspberry>,
	<tfc:food/snow_berry>,
	<tfc:food/strawberry>,
	<tfc:food/wintergreen_berry>,
	<ca:tea_leaves>
];

// Таблица саженцев фруктовых деревьев из ТФК
global TFC_fruit_trees as IItemStack[] = [
	<tfc:fruit_trees/sapling/banana>,
	<tfc:fruit_trees/sapling/cherry>,
	<tfc:fruit_trees/sapling/green_apple>,
	<tfc:fruit_trees/sapling/lemon>,
	<tfc:fruit_trees/sapling/olive>,
	<tfc:fruit_trees/sapling/orange>,
	<tfc:fruit_trees/sapling/peach>,
	<tfc:fruit_trees/sapling/plum>,
	<tfc:fruit_trees/sapling/red_apple>,
	<ca:coffee_sapling>
];

// Таблица фруктов из ТФК
global TFC_fruit as IItemStack[] = [
	<tfc:food/banana>,
	<tfc:food/cherry>,
	<tfc:food/green_apple>,
	<tfc:food/lemon>,
	<tfc:food/olive>,
	<tfc:food/orange>,
	<tfc:food/peach>,
	<tfc:food/plum>,
	<tfc:food/red_apple>,
	<ca:coffee_cherries>
];

// Таблица пылек материалов для переплавки в плавильне
global Greg_metl_dust as IItemStack[] = [
	<metaitem:dustGold>,
	<metaitem:dustIron>,
	<metaitem:dustAntimony>,
	<metaitem:dustBeryllium>,
	<metaitem:dustBismuth>,
	<metaitem:dustCobalt>,
	<metaitem:dustCopper>,
	<metaitem:dustGallium>,
	<metaitem:dustIndium>,
	<metaitem:dustLead>,
	<metaitem:dustManganese>,
	<metaitem:dustMolybdenum>,
	<metaitem:dustNickel>,
	<metaitem:dustPlatinum>,
	<metaitem:dustPlutonium>,
	<metaitem:dustPlutonium241>,
	<metaitem:dustSilver>,
	<metaitem:dustTantalum>,
	<metaitem:dustThorium>,
	<metaitem:dustTin>,
	<metaitem:dustUranium>,
	<metaitem:dustUranium235>,
	<metaitem:dustZinc>,
	<metaitem:dustAnnealedCopper>,
	<metaitem:dustBatteryAlloy>,
	<metaitem:dustBrass>,
	<metaitem:dustBronze>,
	<metaitem:dustCupronickel>,
	<metaitem:dustElectrum>,
	<metaitem:dustInvar>,
	<metaitem:dustMagnalium>,
	<metaitem:dustSolderingAlloy>,
	<metaitem:dustTinAlloy>,
	<metaitem:dustWroughtIron>,
	<metaitem:dustIndiumGalliumPhosphide>,
	<metaitem:dustNickelZincFerrite>,
	<metaitem:dustCobaltBrass>,
	<metaitem:dustPotin>,
	<metaitem:dustBorosilicateGlass>,
	<metaitem:dustRedAlloy>,
	<metaitem:dustBlueAlloy>
];

// Таблица получаемых слитков в плавильне
global Greg_metl_ingot as IItemStack[] = [
	<minecraft:gold_ingot>,
	<minecraft:iron_ingot>,
	<metaitem:ingotAntimony>,
	<metaitem:ingotBeryllium>,
	<metaitem:ingotBismuth>,
	<metaitem:ingotCobalt>,
	<metaitem:ingotCopper>,
	<metaitem:ingotGallium>,
	<metaitem:ingotIndium>,
	<metaitem:ingotLead>,
	<metaitem:ingotManganese>,
	<metaitem:ingotMolybdenum>,
	<metaitem:ingotNickel>,
	<metaitem:ingotPlatinum>,
	<metaitem:ingotPlutonium>,
	<metaitem:ingotPlutonium241>,
	<metaitem:ingotSilver>,
	<metaitem:ingotTantalum>,
	<metaitem:ingotThorium>,
	<metaitem:ingotTin>,
	<metaitem:ingotUranium>,
	<metaitem:ingotUranium235>,
	<metaitem:ingotZinc>,
	<metaitem:ingotAnnealedCopper>,
	<metaitem:ingotBatteryAlloy>,
	<metaitem:ingotBrass>,
	<metaitem:ingotBronze>,
	<metaitem:ingotCupronickel>,
	<metaitem:ingotElectrum>,
	<metaitem:ingotInvar>,
	<metaitem:ingotMagnalium>,
	<metaitem:ingotSolderingAlloy>,
	<metaitem:ingotTinAlloy>,
	<metaitem:ingotWroughtIron>,
	<metaitem:ingotIndiumGalliumPhosphide>,
	<metaitem:ingotNickelZincFerrite>,
	<metaitem:ingotCobaltBrass>,
	<metaitem:ingotPotin>,
	<metaitem:ingotBorosilicateGlass>,
	<metaitem:ingotRedAlloy>,
	<metaitem:ingotBlueAlloy>
];

// Таблица пылек горных пород ТФК
global TFC_RockDust as IItemStack[] = [
	<metaitem:dustGranite>,
	<metaitem:dustDiorite>,
	<metaitem:dustGabbro>,
	<metaitem:dustShale>,
	<metaitem:dustClaystone>,
	<metaitem:dustSalt>,
	<metaitem:dustLimestone>,
	<metaitem:dustConglomerate>,
	<metaitem:dustDolomite>,
	<metaitem:dustChert>,
	<metaitem:dustChalk>,
	<metaitem:dustRhyolite>,
	<metaitem:dustBasalt>,
	<metaitem:dustAndesite>,
	<metaitem:dustDacite>,
	<metaitem:dustQuartzite>,
	<metaitem:dustSlate>,
	<metaitem:dustPhyllite>,
	<metaitem:dustSchist>,
	<metaitem:dustGneiss>,
	<metaitem:dustMarble>
];

// Таблица слитков из ТФК
global TFC_Ingot as IItemStack[] = [
	<tfc:metal/ingot/bismuth>,
	<tfc:metal/ingot/bismuth_bronze>,
	<tfc:metal/ingot/black_bronze>,
	<tfc:metal/ingot/brass>,
	<tfc:metal/ingot/bronze>,
	<tfc:metal/ingot/copper>,
	<tfc:metal/ingot/gold>,
	<tfc:metal/ingot/lead>,
	<tfc:metal/ingot/nickel>,
	<tfc:metal/ingot/rose_gold>,
	<tfc:metal/ingot/silver>,
	<tfc:metal/ingot/tin>,
	<tfc:metal/ingot/zinc>,
	<tfc:metal/ingot/sterling_silver>,
	<tfc:metal/ingot/wrought_iron>,
	<tfc:metal/ingot/steel>,
	<tfc:metal/ingot/platinum>,
	<tfc:metal/ingot/black_steel>,
	<tfc:metal/ingot/blue_steel>,
	<tfc:metal/ingot/red_steel>
];

// Таблица двойных слитков из ТФК
global TFC_DoubleIngot as IItemStack[] = [
	<tfc:metal/double_ingot/bismuth>,
	<tfc:metal/double_ingot/bismuth_bronze>,
	<tfc:metal/double_ingot/black_bronze>,
	<tfc:metal/double_ingot/brass>,
	<tfc:metal/double_ingot/bronze>,
	<tfc:metal/double_ingot/copper>,
	<tfc:metal/double_ingot/gold>,
	<tfc:metal/double_ingot/lead>,
	<tfc:metal/double_ingot/nickel>,
	<tfc:metal/double_ingot/rose_gold>,
	<tfc:metal/double_ingot/silver>,
	<tfc:metal/double_ingot/tin>,
	<tfc:metal/double_ingot/zinc>,
	<tfc:metal/double_ingot/sterling_silver>,
	<tfc:metal/double_ingot/wrought_iron>,
	<tfc:metal/double_ingot/steel>,
	<tfc:metal/double_ingot/platinum>,
	<tfc:metal/double_ingot/black_steel>,
	<tfc:metal/double_ingot/blue_steel>,
	<tfc:metal/double_ingot/red_steel>
];

// Таблица пластин из ТФК
global TFC_Sheet as IItemStack[] = [
	<tfc:metal/sheet/bismuth>,
	<tfc:metal/sheet/bismuth_bronze>,
	<tfc:metal/sheet/black_bronze>,
	<tfc:metal/sheet/brass>,
	<tfc:metal/sheet/bronze>,
	<tfc:metal/sheet/copper>,
	<tfc:metal/sheet/gold>,
	<tfc:metal/sheet/lead>,
	<tfc:metal/sheet/nickel>,
	<tfc:metal/sheet/rose_gold>,
	<tfc:metal/sheet/silver>,
	<tfc:metal/sheet/tin>,
	<tfc:metal/sheet/zinc>,
	<tfc:metal/sheet/sterling_silver>,
	<tfc:metal/sheet/wrought_iron>,
	<tfc:metal/sheet/steel>,
	<tfc:metal/sheet/platinum>,
	<tfc:metal/sheet/black_steel>,
	<tfc:metal/sheet/blue_steel>,
	<tfc:metal/sheet/red_steel>
];

// Таблица двойных пластин из ТФК
global TFC_DoubleSheet as IItemStack[] = [
	<tfc:metal/double_sheet/bismuth>,
	<tfc:metal/double_sheet/bismuth_bronze>,
	<tfc:metal/double_sheet/black_bronze>,
	<tfc:metal/double_sheet/brass>,
	<tfc:metal/double_sheet/bronze>,
	<tfc:metal/double_sheet/copper>,
	<tfc:metal/double_sheet/gold>,
	<tfc:metal/double_sheet/lead>,
	<tfc:metal/double_sheet/nickel>,
	<tfc:metal/double_sheet/rose_gold>,
	<tfc:metal/double_sheet/silver>,
	<tfc:metal/double_sheet/tin>,
	<tfc:metal/double_sheet/zinc>,
	<tfc:metal/double_sheet/sterling_silver>,
	<tfc:metal/double_sheet/wrought_iron>,
	<tfc:metal/double_sheet/steel>,
	<tfc:metal/double_sheet/platinum>,
	<tfc:metal/double_sheet/black_steel>,
	<tfc:metal/double_sheet/blue_steel>,
	<tfc:metal/double_sheet/red_steel>
];

// Таблица пылек из Грега для слитков и пластин ТФК
global Greg_DustIngot as IItemStack[] = [
	<metaitem:dustBismuth>,
	<metaitem:dustBismuthBronze>,
	<metaitem:dustBlackBronze>,
	<metaitem:dustBrass>,
	<metaitem:dustBronze>,
	<metaitem:dustCopper>,
	<metaitem:dustGold>,
	<metaitem:dustLead>,
	<metaitem:dustNickel>,
	<metaitem:dustRoseGold>,
	<metaitem:dustSilver>,
	<metaitem:dustTin>,
	<metaitem:dustZinc>,
	<metaitem:dustSterlingSilver>,
	<metaitem:dustWroughtIron>,
	<metaitem:dustSteel>,
	<metaitem:dustPlatinum>,
	<metaitem:dustBlackSteel>,
	<metaitem:dustBlueSteel>,
	<metaitem:dustRedSteel>
];

// Таблица наковален из ТФК
global TFC_Anvil as IItemStack[] = [
	<tfc:metal/anvil/bismuth_bronze>,
	<tfc:metal/anvil/black_bronze>,
	<tfc:metal/anvil/bronze>,
	<tfc:metal/anvil/copper>,
	<tfc:metal/anvil/wrought_iron>,
	<tfc:metal/anvil/steel>,
	<tfc:metal/anvil/black_steel>,
	<tfc:metal/anvil/blue_steel>,
	<tfc:metal/anvil/red_steel>
];

// Таблица пылек из Грега для наковален ТФК
global Greg_DustAnvil as IItemStack[] = [
	<metaitem:dustBismuthBronze>,
	<metaitem:dustBlackBronze>,
	<metaitem:dustBronze>,
	<metaitem:dustCopper>,
	<metaitem:dustWroughtIron>,
	<metaitem:dustSteel>,
	<metaitem:dustBlackSteel>,
	<metaitem:dustBlueSteel>,
	<metaitem:dustRedSteel>
];


print("Initialized 'TableMaterials'");