//Отключение рецептов кремниевых инструментов
recipes.removeByRecipeName("gregtech:pickaxe_flint");
recipes.removeByRecipeName("gregtech:sword_flint");
recipes.removeByRecipeName("gregtech:axe_flint");
recipes.removeByRecipeName("gregtech:shovel_flint");
recipes.removeByRecipeName("gregtech:knife_flint");
recipes.removeByRecipeName("gregtech:hoe_flint");
recipes.removeByRecipeName("gregtech:mortar_flint");

//Крафт каменного молота
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stone", DigSpeed: 0.0 as float, MaxDurability: 25}}), [<minecraft:stick>, <tfc:stone/hammer_head/igneous_intrusive>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stone", DigSpeed: 0.0 as float, MaxDurability: 25}}), [<minecraft:stick>, <tfc:stone/hammer_head/igneous_extrusive>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stone", DigSpeed: 0.0 as float, MaxDurability: 25}}), [<minecraft:stick>, <tfc:stone/hammer_head/sedimentary>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stone", DigSpeed: 0.0 as float, MaxDurability: 25}}), [<minecraft:stick>, <tfc:stone/hammer_head/metamorphic>]);

//Отключение крафтов молотков с палкой(62)
recipes.removeByRecipeName("gregtech:hammer_naquadah_enriched");
recipes.removeByRecipeName("gregtech:hammer_naquadah_alloy");
recipes.removeByRecipeName("gregtech:hammer_bronze");
recipes.removeByRecipeName("gregtech:hammer_sterling_silver");
recipes.removeByRecipeName("gregtech:hammer_stainless_steel");
recipes.removeByRecipeName("gregtech:hammer_fluxed_electrum");
recipes.removeByRecipeName("gregtech:hammer_thorium");
recipes.removeByRecipeName("gregtech:hammer_duranium");
recipes.removeByRecipeName("gregtech:hammer_diamericium_titanium");
recipes.removeByRecipeName("gregtech:hammer_brass");
recipes.removeByRecipeName("gregtech:hammer_naquadah");
recipes.removeByRecipeName("gregtech:hammer_osmium");
recipes.removeByRecipeName("gregtech:hammer_invar");
recipes.removeByRecipeName("gregtech:hammer_tungsten");
recipes.removeByRecipeName("gregtech:hammer_neutronium");
recipes.removeByRecipeName("gregtech:hammer_vanadium_steel");
recipes.removeByRecipeName("gregtech:hammer_hsse");
recipes.removeByRecipeName("gregtech:hammer_magnalium");
recipes.removeByRecipeName("gregtech:hammer_red_steel");
recipes.removeByRecipeName("gregtech:hammer_neodymium");
recipes.removeByRecipeName("gregtech:hammer_manganese");
recipes.removeByRecipeName("gregtech:hammer_pig_iron");
recipes.removeByRecipeName("gregtech:hammer_copper");
recipes.removeByRecipeName("gregtech:hammer_wrought_iron");
recipes.removeByRecipeName("gregtech:hammer_steel");
recipes.removeByRecipeName("gregtech:hammer_cobalt");
recipes.removeByRecipeName("gregtech:hammer_iron");
recipes.removeByRecipeName("gregtech:hammer_tungsten_steel");
recipes.removeByRecipeName("gregtech:hammer_damascus_steel");
recipes.removeByRecipeName("gregtech:hammer_chrome");
recipes.removeByRecipeName("gregtech:hammer_osmiridium");
recipes.removeByRecipeName("gregtech:hammer_molybdenum");
recipes.removeByRecipeName("gregtech:hammer_titanium");
recipes.removeByRecipeName("gregtech:hammer_rhodium_plated_palladium");
recipes.removeByRecipeName("gregtech:hammer_palladium");
recipes.removeByRecipeName("gregtech:hammer_rose_gold");
recipes.removeByRecipeName("gregtech:hammer_tungsten_carbide");
recipes.removeByRecipeName("gregtech:hammer_uranium");
recipes.removeByRecipeName("gregtech:hammer_hssg");
recipes.removeByRecipeName("gregtech:hammer_blue_steel");
recipes.removeByRecipeName("gregtech:hammer_bismuth_bronze");
recipes.removeByRecipeName("gregtech:hammer_cobalt_brass");
recipes.removeByRecipeName("gregtech:hammer_uranium235");
recipes.removeByRecipeName("gregtech:hammer_black_steel");
recipes.removeByRecipeName("gregtech:hammer_hsss");
recipes.removeByRecipeName("gregtech:hammer_tritanium");
recipes.removeByRecipeName("gregtech:hammer_iridium");
recipes.removeByRecipeName("gregtech:hammer_aluminium");
recipes.removeByRecipeName("gregtech:hammer_ultimet");
recipes.removeByRecipeName("gregtech:hammer_black_bronze");
