// MODS_LOADED: tfg
// --- Добавление рецептов

import classes.Function
import su.terrafirmagreg.modules.wood.api.type.WoodType

WoodType.getTypes().forEach { type ->

// Bookshelf
mods.minecraft.crafting.shapedBuilder()
  .name('wood/bookshelf/' + type.name)
  .output(item('tfg:wood/bookshelf/'+ type.name))
  .row('XXX')
  .row('BBB')
  .row('XXX')
  .key('X', item('tfg:wood/planks/'+ type.name))
  .key('B', ore('bookEmpty'))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/bookshelf/'+ type.name))
    .inputs(item('tfg:wood/planks/'+ type.name) * 6)
    .inputs(ore('bookEmpty') * 3)
    .circuitMeta(10)
    .duration(400)
    .EUt(4)
    .buildAndRegister()

// Barrel
mods.minecraft.crafting.shapedBuilder()
  .name('wood/barrel/' + type.name)
  .output(item('tfg:wood/barrel/'+ type.name))
  .row('X X')
  .row('X X')
  .row('XXX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/barrel/'+ type.name))
    .inputs(item('tfg:wood/lumber/'+ type.name) * 7)
    .circuitMeta(15)
    .duration(205)
    .EUt(4)
    .buildAndRegister()

// Loom
mods.minecraft.crafting.shapedBuilder()
  .name('wood/loom/' + type.name)
  .output(item('tfg:wood/loom/'+ type.name))
  .row('XXX')
  .row('XSX')
  .row('X X')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .key('S', ore('stickWood'))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/loom/'+ type.name))
    .inputs(item('tfg:wood/lumber/'+ type.name) * 7)
    .inputs(ore('stickWood'))
    .circuitMeta(13)
    .duration(210)
    .EUt(4)
    .buildAndRegister()

// Tool Rack
mods.minecraft.crafting.shapedBuilder()
  .name('wood/tool_rack/' + type.name)
  .output(item('tfg:wood/tool_rack/'+ type.name))
  .row('XXX')
  .row('   ')
  .row('XXX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/tool_rack/'+ type.name))
    .inputs(item('tfg:wood/lumber/'+ type.name) * 6)
    .circuitMeta(14)
    .duration(205)
    .EUt(4)
    .buildAndRegister()

// Chest
mods.minecraft.crafting.shapedBuilder()
  .name('wood/chest/' + type.name)
  .output(item('tfg:wood/chest/'+ type.name))
  .row('XXX')
  .row('X X')
  .row('XXX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/chest/'+ type.name))
    .inputs(item('tfg:wood/lumber/'+ type.name) * 8)
    .circuitMeta(12)
    .duration(280)
    .EUt(4)
    .buildAndRegister()

// Chest Trapped
mods.minecraft.crafting.shapelessBuilder()
  .name('wood/chest_trapped/' + type.name)
  .output(item('tfg:wood/chest_trapped/'+ type.name))
  .input(item('tfg:wood/chest/'+ type.name))
  .input(item('minecraft:tripwire_hook'))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/chest_trapped/'+ type.name))
    .inputs(item('tfg:wood/chest/'+ type.name))
    .inputs(item('minecraft:tripwire_hook'))
    .duration(200)
    .EUt(4)
    .buildAndRegister()

// Workbench
mods.minecraft.crafting.shapedBuilder()
  .name('wood/workbench/' + type.name)
  .output(item('tfg:wood/workbench/'+ type.name))
  .row('XX')
  .row('XX')
  .key('X', item('tfg:wood/planks/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/workbench/'+ type.name))
    .inputs(item('tfg:wood/planks/'+ type.name) * 4)
    .circuitMeta(11)
    .duration(250)
    .EUt(4)
    .buildAndRegister()

// Pressure Plate
mods.minecraft.crafting.shapedBuilder()
  .name('wood/pressure_plate/' + type.name)
  .output(item('tfg:wood/pressure_plate/'+ type.name))
  .row('XX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/pressure_plate/'+ type.name) * 4)
    .inputs(item('tfg:wood/planks/'+ type.name) * 2)
    .inputs(metaitem('springIron'))
    .circuitMeta(4)
    .duration(200)
    .EUt(7)
    .buildAndRegister()

// Fence
mods.minecraft.crafting.shapedBuilder()
  .name('wood/fence/' + type.name)
  .output(item('tfg:wood/fence/'+ type.name) * 2)
  .row('XBX')
  .row('XBX')
  .key('X', item('tfg:wood/planks/'+ type.name))
  .key('B', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/fence/'+ type.name) * 4)
    .inputs(item('tfg:wood/planks/'+ type.name) * 4)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 2)
    .circuitMeta(1)
    .duration(200)
    .EUt(7)
    .buildAndRegister()  

// Fence Log
mods.minecraft.crafting.shapedBuilder()
  .name('wood/fence_log/' + type.name)
  .output(item('tfg:wood/fence_log/'+ type.name) * 2)
  .row('XBX')
  .row('XBX')
  .key('X', item('tfg:wood/log/'+ type.name))
  .key('B', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/fence_log/'+ type.name) * 4)
    .inputs(item('tfg:wood/log/'+ type.name) * 4)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 2)
    .circuitMeta(1)
    .duration(200)
    .EUt(7)
    .buildAndRegister() 

// Fence Gate
mods.minecraft.crafting.shapedBuilder()
  .name('wood/fence_gate/' + type.name)
  .output(item('tfg:wood/fence_gate/'+ type.name) * 4)
  .row('BXB')
  .row('BXB')
  .key('X', item('tfg:wood/planks/'+ type.name))
  .key('B', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/fence_gate/'+ type.name) * 8)
    .inputs(item('tfg:wood/planks/'+ type.name) * 4)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 2)
    .circuitMeta(2)
    .duration(200)
    .EUt(7)
    .buildAndRegister()  

// Fence Gate Log
mods.minecraft.crafting.shapedBuilder()
  .name('wood/fence_gate_log/' + type.name)
  .output(item('tfg:wood/fence_gate_log/'+ type.name) * 4)
  .row('BXB')
  .row('BXB')
  .key('X', item('tfg:wood/log/'+ type.name))
  .key('B', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/fence_gate_log/'+ type.name) * 8)
    .inputs(item('tfg:wood/log/'+ type.name) * 4)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 2)
    .circuitMeta(2)
    .duration(200)
    .EUt(7)
    .buildAndRegister() 

// Button
mods.minecraft.crafting.shapelessBuilder()
  .name('wood/button/' + type.name)
  .output(item('tfg:wood/button/'+ type.name))
  .input(item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/button/'+ type.name) * 6)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 3)
    .inputs(metaitem('springSmallIron'))
    .duration(200)
    .EUt(7)
    .buildAndRegister()  

// Door
mods.minecraft.crafting.shapedBuilder()
  .name('wood/door/' + type.name)
  .output(item('tfg:wood/door/'+ type.name) * 2)
  .row('XX')
  .row('XX')
  .row('XX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/door/'+ type.name) * 2)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 6)
    .circuitMeta(8)
    .duration(350)
    .EUt(4)
    .buildAndRegister()

// Trapdoor
mods.minecraft.crafting.shapedBuilder()
  .name('wood/trapdoor/' + type.name)
  .output(item('tfg:wood/trapdoor/'+ type.name) * 3)
  .row('XXX')
  .row('XXX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/trapdoor/'+ type.name) * 3)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 6)
    .circuitMeta(9)
    .duration(320)
    .EUt(4)
    .buildAndRegister()  

// Planks
mods.minecraft.crafting.shapedBuilder()
  .name('wood/planks/' + type.name)
  .output(item('tfg:wood/planks/'+ type.name))
  .row('XX')
  .row('XX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/planks/'+ type.name))
    .inputs(item('tfg:wood/lumber/'+ type.name) * 4)
    .circuitMeta(3)
    .duration(200)
    .EUt(7)
    .buildAndRegister()

// Stairs
mods.minecraft.crafting.shapedBuilder()
  .name('wood/planks/' + type.name + '/stairs')
  .output(item('tfg:wood/planks/'+ type.name + '_stairs') * 3)
  .row('X  ')
  .row('XX ')
  .row('XXX')
  .key('X', item('tfg:wood/planks/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/planks/'+ type.name + '_stairs') * 4)
    .inputs(item('tfg:wood/planks/'+ type.name) * 6)
    .circuitMeta(7)
    .duration(200)
    .EUt(7)
    .buildAndRegister() 

// Slabs
mods.minecraft.crafting.shapedBuilder()
  .name('wood/planks/' + type.name+ '/slab')
  .output(item('tfg:wood/planks/'+ type.name + '_slab') * 6)
  .row('XXX')
  .key('X', item('tfg:wood/planks/'+ type.name))
  .register()

mods.gregtech.cutter.recipeBuilder()
    .outputs(item('tfg:wood/planks/'+ type.name + '_slab') * 2)
    .inputs(item('tfg:wood/planks/'+ type.name))
    .fluidInputs(fluid('lubricant') * 1)
    .duration(200)
    .EUt(7)
    .buildAndRegister() 

mods.gregtech.cutter.recipeBuilder()
    .outputs(item('tfg:wood/planks/'+ type.name + '_slab') * 2)
    .inputs(item('tfg:wood/planks/'+ type.name))
    .fluidInputs(fluid('distilled_water') * 2)
    .duration(300)
    .EUt(7)
    .buildAndRegister() 

mods.gregtech.cutter.recipeBuilder()
    .outputs(item('tfg:wood/planks/'+ type.name + '_slab') * 2)
    .inputs(item('tfg:wood/planks/'+ type.name))
    .fluidInputs(fluid('water') * 4)
    .duration(400)
    .EUt(7)
    .buildAndRegister() 

// Wall
mods.minecraft.crafting.shapedBuilder()
  .name('wood/planks/' + type.name + '/wall')
  .output(item('tfg:wood/planks/'+ type.name + '_wall') * 6)
  .row('   ')
  .row('XXX')
  .row('XXX')
  .key('X', item('tfg:wood/planks/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/planks/'+ type.name + '_wall'))
    .inputs(item('tfg:wood/planks/'+ type.name))
    .circuitMeta(6)
    .duration(100)
    .EUt(7)
    .buildAndRegister()

// Support
mods.minecraft.crafting.shapedBuilder()
  .name('wood/support/' + type.name)
  .output(item('tfg:wood/support/'+ type.name) * 4)
  .row('SB')
  .row(' B')
  .key('B', item('tfg:wood/log/'+ type.name))
  .key('S', ore('toolSaw'))
  .register()

mods.gregtech.lathe.recipeBuilder()
    .outputs(item('tfg:wood/support/'+ type.name) * 4)
    .inputs(item('tfg:wood/log/'+ type.name))
    .duration(200)
    .EUt(7)
    .buildAndRegister()

// Ladder
mods.minecraft.crafting.shapedBuilder()
  .name('wood/ladder/' + type.name)
  .output(item('tfg:wood/ladder/'+ type.name) * 2)
  .row('XSX')
  .row('XBX')
  .row('XHX')
  .key('S', ore('craftingToolSoftHammer'))
  .key('H', ore('craftingToolHardHammer'))
  .key('B', ore('boltWood'))
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/ladder/'+ type.name) * 2)
    .inputs(item('tfg:wood/lumber/'+ type.name) * 4)
    .inputs(ore('boltWood'))
    .circuitMeta(7)
    .duration(40)
    .EUt(1)
    .buildAndRegister() 

// Boat
mods.minecraft.crafting.shapedBuilder()
  .name('wood/boat/' + type.name)
  .output(item('tfg:wood/boat/'+ type.name))
  .row('   ')
  .row('XRX')
  .row('XXX')
  .key('X', item('tfg:wood/lumber/'+ type.name))
  .key('R', metaitem('rubber_drop'))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/boat/'+ type.name))
    .inputs(item('tfg:wood/lumber/'+ type.name) * 5)
    .inputs(metaitem('rubber_drop'))
    .circuitMeta(16)
    .duration(270)
    .EUt(4)
    .buildAndRegister()

// Wheel
mods.minecraft.crafting.shapedBuilder()
  .name('wood/wheel/' + type.name)
  .output(item('tfg:wood/wheel/'+ type.name))
  .row('SSS')
  .row('SPS')
  .row('SSS')
  .key('P', item('tfg:wood/planks/'+ type.name))
  .key('S', ore('stickWood'))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/wheel/'+ type.name))
    .inputs(item('tfg:wood/planks/'+ type.name))
    .inputs(ore('stickWood') * 8)
    .circuitMeta(17)
    .duration(70)
    .EUt(2)
    .buildAndRegister()

// Plow Cart
mods.minecraft.crafting.shapedBuilder()
  .name('wood/plow_cart/' + type.name)
  .output(item('tfg:wood/plow_cart/'+ type.name))
  .row('SSS')
  .row('PSP')
  .row('WPW')
  .key('P', item('tfg:wood/planks/'+ type.name))
  .key('W', item('tfg:wood/wheel/'+ type.name))
  .key('S', ore('stickWood'))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/plow_cart/'+ type.name))
    .inputs(item('tfg:wood/planks/'+ type.name) * 3)
    .inputs(item('tfg:wood/wheel/'+ type.name) * 2)
    .inputs(ore('stickWood') * 4)
    .circuitMeta(18)
    .duration(70)
    .EUt(2)
    .buildAndRegister()

// Animal Cart
mods.minecraft.crafting.shapedBuilder()
  .name('wood/animal_cart/' + type.name)
  .output(item('tfg:wood/animal_cart/'+ type.name))
  .row('PPP')
  .row('PPP')
  .row('WPW')
  .key('P', item('tfg:wood/planks/'+ type.name))
  .key('W', item('tfg:wood/wheel/'+ type.name))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/animal_cart/'+ type.name))
    .inputs(item('tfg:wood/planks/'+ type.name) * 7)
    .inputs(item('tfg:wood/wheel/'+ type.name) * 2)
    .circuitMeta(19)
    .duration(70)
    .EUt(2)
    .buildAndRegister()

// Supply Cart
mods.minecraft.crafting.shapedBuilder()
  .name('wood/supply_cart/' + type.name)
  .output(item('tfg:wood/supply_cart/'+ type.name))
  .row('PCP')
  .row('PCP')
  .row('WPW')
  .key('P', item('tfg:wood/planks/'+ type.name))
  .key('W', item('tfg:wood/wheel/'+ type.name))
  .key('C', ore('chestWood'))
  .register()

mods.gregtech.assembler.recipeBuilder()
    .outputs(item('tfg:wood/supply_cart/'+ type.name))
    .inputs(item('tfg:wood/planks/'+ type.name) * 4)
    .inputs(item('tfg:wood/wheel/'+ type.name) * 2)
    .inputs(ore('chestWood') * 2)
    .circuitMeta(20)
    .duration(70)
    .EUt(2)
    .buildAndRegister()

// Lumber
mods.minecraft.crafting.shapelessBuilder()
  .name('wood/lumber/' + type.name + '/log')
  .output(item('tfg:wood/lumber/'+ type.name) * 4)
  .input(item('tfg:wood/log/'+ type.name))
  .input(ore('toolSaw'))
  .register()

mods.minecraft.crafting.shapelessBuilder()
  .name('wood/lumber/' + type.name + '/planks')
  .output(item('tfg:wood/lumber/'+ type.name) * 8)
  .input(item('tfg:wood/planks/'+ type.name))
  .input(ore('toolSaw'))
  .register()

mods.gregtech.cutter.recipeBuilder()
    .outputs(item('tfg:wood/lumber/'+ type.name) * 4)
    .outputs(metaitem('dustWood') * 2)
    .inputs(item('tfg:wood/log/'+ type.name))
    .fluidInputs(fluid('lubricant') * 1)
    .duration(210)
    .EUt(7)
    .buildAndRegister() 

mods.gregtech.cutter.recipeBuilder()
    .outputs(item('tfg:wood/lumber/'+ type.name) * 4)
    .outputs(metaitem('dustWood') * 2)
    .inputs(item('tfg:wood/log/'+ type.name))
    .fluidInputs(fluid('distilled_water') * 2)
    .duration(310)
    .EUt(7)
    .buildAndRegister() 

mods.gregtech.cutter.recipeBuilder()
    .outputs(item('tfg:wood/lumber/'+ type.name) * 4)
    .outputs(metaitem('dustWood') * 2)
    .inputs(item('tfg:wood/log/'+ type.name))
    .fluidInputs(fluid('water') * 4)
    .duration(410)
    .EUt(7)
    .buildAndRegister() 

  // Lumber -> dustWood
mods.gregtech.macerator.recipeBuilder()
    .outputs(metaitem('dustWood') * 5)
    .outputs(metaitem('dustSmallWood') * 2)
    .inputs(item('tfg:wood/lumber/'+ type.name))
    .duration(400)
    .EUt(12)
    .buildAndRegister()
}



