//Отключение рецептов кремниевых инструментов
recipes.removeByRecipeName("gregtech:pickaxe_flint");
recipes.removeByRecipeName("gregtech:sword_flint");
recipes.removeByRecipeName("gregtech:axe_flint");
recipes.removeByRecipeName("gregtech:shovel_flint");
recipes.removeByRecipeName("gregtech:knife_flint");
recipes.removeByRecipeName("gregtech:hoe_flint");

//Отключение крафтов голов молотов GT(61)
recipes.remove(<ore:toolHeadHammerNeutronium>);
recipes.remove(<ore:toolHeadHammerEnderium>);
recipes.remove(<ore:toolHeadHammerDuranium>);
recipes.remove(<ore:toolHeadHammerCobalt>);
recipes.remove(<ore:toolHeadHammerTritanium>);
recipes.remove(<ore:toolHeadHammerNaquadahEnriched>);
recipes.remove(<ore:toolHeadHammerNaquadahAlloy>);
recipes.remove(<ore:toolHeadHammerNaquadah>);
recipes.remove(<ore:toolHeadHammerHsss>);
recipes.remove(<ore:toolHeadHammerHsse>);
recipes.remove(<ore:toolHeadHammerHssg>);
recipes.remove(<ore:toolHeadHammerIron>);
recipes.remove(<ore:toolHeadHammerVanadiumSteel>);
recipes.remove(<ore:toolHeadHammerTungstenCarbide>);
recipes.remove(<ore:toolHeadHammerVinteum>);
recipes.remove(<ore:toolHeadHammerGarnetYellow>);
recipes.remove(<ore:toolHeadHammerGarnetRed>);
recipes.remove(<ore:toolHeadHammerCobaltBrass>);
recipes.remove(<ore:toolHeadHammerTungstenSteel>);
recipes.remove(<ore:toolHeadHammerDamascusSteel>);
recipes.remove(<ore:toolHeadHammerBlueSteel>);
recipes.remove(<ore:toolHeadHammerRedSteel>);
recipes.remove(<ore:toolHeadHammerBlackSteel>);
recipes.remove(<ore:toolHeadHammerBismuthBronze>);
recipes.remove(<ore:toolHeadHammerBlackBronze>);
recipes.remove(<ore:toolHeadHammerRoseGold>);
recipes.remove(<ore:toolHeadHammerSterlingSilver>);
recipes.remove(<ore:toolHeadHammerAmethyst>);
recipes.remove(<ore:toolHeadHammerOpal>);
recipes.remove(<ore:toolHeadHammerOlivine>);
recipes.remove(<ore:toolHeadHammerOsmiridium>);
recipes.remove(<ore:toolHeadHammerWroughtIron>);
recipes.remove(<ore:toolHeadHammerUltimet>);
recipes.remove(<ore:toolHeadHammerTopaz>);
recipes.remove(<ore:toolHeadHammerTanzanite>);
recipes.remove(<ore:toolHeadHammerSteel>);
recipes.remove(<ore:toolHeadHammerStainlessSteel>);
recipes.remove(<ore:toolHeadHammerSapphire>);
recipes.remove(<ore:toolHeadHammerRuby>);
recipes.remove(<ore:toolHeadHammerPigIron>);
recipes.remove(<ore:toolHeadHammerMagnalium>);
recipes.remove(<ore:toolHeadHammerInvar>);
recipes.remove(<ore:toolHeadHammerGreenSapphire>);
recipes.remove(<ore:toolHeadHammerEmerald>);
recipes.remove(<ore:toolHeadHammerDiamond>);
recipes.remove(<ore:toolHeadHammerBronze>);
recipes.remove(<ore:toolHeadHammerBrass>);
recipes.remove(<ore:toolHeadHammerBlueTopaz>);
recipes.remove(<ore:toolHeadHammerUranium235>);
recipes.remove(<ore:toolHeadHammerUranium>);
recipes.remove(<ore:toolHeadHammerTungsten>);
recipes.remove(<ore:toolHeadHammerTitanium>);
recipes.remove(<ore:toolHeadHammerThorium>);
recipes.remove(<ore:toolHeadHammerPalladium>);
recipes.remove(<ore:toolHeadHammerOsmium>);
recipes.remove(<ore:toolHeadHammerDarmstadtium>);
recipes.remove(<ore:toolHeadHammerAluminium>);
recipes.remove(<ore:toolHeadHammerMolybdenum>);
recipes.remove(<ore:toolHeadHammerManganese>);
recipes.remove(<ore:toolHeadHammerNeodymium>);
recipes.remove(<ore:toolHeadHammerChrome>);
recipes.remove(<ore:toolHeadHammerIridium>);

//Отключение крафтов молотков с палкой(62)
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "rhodium_plated_palladium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iron"}}));

//Добавление рецептов молотов GT(38)+1
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "copper", DigSpeed: 0.5 as float, MaxDurability: 300}}), [<minecraft:stick>, <tfc:metal/hammer_head/copper>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [<minecraft:stick>, <ore:toolHeadHammerNeutronium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsss", MaxDurability: 15000}}), [<minecraft:stick>, <ore:toolHeadHammerHsss>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hsse", MaxDurability: 19000}}), [<minecraft:stick>, <ore:toolHeadHammerHsse>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "hssg", MaxDurability: 17000}}), [<minecraft:stick>, <ore:toolHeadHammerHssg>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [<minecraft:stick>, <ore:toolHeadHammerVanadiumSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [<minecraft:stick>, <ore:toolHeadHammerCobaltBrass>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [<minecraft:stick>, <ore:toolHeadHammerTungstenSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadHammerDamascusSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadHammerBlueSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadHammerRedSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <ore:toolHeadHammerBlackSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [<minecraft:stick>, <ore:toolHeadHammerBismuthBronze>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <ore:toolHeadHammerBlackBronze>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [<minecraft:stick>, <ore:toolHeadHammerRoseGold>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [<minecraft:stick>, <ore:toolHeadHammerSterlingSilver>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [<minecraft:stick>, <ore:toolHeadHammerOsmiridium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "wrought_iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadHammerWroughtIron>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [<minecraft:stick>, <ore:toolHeadHammerUltimet>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [<minecraft:stick>, <ore:toolHeadHammerSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadHammerStainlessSteel>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [<minecraft:stick>, <ore:toolHeadHammerMagnalium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "invar", MaxDurability: 4500}}), [<minecraft:stick>, <ore:toolHeadHammerInvar>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadHammerDiamond>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <ore:toolHeadHammerBronze>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [<minecraft:stick>, <ore:toolHeadHammerBrass>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [<minecraft:stick>, <ore:toolHeadHammerTungsten>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadHammerTitanium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [<minecraft:stick>, <ore:toolHeadHammerPalladium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [<minecraft:stick>, <ore:toolHeadHammerOsmium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [<minecraft:stick>, <ore:toolHeadHammerDarmstadtium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadHammerNeodymium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadHammerMolybdenum>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [<minecraft:stick>, <ore:toolHeadHammerManganese>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [<minecraft:stick>, <ore:toolHeadHammerChrome>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "cobalt", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadHammerCobalt>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 10550}}), [<minecraft:stick>, <ore:toolHeadHammerIridium>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadHammerIron>]);
recipes.addShapeless(<gregtech:meta_tool:6>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [<minecraft:stick>, <ore:toolHeadHammerAluminium>]);

//Отключение крафтов голов пил GT(61)
recipes.remove(<ore:toolHeadSawNeutronium>);
recipes.remove(<ore:toolHeadSawEnderium>);
recipes.remove(<ore:toolHeadSawDuranium>);
recipes.remove(<ore:toolHeadSawCobalt>);
recipes.remove(<ore:toolHeadSawTritanium>);
recipes.remove(<ore:toolHeadSawNaquadahEnriched>);
recipes.remove(<ore:toolHeadSawNaquadahAlloy>);
recipes.remove(<ore:toolHeadSawNaquadah>);
recipes.remove(<ore:toolHeadSawHsss>);
recipes.remove(<ore:toolHeadSawHsse>);
recipes.remove(<ore:toolHeadSawHssg>);
recipes.remove(<ore:toolHeadSawVanadiumSteel>);
recipes.remove(<ore:toolHeadSawTungstenCarbide>);
recipes.remove(<ore:toolHeadSawVinteum>);
recipes.remove(<ore:toolHeadSawGarnetYellow>);
recipes.remove(<ore:toolHeadSawGarnetRed>);
recipes.remove(<ore:toolHeadSawCobaltBrass>);
recipes.remove(<ore:toolHeadSawTungstenSteel>);
recipes.remove(<ore:toolHeadSawDamascusSteel>);
recipes.remove(<ore:toolHeadSawBlueSteel>);
recipes.remove(<ore:toolHeadSawRedSteel>);
recipes.remove(<ore:toolHeadSawBlackSteel>);
recipes.remove(<ore:toolHeadSawBismuthBronze>);
recipes.remove(<ore:toolHeadSawBlackBronze>);
recipes.remove(<ore:toolHeadSawRoseGold>);
recipes.remove(<ore:toolHeadSawSterlingSilver>);
recipes.remove(<ore:toolHeadSawAmethyst>);
recipes.remove(<ore:toolHeadSawOpal>);
recipes.remove(<ore:toolHeadSawOlivine>);
recipes.remove(<ore:toolHeadSawOsmiridium>);
recipes.remove(<ore:toolHeadSawWroughtIron>);
recipes.remove(<ore:toolHeadSawUltimet>);
recipes.remove(<ore:toolHeadSawTopaz>);
recipes.remove(<ore:toolHeadSawTanzanite>);
recipes.remove(<ore:toolHeadSawSteel>);
recipes.remove(<ore:toolHeadSawStainlessSteel>);
recipes.remove(<ore:toolHeadSawSapphire>);
recipes.remove(<ore:toolHeadSawRuby>);
recipes.remove(<ore:toolHeadSawPigIron>);
recipes.remove(<ore:toolHeadSawMagnalium>);
recipes.remove(<ore:toolHeadSawInvar>);
recipes.remove(<ore:toolHeadSawGreenSapphire>);
recipes.remove(<ore:toolHeadSawEmerald>);
recipes.remove(<ore:toolHeadSawDiamond>);
recipes.remove(<ore:toolHeadSawBronze>);
recipes.remove(<ore:toolHeadSawBrass>);
recipes.remove(<ore:toolHeadSawBlueTopaz>);
recipes.remove(<ore:toolHeadSawUranium235>);
recipes.remove(<ore:toolHeadSawUranium>);
recipes.remove(<ore:toolHeadSawTungsten>);
recipes.remove(<ore:toolHeadSawTitanium>);
recipes.remove(<ore:toolHeadSawThorium>);
recipes.remove(<ore:toolHeadSawPalladium>);
recipes.remove(<ore:toolHeadSawOsmium>);
recipes.remove(<ore:toolHeadSawDarmstadtium>);
recipes.remove(<ore:toolHeadSawNeodymium>);
recipes.remove(<ore:toolHeadSawMolybdenum>);
recipes.remove(<ore:toolHeadSawManganese>);
recipes.remove(<ore:toolHeadSawIron>);
recipes.remove(<ore:toolHeadSawIridium>);
recipes.remove(<ore:toolHeadSawAluminium>);
recipes.remove(<ore:toolHeadSawChrome>);

//Отключение крафтов пил с палкой(61)
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iron"}}));

//Крафт пил(38)+1
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "copper", DigSpeed: 0.5 as float, MaxDurability: 300}}), [<minecraft:stick>, <tfc:metal/saw_blade/copper>]);
//
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [<minecraft:stick>, <ore:toolHeadSawNeutronium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsss", MaxDurability: 15000}}), [<minecraft:stick>, <ore:toolHeadSawHsss>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hsse", MaxDurability: 19000}}), [<minecraft:stick>, <ore:toolHeadSawHsse>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "hssg", MaxDurability: 17000}}), [<minecraft:stick>, <ore:toolHeadSawHssg>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [<minecraft:stick>, <ore:toolHeadSawVanadiumSteel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [<minecraft:stick>, <ore:toolHeadSawCobaltBrass>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [<minecraft:stick>, <ore:toolHeadSawTungstenSteel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadSawDamascusSteel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <ore:toolHeadSawBlackBronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [<minecraft:stick>, <ore:toolHeadSawRoseGold>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [<minecraft:stick>, <ore:toolHeadSawSterlingSilver>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [<minecraft:stick>, <ore:toolHeadSawOsmiridium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [<minecraft:stick>, <ore:toolHeadSawUltimet>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadSawStainlessSteel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [<minecraft:stick>, <ore:toolHeadSawMagnalium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadSawDiamond>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [<minecraft:stick>, <ore:toolHeadSawBrass>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [<minecraft:stick>, <ore:toolHeadSawTungsten>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadSawTitanium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [<minecraft:stick>, <ore:toolHeadSawPalladium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [<minecraft:stick>, <ore:toolHeadSawOsmium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [<minecraft:stick>, <ore:toolHeadSawDarmstadtium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadSawNeodymium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadSawMolybdenum>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [<minecraft:stick>, <ore:toolHeadSawManganese>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [<minecraft:stick>, <ore:toolHeadSawChrome>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 10550}}), [<minecraft:stick>, <ore:toolHeadSawIridium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadSawIron>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [<minecraft:stick>, <ore:toolHeadSawAluminium>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <tfc:metal/saw_blade/bronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <tfc:metal/saw_blade/black_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [<minecraft:stick>, <tfc:metal/saw_blade/bismuth_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/saw_blade/wrought_iron>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [<minecraft:stick>, <tfc:metal/saw_blade/steel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/saw_blade/red_steel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/saw_blade/blue_steel>]);
recipes.addShapeless(<gregtech:meta_tool:5>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <tfc:metal/saw_blade/black_steel>]);

//Отключение крафтов напильника(61)
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "rhodium_plated_palladium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iron"}}));

//Добавление рецептов напильников GT(38)
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [<minecraft:stick>, <ore:toolHeadFileNeutronium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsss", MaxDurability: 15000}}), [<minecraft:stick>, <ore:toolHeadFileHsss>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hsse", MaxDurability: 19000}}), [<minecraft:stick>, <ore:toolHeadFileHsse>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "hssg", MaxDurability: 17000}}), [<minecraft:stick>, <ore:toolHeadFileHssg>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [<minecraft:stick>, <ore:toolHeadFileVanadiumSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [<minecraft:stick>, <ore:toolHeadFileCobaltBrass>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [<minecraft:stick>, <ore:toolHeadFileTungstenSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadFileDamascusSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadFileBlueSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <ore:toolHeadFileRedSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <ore:toolHeadFileBlackSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [<minecraft:stick>, <ore:toolHeadFileBismuthBronze>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [<minecraft:stick>, <ore:toolHeadFileBlackBronze>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [<minecraft:stick>, <ore:toolHeadFileRoseGold>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [<minecraft:stick>, <ore:toolHeadFileSterlingSilver>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [<minecraft:stick>, <ore:toolHeadFileOsmiridium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "wrought_iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadFileWroughtIron>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [<minecraft:stick>, <ore:toolHeadFileUltimet>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [<minecraft:stick>, <ore:toolHeadFileSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadFileStainlessSteel>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [<minecraft:stick>, <ore:toolHeadFileMagnalium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "invar", MaxDurability: 4500}}), [<minecraft:stick>, <ore:toolHeadFileInvar>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [<minecraft:stick>, <ore:toolHeadFileDiamond>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <ore:toolHeadFileBronze>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [<minecraft:stick>, <ore:toolHeadFileBrass>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [<minecraft:stick>, <ore:toolHeadFileTungsten>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 9500}}), [<minecraft:stick>, <ore:toolHeadFileTitanium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [<minecraft:stick>, <ore:toolHeadFilePalladium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [<minecraft:stick>, <ore:toolHeadFileOsmium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [<minecraft:stick>, <ore:toolHeadFileDarmstadtium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadFileNeodymium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [<minecraft:stick>, <ore:toolHeadFileMolybdenum>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [<minecraft:stick>, <ore:toolHeadFileManganese>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [<minecraft:stick>, <ore:toolHeadFileChrome>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "cobalt", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadFileCobalt>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 10550}}), [<minecraft:stick>, <ore:toolHeadFileIridium>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <ore:toolHeadFileIron>]);
recipes.addShapeless(<gregtech:meta_tool:9>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [<minecraft:stick>, <ore:toolHeadFileAluminium>]);

//Отключение крафтов ножей(61)
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neutronium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "enderium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "duranium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tritanium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "naquadah_enriched"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "naquadah_alloy"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "naquadah"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "hsss"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "hsse"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "hssg"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iridium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "vanadium_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten_carbide"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "vinteum"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "garnet_yellow"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "garnet_red"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt_brass"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "damascus_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "blue_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "red_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bismuth_bronze"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_bronze"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "rose_gold"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "sterling_silver"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "amethyst"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "opal"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "olivine"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmiridium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "wrought_iron"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "ultimet"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "topaz"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tanzanite"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "stainless_steel"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "sapphire"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "ruby"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "pig_iron"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "magnalium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "invar"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "chrome"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "green_sapphire"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "emerald"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "diamond"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bronze"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "brass"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "blue_topaz"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "uranium235"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "uranium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "titanium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "thorium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "palladium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "aluminium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neodymium"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "molybdenum"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "manganese"}}));
recipes.remove(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iron"}}));

//Добавление рецептов ножей GT(38)+1
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "copper", DigSpeed: 0.5 as float, MaxDurability: 600}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateCopper>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickCopper>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neutronium"}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateNeutronium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickNeutronium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "Hsss", MaxDurability: 15000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateHsss>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickHsss>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "Hsse", MaxDurability: 117000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateHsse>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickHsse>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "Hssg", MaxDurability: 17000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateHssg>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickHssg>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "vanadium_steel", MaxDurability: 3500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateVanadiumSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickVanadiumSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt_brass", MaxDurability: 2500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateCobaltBrass>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickCobaltBrass>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten_steel", MaxDurability: 12000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateTungstenSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickTungstenSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "damascus_steel", MaxDurability: 5000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateDamascusSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickDamascusSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBlueSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBlueSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateRedSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickRedSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBlackSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBlackSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBismuthBronze>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBismuthBronze>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1460}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBlackBronze>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBlackBronze>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "rose_gold", MaxDurability: 500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateRoseGold>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickRoseGold>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "sterling_silver", MaxDurability: 250}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateSterlingSilver>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickSterlingSilver>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmiridium", MaxDurability: 14500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateOsmiridium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickOsmiridium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "wrought_iron", MaxDurability: 2200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateWroughtIron>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickWroughtIron>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "ultimet", MaxDurability: 7850}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateUltimet>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickUltimet>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3400}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "stainless_steel", MaxDurability: 9500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateStainlessSteel>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickStainlessSteel>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "magnalium", MaxDurability: 1100}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateMagnalium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickMagnalium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "invar", MaxDurability: 4500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateInvar>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickInvar>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "diamond", MaxDurability: 5000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateDiamond>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickDiamond>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBronze>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBronze>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "brass", MaxDurability: 750}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateBrass>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickBrass>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "tungsten", MaxDurability: 10500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateTungsten>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickTungsten>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "titanium", MaxDurability: 11250}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateTitanium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickTitanium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "palladium", MaxDurability: 8500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:platePalladium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickPalladium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "osmium", MaxDurability: 13750}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateOsmium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickOsmium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "darmstadtium"}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateDarmstadtium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickDarmstadtium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "neodymium", MaxDurability: 5650}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateNeodymium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickNeodymium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "molybdenum", MaxDurability: 5650}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateMolybdenum>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickMolybdenum>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "manganese", MaxDurability: 1500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateManganese>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickManganese>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "chrome", MaxDurability: 7000}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateChrome>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickChrome>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "cobalt", MaxDurability: 2200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateCobalt>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickCobalt>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iridium", MaxDurability: 12550}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateIridium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickIridium>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateIron>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickIron>, null]]);
recipes.addShaped(<gregtech:meta_tool:17>.withTag({"GT.ToolStats": {Material: "aluminium", MaxDurability: 7500}}), [[null, null, null],[<ore:craftingToolFile>.firstItem.withEmptyTag(), <ore:plateAluminium>, <ore:craftingToolHardHammer>.firstItem.withEmptyTag()],[null, <ore:stickAluminium>, null]]);

//Рецепты тулов из TFC
//Кирки
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1260}}), [<minecraft:stick>, <tfc:metal/pick_head/bismuth_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1400}}), [<minecraft:stick>, <tfc:metal/pick_head/black_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <tfc:metal/pick_head/bronze>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "copper", MaxDurability: 600}}), [<minecraft:stick>, <tfc:metal/pick_head/copper>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/pick_head/wrought_iron>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3300}}), [<minecraft:stick>, <tfc:metal/pick_head/steel>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <tfc:metal/pick_head/black_steel>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/pick_head/blue_steel>]);
recipes.addShapeless(<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/pick_head/red_steel>]);
//Топоры
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1260}}), [<minecraft:stick>, <tfc:metal/axe_head/bismuth_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1400}}), [<minecraft:stick>, <tfc:metal/axe_head/black_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <tfc:metal/axe_head/bronze>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "copper", MaxDurability: 600}}), [<minecraft:stick>, <tfc:metal/axe_head/copper>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/axe_head/wrought_iron>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3300}}), [<minecraft:stick>, <tfc:metal/axe_head/steel>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <tfc:metal/axe_head/black_steel>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/axe_head/blue_steel>]);
recipes.addShapeless(<gregtech:meta_tool:3>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/axe_head/red_steel>]);
//Мотыги
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1260}}), [<minecraft:stick>, <tfc:metal/hoe_head/bismuth_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1400}}), [<minecraft:stick>, <tfc:metal/hoe_head/black_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <tfc:metal/hoe_head/bronze>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "copper", MaxDurability: 600}}), [<minecraft:stick>, <tfc:metal/hoe_head/copper>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/hoe_head/wrought_iron>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3300}}), [<minecraft:stick>, <tfc:metal/hoe_head/steel>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <tfc:metal/hoe_head/black_steel>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/hoe_head/blue_steel>]);
recipes.addShapeless(<gregtech:meta_tool:4>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/hoe_head/red_steel>]);
//Мечи
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1260}}), [<minecraft:stick>, <tfc:metal/sword_blade/bismuth_bronze>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1400}}), [<minecraft:stick>, <tfc:metal/sword_blade/black_bronze>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <tfc:metal/sword_blade/bronze>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "copper", MaxDurability: 600}}), [<minecraft:stick>, <tfc:metal/sword_blade/copper>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/sword_blade/wrought_iron>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3300}}), [<minecraft:stick>, <tfc:metal/sword_blade/steel>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <tfc:metal/sword_blade/black_steel>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/sword_blade/blue_steel>]);
recipes.addShapeless(<gregtech:meta_tool>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/sword_blade/red_steel>]);
//Лопаты
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "bismuth_bronze", MaxDurability: 1260}}), [<minecraft:stick>, <tfc:metal/shovel_head/bismuth_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "black_bronze", MaxDurability: 1400}}), [<minecraft:stick>, <tfc:metal/shovel_head/black_bronze>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "bronze", MaxDurability: 1300}}), [<minecraft:stick>, <tfc:metal/shovel_head/bronze>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "copper", MaxDurability: 600}}), [<minecraft:stick>, <tfc:metal/shovel_head/copper>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "iron", MaxDurability: 2200}}), [<minecraft:stick>, <tfc:metal/shovel_head/wrought_iron>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "steel", MaxDurability: 3300}}), [<minecraft:stick>, <tfc:metal/shovel_head/steel>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "black_steel", MaxDurability: 4200}}), [<minecraft:stick>, <tfc:metal/shovel_head/black_steel>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "blue_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/shovel_head/blue_steel>]);
recipes.addShapeless(<gregtech:meta_tool:2>.withTag({"GT.ToolStats": {Material: "red_steel", MaxDurability: 6500}}), [<minecraft:stick>, <tfc:metal/shovel_head/red_steel>]);