name: Project Server News
run-name: "Project Server News #${{ github.run_number }}"
on:
  workflow_dispatch:
    inputs:
      project_version:
        required: true
        type: string

jobs:   
  discord-message:
    name: 📱 Discord Message
    runs-on: ubuntu-latest

    steps:
      - name: 📨 Send Discord message
        uses: hugoalh/send-discord-webhook-ghaction@v7.0.5
        with:
          key: ${{ secrets.DISCORD_NEWS_SERVER }}
          username: "TerraFirmaGreg"
          avatar_url: "https://raw.githubusercontent.com/TerraFirmaGreg-Team/.github/main/branding/logo.png"
          content_links_no_embed: .+
          allowed_mentions_parse_users: true
          content: |
            @Xikaro
            **Server updated to**: `${{ inputs.project_version }}`